# Generated By: Claude Code (Claude Fable 5)
"""Entry point for `python -m orchestrator` (run from the plugin root)."""

import sys

from orchestrator.cli import main

if __name__ == "__main__":
    sys.exit(main())
