# Generated By: Claude Code (Claude Fable 5)
"""Agent backend seam for the review orchestrator.

Every model invocation in the orchestrator goes through `run_agent`. It is
the single point a future backend (e.g. codex headless) must reimplement:
same signature, different subprocess. Nothing else in the orchestrator may
spawn an agent.

The Claude implementation shells out to `claude -p --output-format json`
with `--json-schema` for harness-level structured output. Every result
carries the measured `total_cost_usd` from the CLI's result JSON — cost
reporting is real spend, never an estimate.
"""

import json
import os
import subprocess
import sys
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path

ORCHESTRATOR_ROOT = Path(__file__).resolve().parent
PLUGIN_ROOT = ORCHESTRATOR_ROOT.parent
REVIEW_SCHEMAS_DIR = PLUGIN_ROOT / "skills" / "review" / "schemas"

if str(PLUGIN_ROOT) not in sys.path:
    sys.path.insert(0, str(PLUGIN_ROOT))


@dataclass
class AgentResult:
    """Outcome of one headless agent invocation."""

    output: dict | None = None  # structured_output; None on failure
    cost_usd: float = 0.0  # total_cost_usd (0.0 if unavailable)
    permission_denials: list = field(default_factory=list)
    error: str | None = None


def load_resolved_schema(name: str) -> dict:
    """Load a resolved (ref-inlined) schema by base name, e.g. 'agent-output'.

    Strips the `_generated` marker — it is not part of the schema contract
    and must not reach the CLI's --json-schema argument.
    """
    path = REVIEW_SCHEMAS_DIR / f"{name}.resolved.schema.json"
    with path.open("r", encoding="utf-8") as fh:
        schema = json.load(fh)
    schema.pop("_generated", None)
    return schema


_TRACE_LOCK = threading.Lock()


def _write_trace(trace_file, record: dict) -> None:
    """Append one JSON line to the agent trace. Best-effort — tracing must
    never fail a run."""
    if trace_file is None:
        return
    try:
        line = json.dumps(record) + "\n"
        with _TRACE_LOCK, open(trace_file, "a", encoding="utf-8") as fh:
            fh.write(line)
    except OSError:
        pass


# CLAUDE* vars that configure telemetry, not session identity — children
# must keep them or OTEL export silently dies. OTEL_* vars survive the
# scrub on their own (different prefix).
_ENV_KEEP = {
    "CLAUDE_CODE_ENABLE_TELEMETRY",
    "CLAUDE_CODE_ENHANCED_TELEMETRY_BETA",
}


def _scrubbed_env() -> dict:
    """Child env without session-identity CLAUDE* vars.

    The orchestrator may itself run inside a Claude Code session; inherited
    CLAUDE* vars (CLAUDECODE, CLAUDE_CODE_SESSION_ID, ...) could make the
    nested CLI behave as a subagent of that session. Telemetry toggles are
    kept — verified empirically that a scrub of CLAUDE_CODE_ENABLE_TELEMETRY
    kills the child's OTEL export.
    """
    return {
        k: v
        for k, v in os.environ.items()
        if not k.startswith("CLAUDE") or k in _ENV_KEEP
    }


def run_agent(
    prompt: str,
    *,
    schema: dict | None,
    model: str,
    allowed_tools: list[str],
    cwd: str,
    tools: str | None = None,
    effort: str | None = None,
    timeout_s: int = 600,
    trace_file: str | Path | None = None,
    label: str = "",
) -> AgentResult:
    """Run one headless claude agent and parse its result JSON.

    `tools` restricts which built-in tools exist at all (e.g.
    "Read,Glob,Grep" gives an agent no Bash tool, period). `allowed_tools`
    is the permission allowlist within the available set. Both are needed:
    permission rules cannot block commands on the CLI's built-in read-only
    auto-allow list (git diff/log/...), but removing the tool can.

    When `trace_file` is set, every invocation appends one JSON line there:
    the prompt, invocation parameters, outcome, and the raw CLI result.
    The child runs with --no-session-persistence, so this trace is the only
    record of what a sub-agent was asked and answered — the debugging trail.
    """
    started = time.monotonic()

    def _finish(agent_result: AgentResult, raw_result=None) -> AgentResult:
        _write_trace(
            trace_file,
            {
                "label": label,
                "model": model,
                "effort": effort,
                "tools": tools,
                "allowed_tools": allowed_tools,
                "cwd": cwd,
                "elapsed_s": round(time.monotonic() - started, 3),
                "error": agent_result.error,
                "cost_usd": agent_result.cost_usd,
                "denials": agent_result.permission_denials,
                "prompt": prompt,
                "result": raw_result,
            },
        )
        return agent_result

    argv = [
        "claude",
        "-p",
        prompt,
        "--output-format",
        "json",
        "--model",
        model,
        "--no-session-persistence",
        # Deny non-allowlisted tool calls instead of prompting; denials are
        # recorded in permission_denials on the result.
        "--permission-mode",
        "dontAsk",
    ]
    if schema is not None:
        argv += ["--json-schema", json.dumps(schema)]
    if tools is not None:
        argv += ["--tools", tools]
    if effort:
        argv += ["--effort", effort]
    if allowed_tools:
        argv += ["--allowedTools", " ".join(allowed_tools)]

    try:
        proc = subprocess.run(
            argv,
            cwd=cwd,
            env=_scrubbed_env(),
            capture_output=True,
            text=True,
            timeout=timeout_s,
        )
    except subprocess.TimeoutExpired:
        return _finish(AgentResult(error=f"timeout after {timeout_s}s"))
    except OSError as exc:
        return _finish(AgentResult(error=f"failed to spawn claude: {exc}"))

    try:
        result = json.loads(proc.stdout)
    except json.JSONDecodeError:
        stderr_tail = (proc.stderr or "").strip()[-500:]
        return _finish(
            AgentResult(
                error=f"non-JSON output (exit {proc.returncode}): {stderr_tail}"
            ),
            raw_result={"stdout": proc.stdout[-2000:], "stderr": stderr_tail},
        )

    agent_result = AgentResult(
        cost_usd=float(result.get("total_cost_usd") or 0.0),
        permission_denials=result.get("permission_denials") or [],
    )

    if proc.returncode != 0 or result.get("is_error"):
        agent_result.error = f"agent error (exit {proc.returncode}): " + str(
            result.get("result", "")
        )[:500]
        return _finish(agent_result, raw_result=result)

    if schema is not None:
        output = result.get("structured_output")
        if not isinstance(output, dict):
            agent_result.error = "missing structured_output in result"
            return _finish(agent_result, raw_result=result)
        agent_result.output = output
    else:
        agent_result.output = {"text": result.get("result", "")}

    return _finish(agent_result, raw_result=result)
