# Generated By: Claude Code (Claude Fable 5)
"""Agent backend seam for the review orchestrator.

Every model invocation in the orchestrator goes through `run_agent`. It is
the single point a future backend (e.g. codex headless) must reimplement:
same signature, different subprocess. Nothing else in the orchestrator may
spawn an agent.

The Claude implementation shells out to `claude -p --output-format json`;
the Codex implementation uses `codex exec --json`. Both return the same
structured AgentResult to the pipeline.
"""

import json
import os
import re
import signal
import shutil
import subprocess
import sys
import threading
import time
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from types import SimpleNamespace

ORCHESTRATOR_ROOT = Path(__file__).resolve().parent
PLUGIN_ROOT = ORCHESTRATOR_ROOT.parent
REVIEW_SCHEMAS_DIR = PLUGIN_ROOT / "skills" / "review" / "schemas"

if str(PLUGIN_ROOT) not in sys.path:
    sys.path.insert(0, str(PLUGIN_ROOT))


@dataclass
class AgentResult:
    """Outcome of one headless agent invocation."""

    output: dict | None = None  # structured_output; None on failure
    cost_usd: float = 0.0  # total_cost_usd (0.0 if unavailable)
    permission_denials: list = field(default_factory=list)
    error: str | None = None
    # Machine-readable failure class for aggregation/alerting:
    # timeout | spawn | protocol | agent | budget | schema (set by callers) | None
    error_category: str | None = None
    session_id: str = ""  # child session id — joins the trace/ledger to telemetry


def load_resolved_schema(name: str) -> dict:
    """Load a resolved (ref-inlined) schema by base name, e.g. 'agent-output'.

    Strips the `_generated` marker — it is not part of the schema contract
    and must not reach the CLI's --json-schema argument.
    """
    path = REVIEW_SCHEMAS_DIR / f"{name}.resolved.schema.json"
    with path.open("r", encoding="utf-8") as fh:
        schema = json.load(fh)
    schema.pop("_generated", None)
    return schema


_TRACE_LOCK = threading.Lock()


def redact_prompt(prompt: str, redact_text: str | None) -> str:
    """Replace the literal user-authored text in a prompt before tracing.

    Exact-substring replacement of the guidance string the caller supplies —
    no structural heuristics, so no prompt or guidance content can end the
    redaction early or leak around it. Everything else in a prompt is
    project-derived and is the debugging value of the trace.
    """
    if not redact_text:
        return prompt
    return prompt.replace(redact_text, "[guidance redacted from trace]")


def _write_trace(trace_file, record: dict) -> None:
    """Append one JSON line to the agent trace.

    Best-effort — tracing must never fail a run — but failures are warned
    to stderr rather than swallowed silently. The trace file is created
    owner-only: prompts carry project content.
    """
    if trace_file is None:
        return
    try:
        line = json.dumps(record) + "\n"
        # --select-only runs the selector before any stage dir exists.
        os.makedirs(os.path.dirname(str(trace_file)) or ".", exist_ok=True)
        with _TRACE_LOCK:
            fd = os.open(
                str(trace_file), os.O_WRONLY | os.O_CREAT | os.O_APPEND, 0o600
            )
            with os.fdopen(fd, "a", encoding="utf-8") as fh:
                fh.write(line)
    except OSError as exc:
        print(
            f"warning: agent trace write failed ({exc}); "
            f"attempt for {record.get('label')} not traced",
            file=sys.stderr,
        )


# CLAUDE* vars that configure telemetry, not session identity — children
# must keep them or OTEL export silently dies. OTEL_* vars survive the
# scrub on their own (different prefix).
_ENV_KEEP = {
    "CLAUDE_CODE_ENABLE_TELEMETRY",
    "CLAUDE_CODE_ENHANCED_TELEMETRY_BETA",
}
# Env files consulted (first hit wins) when the inherited environment has no
# OTLP endpoint — a long-running parent process can hold an env older than
# the machine's telemetry config. Only telemetry keys are read from them.
_OTEL_ENV_FILE_OVERRIDE = "REVIEW_ORCHESTRATOR_OTEL_ENV"
_OTEL_ENV_FILES = ("/sandbox/.env", "~/.env")


def _telemetry_env_from_file() -> dict:
    """Telemetry keys (OTEL_*, telemetry toggles) from the first env file found.

    Never a general env loader: credentials and unrelated vars in those
    files must not leak into child processes.
    """
    candidates = [os.environ.get(_OTEL_ENV_FILE_OVERRIDE)] + [
        str(Path(path).expanduser()) for path in _OTEL_ENV_FILES
    ]
    for candidate in candidates:
        if not candidate or not Path(candidate).is_file():
            continue
        loaded: dict = {}
        for line in Path(candidate).read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            key = key.strip().removeprefix("export ").strip()
            if key.startswith("OTEL_") or key in _ENV_KEEP:
                loaded[key] = value.strip().strip("'\"")
        if loaded:
            return loaded
    return {}


def _scrubbed_env() -> dict:
    """Child env without session-identity CLAUDE* vars.

    The orchestrator may itself run inside a Claude Code session; inherited
    CLAUDE* vars (CLAUDECODE, CLAUDE_CODE_SESSION_ID, ...) could make the
    nested CLI behave as a subagent of that session. Telemetry toggles are
    kept — verified empirically that a scrub of CLAUDE_CODE_ENABLE_TELEMETRY
    kills the child's OTEL export. When the inherited env lacks an OTLP
    endpoint, telemetry keys are filled in (never overridden) from a
    well-known env file so child sessions still report.
    """
    env = {
        k: v
        for k, v in os.environ.items()
        if not k.startswith("CLAUDE") or k in _ENV_KEEP
    }
    if "OTEL_EXPORTER_OTLP_ENDPOINT" not in env:
        for key, value in _telemetry_env_from_file().items():
            env.setdefault(key, value)
    if "OTEL_EXPORTER_OTLP_ENDPOINT" in env:
        # An endpoint states intent to export; without exporter selections
        # the CLI sends nothing. Default them, never override.
        env.setdefault("CLAUDE_CODE_ENABLE_TELEMETRY", "1")
        env.setdefault("OTEL_METRICS_EXPORTER", "otlp")
        env.setdefault("OTEL_LOGS_EXPORTER", "otlp")
        env.setdefault("OTEL_TRACES_EXPORTER", "otlp")
    return env


def _codex_env() -> tuple[dict, Path]:
    """Run Codex in a writable home while reusing its auth and config."""
    source_home = Path(os.environ.get("CODEX_HOME", Path.home() / ".codex"))
    child_home = Path(tempfile.mkdtemp(prefix="review-codex-home-"))
    for name in ("auth.json", "config.toml"):
        source = source_home / name
        if source.is_file():
            (child_home / name).symlink_to(source)
    env = {
        key: value
        for key, value in os.environ.items()
        if not key.startswith("CODEX_")
    }
    env["CODEX_HOME"] = str(child_home)
    return env, child_home


def _is_budget_stop(result: dict) -> bool:
    """True when the CLI stopped itself on --max-budget-usd.

    Both markers are checked because they come from different layers of the
    result and either alone could be renamed; verified present together on
    an actual budget stop (subtype error_max_budget_usd / terminal_reason
    budget_exhausted).
    """
    return (
        result.get("subtype") == "error_max_budget_usd"
        or result.get("terminal_reason") == "budget_exhausted"
    )


def _codex_result(events: list[dict], returncode: int, stderr: str) -> dict:
    """Normalize Codex JSONL events to the Claude result shape we consume."""
    thread_id = next(
        (event.get("thread_id") for event in events if event.get("type") == "thread.started"),
        "",
    )
    text = ""
    for event in reversed(events):
        item = event.get("item", {})
        if event.get("type") != "item.completed" or item.get("type") != "agent_message":
            continue
        text = item.get("text", "")
        if not text and isinstance(item.get("content"), list):
            text = "".join(
                part.get("text", "") for part in item["content"] if isinstance(part, dict)
            )
        break
    structured = None
    if isinstance(text, str):
        try:
            structured = json.loads(text)
        except json.JSONDecodeError:
            pass
    error = next(
        (event.get("message") or event.get("error") for event in events if event.get("type") == "error"),
        None,
    )
    return {
        "is_error": returncode != 0 or error is not None,
        "session_id": thread_id,
        "total_cost_usd": 0.0,
        "permission_denials": [],
        "result": error or text or stderr.strip(),
        "structured_output": structured,
    }


def run_agent(
    prompt: str,
    *,
    schema: dict | None,
    model: str,
    allowed_tools: list[str],
    cwd: str,
    tools: str | None = None,
    effort: str | None = None,
    timeout_s: int = 3600,
    max_budget_usd: float | None = None,
    session_id: str | None = None,
    resume_session_id: str | None = None,
    persist_session: bool = False,
    debug_file: str | Path | None = None,
    trace_file: str | Path | None = None,
    label: str = "",
    redact: str | None = None,
    otel_attributes: dict | None = None,
    harness: str = "claude",
) -> AgentResult:
    """Run one headless agent harness and parse its structured result.

    `tools` restricts which built-in tools exist at all (e.g.
    "Read,Glob,Grep" gives an agent no Bash tool, period). `allowed_tools`
    is the permission allowlist within the available set. Both are needed:
    permission rules cannot block commands on the CLI's built-in read-only
    auto-allow list (git diff/log/...), but removing the tool can.

    `otel_attributes` are appended to the child's OTEL_RESOURCE_ATTRIBUTES
    (values sanitized for the comma/equals list format) so its telemetry
    carries run-level correlation labels.

    `max_budget_usd` is the real runaway control; `timeout_s` is only a
    latency backstop. The distinction matters because the two failure paths
    are not comparable: a budget stop is the CLI exiting on its own, so it
    still writes its result JSON and its `total_cost_usd` and `session_id`
    are reported. A timeout is SIGKILL, which destroys that JSON — cost and
    session id are then unknowable, and the ledger shows 0.0 for spend that
    was real. Verified against the CLI: budget exhaustion returns exit 1
    with `subtype: "error_max_budget_usd"`, `terminal_reason:
    "budget_exhausted"`, and an accurate cost. The cap is enforced *between
    turns*, so actual spend overshoots it by up to one turn.

    `session_id` is chosen by the caller rather than read back from the
    result, so a killed attempt is still identifiable. `persist_session`
    keeps the session on disk so `resume_session_id` can reopen it — used
    to harvest partial findings from a budget-stopped agent.

    When `trace_file` is set, every invocation appends one JSON line there:
    the prompt (with the literal `redact` text replaced), invocation
    parameters, outcome, and the raw CLI result. `debug_file` additionally
    streams the CLI's own debug log, which — unlike the trace, written only
    after an agent returns — is readable while the agent is still running.
    """
    started = time.monotonic()

    def _finish(agent_result: AgentResult, raw_result=None) -> AgentResult:
        _write_trace(
            trace_file,
            {
                "ts": round(time.time(), 3),
                "label": label,
                "model": model,
                "effort": effort,
                "tools": tools,
                "allowed_tools": allowed_tools,
                "cwd": cwd,
                "elapsed_s": round(time.monotonic() - started, 3),
                "error": agent_result.error,
                "cost_usd": agent_result.cost_usd,
                "denials": agent_result.permission_denials,
                "prompt": redact_prompt(prompt, redact),
                "result": raw_result,
            },
        )
        return agent_result

    if harness not in {"claude", "codex"}:
        return AgentResult(error=f"unsupported agent harness: {harness}", error_category="spawn")

    # Prompt goes via stdin, not argv: argv is world-visible in `ps` and
    # subject to ARG_MAX; prompts carry project content and can be large.
    schema_file = None
    codex_home = None
    if harness == "claude":
        argv = [
            "claude", "-p", "--output-format", "json", "--model", model,
            "--permission-mode", "dontAsk",
        ]
        if not persist_session:
            argv.append("--no-session-persistence")
        if resume_session_id:
            argv += ["--resume", resume_session_id]
        elif session_id:
            argv += ["--session-id", session_id]
        if max_budget_usd is not None:
            argv += ["--max-budget-usd", str(max_budget_usd)]
        if debug_file is not None:
            Path(debug_file).parent.mkdir(parents=True, exist_ok=True)
            argv += ["--debug-file", str(debug_file)]
        if schema is not None:
            argv += ["--json-schema", json.dumps(schema)]
        if tools is not None:
            argv += ["--tools", tools]
        if effort:
            argv += ["--effort", effort]
        if allowed_tools:
            argv += ["--allowedTools", ",".join(allowed_tools)]
        child_env = _scrubbed_env()
    else:
        # Codex has no Claude-style tool allowlist; read-only sandboxing keeps
        # review agents from changing the project while retaining git reads.
        argv = ["codex", "exec", "--json", "--ephemeral", "--sandbox", "read-only"]
        if model not in {"haiku", "sonnet"}:
            argv += ["--model", model]
        if schema is not None:
            schema_file = tempfile.NamedTemporaryFile(
                mode="w", suffix=".json", prefix="review-schema-", delete=False
            )
            json.dump(schema, schema_file)
            schema_file.close()
            argv += ["--output-schema", schema_file.name]
        argv.append("-")
        child_env, codex_home = _codex_env()
    if otel_attributes:
        pairs = ",".join(
            f"{key}={re.sub(r'[,=]', '-', str(value))}"
            for key, value in otel_attributes.items()
        )
        existing = child_env.get("OTEL_RESOURCE_ATTRIBUTES", "")
        child_env["OTEL_RESOURCE_ATTRIBUTES"] = f"{existing},{pairs}" if existing else pairs

    try:
        # start_new_session so a timeout can reap the CLI's own children
        # (the API worker processes it spawns) via the process group.
        popen = subprocess.Popen(
            argv,
            cwd=cwd,
            env=child_env,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            start_new_session=True,
        )
    except OSError as exc:
        if schema_file is not None:
            Path(schema_file.name).unlink(missing_ok=True)
        if codex_home is not None:
            shutil.rmtree(codex_home, ignore_errors=True)
        return _finish(AgentResult(error=f"failed to spawn {harness}: {exc}", error_category="spawn"))
    try:
        stdout, stderr = popen.communicate(input=prompt, timeout=timeout_s)
    except subprocess.TimeoutExpired:
        if schema_file is not None:
            Path(schema_file.name).unlink(missing_ok=True)
        if codex_home is not None:
            shutil.rmtree(codex_home, ignore_errors=True)
        try:
            os.killpg(popen.pid, signal.SIGKILL)
        except OSError:
            pass
        popen.wait()
        # SIGKILL destroyed the result JSON, so cost is unknowable here and
        # stays 0.0 — real spend the ledger cannot see. The caller-chosen
        # session id is the one thing still recoverable.
        return _finish(
            AgentResult(
                error=f"timeout after {timeout_s}s",
                error_category="timeout",
                session_id=resume_session_id or session_id or "",
            )
        )

    proc = SimpleNamespace(
        stdout=stdout, stderr=stderr, returncode=popen.returncode
    )

    if schema_file is not None:
        Path(schema_file.name).unlink(missing_ok=True)
    if codex_home is not None:
        shutil.rmtree(codex_home, ignore_errors=True)

    if harness == "codex":
        events = []
        for line in proc.stdout.splitlines():
            try:
                events.append(json.loads(line))
            except json.JSONDecodeError:
                continue
        result = _codex_result(events, proc.returncode, proc.stderr)
    else:
        try:
            result = json.loads(proc.stdout)
        except json.JSONDecodeError:
            result = None
    if not isinstance(result, dict):
        stderr_tail = (proc.stderr or "").strip()[-2000:]
        return _finish(
            AgentResult(
                error=f"malformed CLI result (exit {proc.returncode}): {stderr_tail[:500]}",
                error_category="protocol",
            ),
            raw_result={"stdout": proc.stdout[-2000:], "stderr": stderr_tail},
        )

    try:
        cost_usd = float(result.get("total_cost_usd") or 0.0)
    except (TypeError, ValueError):
        cost_usd = 0.0
    denials = result.get("permission_denials")
    agent_result = AgentResult(
        cost_usd=cost_usd,
        permission_denials=denials if isinstance(denials, list) else [],
        session_id=str(result.get("session_id") or "")
        or (resume_session_id or session_id or ""),
    )

    if proc.returncode != 0 or result.get("is_error"):
        if _is_budget_stop(result):
            # Distinct from "agent": the work was cut short by our own cap,
            # not by anything wrong with the agent. `result` is empty on this
            # path, so the message has to come from `errors`.
            errors = result.get("errors")
            detail = "; ".join(str(e) for e in errors) if isinstance(errors, list) else ""
            agent_result.error = f"budget exhausted: {detail or 'max budget reached'}"
            agent_result.error_category = "budget"
        else:
            agent_result.error = f"agent error (exit {proc.returncode}): " + str(
                result.get("result", "")
            )[:500]
            agent_result.error_category = "agent"
        return _finish(agent_result, raw_result=result)

    if schema is not None:
        output = result.get("structured_output")
        if not isinstance(output, dict):
            agent_result.error = "missing structured_output in result"
            agent_result.error_category = "protocol"
            return _finish(agent_result, raw_result=result)
        agent_result.output = output
    else:
        agent_result.output = {"text": result.get("result", "")}

    return _finish(agent_result, raw_result=result)
