#!/usr/bin/env python3
# Generated By: Claude Code (Claude Fable 5)
"""CLI entry point for the review orchestrator.

Usage (typically via the review skill wrapper, but works standalone):

    python orchestrator/cli.py [--pr N] [--guidance "text"]
        [--scoring categorical|simple] [--project-root PATH]
        [--max-agents 16] [--parallel 4] [--timeout 600] [--dry-run]

Long runs from an agent wrapper use the detach/wait pair — the run survives
the wrapper's process lifetime, and waiting is a short idempotent command
the wrapper repeats until it stops returning exit code 3:

    python orchestrator/cli.py --detach [run args]   # start, return at once
    python orchestrator/cli.py --wait                # exit 0/1 done, 3 running
"""

import argparse
import hashlib
import os
import subprocess
import sys
import tempfile
import time
import traceback
from pathlib import Path

PLUGIN_ROOT = Path(__file__).resolve().parent.parent
if str(PLUGIN_ROOT) not in sys.path:
    sys.path.insert(0, str(PLUGIN_ROOT))

from orchestrator import pipeline  # noqa: E402

EXIT_STILL_RUNNING = 3
_EXIT_FILE_ENV = "REVIEW_ORCHESTRATOR_EXIT_FILE"
_LOG_TAIL_LINES = 40
_POLL_INTERVAL_S = 5


def _run_files(project_root: str) -> dict[str, Path]:
    """Per-project runtime files, outside the repo and outside .tmp-review
    (which the run itself wipes). Kept in an owner-only directory so the
    predictable names in the shared temp dir are not attackable."""
    run_dir = Path(tempfile.gettempdir()) / f"review-orchestrator-{os.getuid()}"
    run_dir.mkdir(mode=0o700, exist_ok=True)
    key = hashlib.sha256(str(Path(project_root).resolve()).encode()).hexdigest()[:12]
    base = run_dir / key
    return {
        "log": base.with_suffix(".log"),
        "exit": base.with_suffix(".exit"),
        "pid": base.with_suffix(".pid"),
        "selection": base.with_suffix(".selection.json"),
    }


def _pid_alive(pid_file: Path) -> int | None:
    """Return the recorded child pid if it is still running, else None."""
    try:
        pid = int(pid_file.read_text().strip())
        os.kill(pid, 0)
        return pid
    except (OSError, ValueError):
        return None


def _claim_run(files: dict[str, Path]) -> bool:
    """Atomically claim the run slot via O_EXCL on the pid file.

    Returns False when another live run holds it. A stale claim (dead pid
    or completed run) is cleared and re-claimed once.
    """
    for _ in range(2):
        try:
            fd = os.open(str(files["pid"]), os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
            os.close(fd)
            return True
        except FileExistsError:
            if _pid_alive(files["pid"]) is not None and not files["exit"].is_file():
                return False
            files["pid"].unlink(missing_ok=True)
    return False


def _detach(args, passthrough: list[str]) -> int:
    files = _run_files(args.project_root)
    if not _claim_run(files):
        print(
            "error: a review for this project is already running; "
            "poll it with --wait or kill it first",
            file=sys.stderr,
        )
        return 2
    files["log"].unlink(missing_ok=True)
    files["exit"].unlink(missing_ok=True)
    log_fh = files["log"].open("w", encoding="utf-8")
    env = dict(os.environ)
    env[_EXIT_FILE_ENV] = str(files["exit"])
    proc = subprocess.Popen(
        [sys.executable, str(Path(__file__).resolve()), *passthrough],
        stdout=log_fh,
        stderr=subprocess.STDOUT,
        stdin=subprocess.DEVNULL,
        start_new_session=True,
        env=env,
        cwd=args.project_root,
    )
    log_fh.close()
    files["pid"].write_text(str(proc.pid), encoding="utf-8")
    print(f"review started (pid {proc.pid}); poll with: --wait")
    return 0


def _wait(args) -> int:
    files = _run_files(args.project_root)
    deadline = time.monotonic() + args.wait_timeout_s
    while time.monotonic() < deadline:
        if files["exit"].is_file():
            code = int(files["exit"].read_text().strip() or "1")
            log = files["log"].read_text(encoding="utf-8") if files["log"].is_file() else ""
            # The summary is the tail of the run log.
            tail = "\n".join(log.splitlines()[-_LOG_TAIL_LINES:])
            print(tail)
            print(f"\nreview finished with exit code {code}")
            return code
        if not files["log"].is_file():
            print("no review is running for this project (nothing was started)")
            return 2
        if _pid_alive(files["pid"]) is None:
            # Process died without writing its exit file (killed, OOM, ...).
            log = files["log"].read_text(encoding="utf-8")
            print("\n".join(log.splitlines()[-_LOG_TAIL_LINES:]))
            print("\nreview process died without completing (killed or crashed)")
            return 1
        remaining = deadline - time.monotonic()
        if remaining > 0:
            time.sleep(min(_POLL_INTERVAL_S, remaining))
    print(f"still running after {args.wait_timeout_s}s — run --wait again")
    return EXIT_STILL_RUNNING


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="review-orchestrator", description=__doc__
    )
    parser.add_argument("--pr", type=int, default=None, help="PR number to scope to")
    parser.add_argument("--guidance", default="", help="free-form review guidance")
    parser.add_argument(
        "--scoring",
        choices=["categorical", "simple"],
        default="categorical",
        help="categorical: five-dimension rubric with justifications "
        "(more output tokens per finding, stronger noise filtering); "
        "simple: severity+confidence (cheaper, lighter)",
    )
    parser.add_argument(
        "--project-root", default=os.getcwd(), help="project to review"
    )
    def _positive_int(value: str) -> int:
        parsed = int(value)
        if parsed < 1:
            raise argparse.ArgumentTypeError("must be >= 1")
        return parsed

    defaults = pipeline.Options(project_root=".")
    parser.add_argument("--max-agents", type=_positive_int, default=defaults.max_agents)
    parser.add_argument("--parallel", type=_positive_int, default=defaults.parallel)
    parser.add_argument(
        "--timeout", type=_positive_int, default=defaults.timeout_s,
        help="per-agent timeout in seconds",
    )
    parser.add_argument(
        "--skip-lenses",
        default="",
        help="comma-separated lens slugs to exclude before selection "
        "(an explicit skip beats the implementation lens's always-run)",
    )
    modes = parser.add_mutually_exclusive_group()
    modes.add_argument(
        "--dry-run",
        action="store_true",
        help="compute scope and print the selector prompt without dispatching agents",
    )
    modes.add_argument(
        "--select-only",
        action="store_true",
        help="run scope + lens selector only, print matched lenses "
        "(lens: <slug>: <rationale> lines), and save the selection for the "
        "next run against the same HEAD to reuse",
    )
    modes.add_argument(
        "--detach",
        action="store_true",
        help="start the run as a detached process and return immediately",
    )
    modes.add_argument(
        "--wait",
        action="store_true",
        help="poll a detached run; exit 0/1 when done, "
        f"{EXIT_STILL_RUNNING} while still running",
    )
    parser.add_argument(
        "--wait-timeout-s",
        type=_positive_int,
        default=100,
        help="how long one --wait call blocks before returning still-running",
    )
    args = parser.parse_args(argv)

    if args.wait:
        return _wait(args)
    if args.detach:
        passthrough = [a for a in (argv if argv is not None else sys.argv[1:]) if a != "--detach"]
        return _detach(args, passthrough)

    from orchestrator.lenses import LENSES

    skip_lenses = tuple(
        slug.strip() for slug in args.skip_lenses.split(",") if slug.strip()
    )
    known = {lens.slug for lens in LENSES}
    unknown = [slug for slug in skip_lenses if slug not in known]
    if unknown:
        print(
            f"error: unknown lens slug(s) in --skip-lenses: {', '.join(unknown)}; "
            f"known: {', '.join(sorted(known))}",
            file=sys.stderr,
        )
        return 2

    options = pipeline.Options(
        project_root=str(Path(args.project_root).resolve()),
        pr_number=args.pr,
        guidance=args.guidance,
        scoring=args.scoring,
        skip_lenses=skip_lenses,
        max_agents=args.max_agents,
        parallel=args.parallel,
        timeout_s=args.timeout,
        dry_run=args.dry_run,
    )
    files = _run_files(options.project_root)
    if args.select_only:
        return pipeline.run_select_only(options, files["selection"])
    exit_file = os.environ.get(_EXIT_FILE_ENV)
    claimed = False
    if exit_file is None and not args.dry_run:
        # Foreground runs share .tmp-review with detached ones — same slot.
        if not _claim_run(files):
            print(
                "error: a review for this project is already running; "
                "poll it with --wait or kill it first",
                file=sys.stderr,
            )
            return 2
        files["pid"].write_text(str(os.getpid()), encoding="utf-8")
        claimed = True
    try:
        code = pipeline.run_review(options, selection_file=files["selection"])
    except pipeline.PipelineError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        code = 1
    except KeyboardInterrupt:
        print("ERROR: interrupted", file=sys.stderr)
        code = 130
    except Exception as exc:  # noqa: BLE001 — CLI boundary: format, record, exit
        traceback.print_exc()
        print(f"ERROR: unexpected failure: {exc}", file=sys.stderr)
        code = 1
    finally:
        if claimed:
            files["pid"].unlink(missing_ok=True)
    if exit_file:
        # Atomic: readers must never observe a torn/empty exit file.
        tmp = Path(exit_file).with_suffix(".exit.tmp")
        tmp.write_text(str(code), encoding="utf-8")
        os.replace(tmp, exit_file)
    return code


if __name__ == "__main__":
    sys.exit(main())
