# Generated By: Claude Code (Claude Fable 5)
"""Lens roster and selection for the review orchestrator.

The eight lenses map 1:1 to the `concern`/`concern_slug` enum values in
skills/review/schemas/agent-output.schema.json, so lens selection is a
subset choice — no schema change. A cheap selector agent picks applicable
lenses per scope (pattern borrowed from cblecker/claude-plugins
pr-review-toolkit); on selector failure every lens runs so a broken
selector can never silently narrow the review.
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class Lens:
    concern: str  # exact agent-output schema enum value
    slug: str  # exact concern_slug enum value
    model: str
    scope_text: str  # what this lens reviews (goes into the agent prompt)
    runs_when: str  # selector guidance


LENSES: tuple[Lens, ...] = (
    Lens(
        "Implementation Quality",
        "implementation",
        "sonnet",
        "Logic correctness, error handling, type safety, resource management, "
        "edge cases, concurrency. Security excluded — dedicated lens.",
        "Always — general code correctness runs on every review.",
    ),
    Lens(
        "Architecture and Design",
        "architecture",
        "sonnet",
        "Project structure, module boundaries, coupling, data model, "
        "configuration management, design pattern consistency.",
        "Change touches module structure, interfaces between components, "
        "configuration, or introduces new files/packages.",
    ),
    Lens(
        "Test Quality and Coverage",
        "test",
        "sonnet",
        "Test plan alignment, isolation, assertion quality, edge case "
        "coverage, mock usage, missing scenarios, fixture design.",
        "Functional code changed that should have corresponding tests, or "
        "test files themselves changed.",
    ),
    Lens(
        "Maintainability and Standards",
        "maintainability",
        "sonnet",
        "Naming, duplication, import organization, function complexity, "
        "internal consistency, build system. Documentation excluded — "
        "dedicated lens.",
        "Change is more than a trivial fix, or touches build files, or adds "
        "duplicated/complex logic.",
    ),
    Lens(
        "Security",
        "security",
        "sonnet",
        "Authn/authz, input validation, injection vectors, credential/secret "
        "handling, path traversal, deserialization, supply chain (deps), "
        "TLS/crypto, auth-related error leakage. Auth chain rule: before "
        "reporting filter-level or data-level access control issues (IDOR, "
        "horizontal privilege escalation), verify the full auth chain — "
        "endpoint-level guards may already prevent the attack.",
        "Change touches auth, crypto, secrets, input parsing, subprocess/"
        "network/file I/O at trust boundaries, or dependencies.",
    ),
    Lens(
        "Backwards Compatibility",
        "compatibility",
        "sonnet",
        "Contract changes toward existing consumers. A breaking change is any "
        "change that forces an existing consumer of a supported surface to act "
        "in order to keep working as it did before. 'Consumer' is broad: an "
        "API client, a CLI script, a dashboard reading your metrics, a "
        "deployment being upgraded, code importing your exported symbols.\n"
        "CLASSIFY THE DELIVERABLE FIRST from repo evidence (Dockerfile, k8s/"
        "helm manifests, queue clients, migration dirs). Batch tool or "
        "library: interface breaks only. Single-instance long-running service: "
        "plus persisted-state and migration safety in both directions. "
        "Deployed/HA service: plus mixed-version coexistence, in-flight work "
        "across upgrades, and rollback. Mark inapplicable facets N/A; never "
        "report a runtime-upgrade finding against a batch tool or library.\n"
        "SURFACES, all equally in scope: HTTP API (paths, query/path params, "
        "request and response schemas, status codes, auth); CLI (command and "
        "flag names, machine-readable output); data schema and migration "
        "sequencing; declarative resources (CRDs, config-as-code); "
        "configuration (env vars, config keys, defaults); operational surfaces "
        "(metric names and labels, log fields, trace attributes) — a metric "
        "rename breaks a dashboard exactly as a response-field rename breaks a "
        "client; behavioral semantics (ordering, runtime defaults) with no "
        "interface change at all; UI routes and deep links — a page URL is an "
        "interface even when nothing programmatic calls it; third-party "
        "integrations (callback URLs, app registrations).\n"
        "DIRECTIONALITY RULE: narrowing what you accept is breaking (making an "
        "optional input required, rejecting a previously accepted value, "
        "tightening validation). Widening what you produce is breaking (a "
        "field becoming nullable, a return type gaining shapes consumers never "
        "coded for). Widening what you accept, and narrowing what you produce, "
        "are safe.\n"
        "ASSUME WELL-BEHAVED CONSUMERS — they ignore unknown response fields "
        "and tolerate unrecognized enum values. Adding an optional field or a "
        "new enum value is therefore NOT breaking, unless the repo shows a "
        "specific consumer that rejects unrecognized data.\n"
        "NOT BREAKING, do not report: a new endpoint, command, field, enum "
        "value, or optional parameter; correcting behavior nobody could have "
        "relied on correctly; changing human-readable text where the error "
        "code or exit status is unchanged; different data inside a field "
        "already documented as an open-ended map.\n"
        "OUT OF SCOPE, do not report: features marked experimental, alpha, or "
        "explicitly unstable; environments or configurations the project never "
        "claimed to support; interfaces nothing outside the owning code "
        "depends on. An 'internal' interface stops being internal the moment "
        "an outside consumer depends on it — look for real callers instead of "
        "trusting the label. Internal interfaces stay in scope for "
        "mixed-version coexistence on an HA service, where the cross-version "
        "caller is the service's own other release. A change sitting on one of "
        "these boundaries is worth reporting; say which exclusion is in "
        "question.\n"
        "A MISSING SIGNAL IS ITS OWN FINDING: on a versioned or reasonably "
        "versionable surface (API, CLI, CRD), a breaking change shipped with "
        "no major version bump, deprecation notice, or migration note is a "
        "defect separate from the break — report both. Unversioned surfaces "
        "(UI, logs, metrics) carry no version number; there the missing signal "
        "is the missing release-note entry.\n"
        "SIZE THE REMEDY IN suggested_fix — it differs by surface. API, CLI "
        "and declarative specs are heaviest: a new version alongside the old, "
        "a deprecation window, a migration guide. Data schema: a "
        "backward-compatible migration, forward-compatible too where rollback "
        "is supported. Operational surfaces: a release-note entry and "
        "coordination with whoever consumes the metric or log, not a "
        "parallel-support window. Upgrade behavior can be purely procedural — "
        "a documented upgrade step. Do not prescribe a deprecation cycle for a "
        "log-field rename.",
        "Change touches public interfaces (API/CLI/exported symbols), URL or "
        "UI route paths, schemas or wire/file formats, DB migrations, config "
        "keys or defaults, metric/log/trace names, deployment manifests, or "
        "runtime behavior an existing consumer could depend on.",
    ),
    Lens(
        "Documentation",
        "documentation",
        "haiku",
        "README accuracy and completeness, docstrings, inline comments where "
        "non-obvious, examples, ADRs, changelog, public API docs, "
        "install/usage instructions.",
        "Change touches docs files, public API surfaces, or user-facing "
        "behavior described in the README.",
    ),
    Lens(
        "Observability",
        "observability",
        "haiku",
        "Log quality (levels, structured fields, sensitive data), error "
        "context, metrics, traces, debug affordances, alerting hooks.",
        "Change touches logging, error handling paths, metrics, or "
        "long-running/operational code.",
    ),
)

_BY_SLUG = {lens.slug: lens for lens in LENSES}
ALWAYS_RUN_SLUG = "implementation"


def resolve_selection(
    selector_output: dict | None, roster: tuple[Lens, ...] = LENSES
) -> tuple[list[Lens], str, dict]:
    """Map selector agent output to lenses within `roster`.

    Returns (lenses, source, rationales). source is "selector" or
    "all-lenses-fallback". Unknown or out-of-roster lens names are dropped;
    empty/invalid selection falls back to the whole roster; the always-run
    lens is force-included only when the roster still contains it (a user
    skip beats always-run).
    """
    roster_by_slug = {lens.slug: lens for lens in roster}
    selected: list[Lens] = []
    rationales: dict[str, str] = {}
    entries = (selector_output or {}).get("lenses") or []
    for entry in entries:
        lens = roster_by_slug.get((entry or {}).get("name", ""))
        if lens is None or lens in selected:
            continue
        selected.append(lens)
        rationales[lens.slug] = entry.get("rationale", "")

    if not selected:
        return list(roster), "all-lenses-fallback", {}

    always = roster_by_slug.get(ALWAYS_RUN_SLUG)
    if always is not None and always not in selected:
        selected.insert(0, always)
        rationales[ALWAYS_RUN_SLUG] = "General correctness always runs."
    return selected, "selector", rationales


def resolve_dimensions(
    selector_output: dict | None, lens_count: int, max_agents: int
) -> list[dict]:
    """Dimensions from selector output, capped so lenses × dims <= max_agents.

    Default is one full-scope dimension. The selector may propose up to 3;
    excess dimensions are dropped (first kept) rather than dropping lenses.
    """
    default = [{"name": "full scope", "slug": "full-scope", "scope": {}}]
    proposed = (selector_output or {}).get("dimensions") or []
    dims: list[dict] = []
    seen_slugs: set[str] = set()
    for d in proposed[:3]:
        # scope keys are free-form ({"paths": [...]}, {"theme": ...}); the
        # optional shared_infrastructure flag alters agent prompts.
        if not (isinstance(d, dict) and d.get("name") and d.get("slug")):
            continue
        if d["slug"] in seen_slugs:
            # Duplicate slugs would race on the same output filename.
            continue
        seen_slugs.add(d["slug"])
        dims.append({"name": d["name"], "slug": d["slug"], "scope": d.get("scope", {})})
    dims = dims or default
    max_dims = max(1, max_agents // max(1, lens_count))
    return dims[:max_dims]
