# Generated By: Claude Code (Claude Fable 5)
"""Review pipeline: deterministic stage sequencing for the review skill.

Models are invoked only
for reasoning (selector, lens agents, validators) through the
backend seam; every other stage is the existing tested stage CLI run via
subprocess, or plain Python.
"""

import json
import os
import subprocess
import sys
import time
import uuid
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass, field, fields
from pathlib import Path

ORCHESTRATOR_ROOT = Path(__file__).resolve().parent
PLUGIN_ROOT = ORCHESTRATOR_ROOT.parent
if str(PLUGIN_ROOT) not in sys.path:
    sys.path.insert(0, str(PLUGIN_ROOT))

import jsonschema  # noqa: E402

from orchestrator import backend, lenses, prompts, scope as scope_mod  # noqa: E402
from scripts.envelope import assign_bucket, load_stage_dir, review_file_basename  # noqa: E402

REVIEW_SCRIPTS = PLUGIN_ROOT / "skills" / "review" / "scripts"
TMP_DIR_NAME = ".tmp-review"
TRACE_FILENAME = "agent-trace.jsonl"
LOG_DIRNAME = "agent-logs"

# Per-agent spend cap — the actual runaway control (Options.timeout_s is only
# a latency backstop). Keyed by model because the floors differ by an order of
# magnitude: measured haiku lenses run $0.25-$0.40 and sonnet lenses
# $2.07-$3.53, so one flat cap is either no cap for haiku or too tight for
# sonnet. The CLI enforces this between turns, so real spend overshoots by up
# to one turn's cost.
BUDGET_USD_BY_MODEL = {"sonnet": 6.0, "haiku": 2.0}
DEFAULT_BUDGET_USD = 6.0

# Second pass over a budget-stopped agent: reopen its session and ask only for
# what it already worked out. Cheap because it does no new investigation, and
# it salvages a run that otherwise cost full price for nothing.
HARVEST_BUDGET_USD = 0.5
HARVEST_PROMPT = (
    "STOP investigating. Your previous run was cut short when it hit its "
    "spend cap, and its work is otherwise lost.\n\n"
    "Do NOT read any more files, run any more searches, or start any new "
    "analysis. Using ONLY what you already established in this session, emit "
    "your structured output now.\n\n"
    "Include every finding you had already confirmed. Omit anything you were "
    "still in the middle of verifying — a partial set of solid findings is "
    "the goal, not a padded one. If you had not confirmed any findings yet, "
    "return an empty findings list rather than inventing any."
)


# ok       — ran, nothing lost
# degraded — ran, but part of its work did not land (some agents failed, a
#            fallback was taken); the run continues with less than it should
# skipped  — deliberately not run for this scope/mode
# failed   — aborted the run
STEP_STATUSES = ("ok", "degraded", "skipped", "failed")

# Issue kinds that record a deliberate pipeline decision, not a failure —
# kept apart in every summary so a clean run does not report warnings.
DECISION_KINDS = frozenset({"finding_removed", "finding_truncated"})

RUN_REPORT_FILENAME = "run-report.json"


def budget_for(model: str) -> float:
    """Spend cap for one agent invocation on this model."""
    return BUDGET_USD_BY_MODEL.get(model, DEFAULT_BUDGET_USD)


@dataclass(frozen=True)
class ToolConfig:
    """Per-role tool boundary: `tools` is which built-in tools exist at all
    (lens agents have no Bash, period); `allowed` is the permission
    allowlist within that set."""

    tools: str
    allowed: tuple[str, ...]


SELECTOR_TOOLS = ToolConfig(
    tools="Read,Glob,Grep,Bash",
    allowed=("Read", "Glob", "Grep", "Bash(git diff:*)", "Bash(git log:*)", "Bash(git ls-files:*)"),
)
LENS_TOOLS = ToolConfig(tools="Read,Glob,Grep", allowed=("Read", "Glob", "Grep"))
VALIDATOR_TOOLS = ToolConfig(
    tools="Read,Glob,Grep,Bash",
    allowed=(
        "Read",
        "Glob",
        "Grep",
        "Bash(git diff:*)",
        "Bash(git log:*)",
        "Bash(git show:*)",
        "Bash(git blame:*)",
    ),
)
@dataclass
class Options:
    """CLI arguments and pipeline configuration for one review run."""

    project_root: str
    pr_number: int | None = None
    guidance: str = ""
    scoring: str = "categorical"  # or "simple"
    harness: str = "claude"
    skip_lenses: tuple = ()  # lens slugs excluded before selection
    max_agents: int = 16
    parallel: int = 4
    # Latency backstop only. Spend is capped per agent by BUDGET_USD_BY_MODEL,
    # which stops a runaway without SIGKILL and so keeps its cost reportable.
    timeout_s: int = 3600
    dry_run: bool = False


@dataclass
class CostEntry:
    """One agent attempt in the run ledger."""

    stage: str
    label: str
    model: str
    cost_usd: float
    token_usage: dict = field(default_factory=dict)
    normalized_tokens: float = 0.0
    elapsed_s: float = 0.0
    retries: int = 0
    error: str | None = None
    error_category: str | None = None
    session_id: str = ""  # child session id — joins the ledger to telemetry
    denials: list = field(default_factory=list)  # denied tool inputs, if any


@dataclass
class RunState:
    """Mutable per-run state: cost ledger and operational issues."""

    options: Options
    scope: scope_mod.ReviewScope
    run_id: str = field(default_factory=lambda: uuid.uuid4().hex[:12])
    # The Claude Code session that launched this run. The orchestrator makes no
    # model calls of its own, so this session's spend — reading the skill,
    # choosing arguments, polling --wait, relaying results — is real review cost
    # that no ledger entry here can capture: it belongs to a process this one
    # cannot see and never ends when the run does. Recording the id is what
    # makes it joinable. Empty when the CLI is run from a plain shell.
    orchestrating_session_id: str = field(
        default_factory=lambda: os.environ.get("CLAUDE_CODE_SESSION_ID", "")
    )
    saved_selection: dict | None = None  # selector output from --select-only
    costs: list[CostEntry] = field(default_factory=list)
    issues: list[dict] = field(default_factory=list)
    issues_merged: int = 0  # how many of `issues` already reached an envelope
    # Ordered outcome of every pipeline step. Separate from `issues` on
    # purpose: issues say what went wrong, steps say what ran at all. A
    # stage that degrades quietly — a validator batch that never dispatched,
    # a selector that fell back — shows up here as a row, so reading the run
    # never means reconstructing it from logs.
    steps: list[dict] = field(default_factory=list)

    def record_step(self, name: str, status: str, detail: str = "") -> None:
        """Append one step outcome. `status` is ok|degraded|skipped|failed."""
        if status not in STEP_STATUSES:
            raise ValueError(f"unknown step status {status!r}")
        self.steps.append({"step": name, "status": status, "detail": detail})

    def run_report(self) -> dict:
        """The machine-readable run report embedded in the findings envelope."""
        statuses = {step["status"] for step in self.steps}
        if "failed" in statuses:
            overall = "failed"
        elif "degraded" in statuses:
            overall = "degraded"
        else:
            overall = "ok"
        return {
            "run_id": self.run_id,
            "harness": self.options.harness,
            "scoring": self.options.scoring,
            "status": overall,
            "steps": list(self.steps),
        }

    def agent_attributes(self, stage: str, label: str) -> dict:
        """OTEL resource attributes stamping a child with run correlation."""
        attributes = {
            "review.run_id": self.run_id,
            "review.stage": stage,
            "review.agent": label,
            "review.scoring": self.options.scoring,
        }
        if self.orchestrating_session_id:
            attributes["review.orchestrating_session_id"] = (
                self.orchestrating_session_id
            )
        return attributes

    @property
    def log_dir(self) -> Path:
        """Per-agent CLI debug logs, written while the agents are still running.

        The trace file is only appended after an agent returns, so during a
        long run there is nothing to look at. These exist purely to answer
        "what is it doing right now" on request — nothing reads them
        programmatically, and no decision is made from them. A quiet log is
        ambiguous (a stalled agent and one inside a long tool call look the
        same), which is exactly why acting on it automatically is a trap.
        """
        return self.tmp_dir / LOG_DIRNAME

    @property
    def tmp_dir(self) -> Path:
        return Path(self.options.project_root) / TMP_DIR_NAME


class PipelineError(Exception):
    """Fatal pipeline failure — abort with this message."""


def _attempt_error(attempt_result, schema) -> str | None:
    """Why this attempt failed, or None if it succeeded.

    An attempt fails when the backend reported an error, or when the output
    does not validate locally against the source schema.
    """
    if attempt_result.error is not None:
        return attempt_result.error
    if schema is not None:
        try:
            jsonschema.validate(attempt_result.output, schema)
        except jsonschema.ValidationError as exc:
            return f"output failed local schema validation: {exc.message[:200]}"
    return None


def _run_with_retry(state, stage, label, model, fn, schema=None, retries=2, harvest=None):
    """Call fn() -> AgentResult up to 1 + retries times.

    Cost of every attempt is recorded — the ledger reports real spend.
    Returns the first successful AgentResult, or the last attempt with
    `error` set when all attempts failed.

    A budget stop is never retried. Hitting the cap is evidence the agent
    was running away, and an identical retry runs away again at full price;
    the old behaviour spent three full budgets to learn nothing. Instead,
    when `harvest` is supplied, its session is reopened once to collect
    whatever it had already established.
    """
    last_attempt = None
    for attempt_number in range(retries + 1):
        started = time.monotonic()
        attempt = fn()
        failure_reason = _attempt_error(attempt, schema)
        category = attempt.error_category
        if failure_reason is not None and category is None:
            category = "schema"
        state.costs.append(
            CostEntry(
                stage=stage,
                label=label,
                model=model,
                cost_usd=attempt.cost_usd,
                token_usage=attempt.token_usage,
                normalized_tokens=backend.normalize_token_usage(attempt.token_usage),
                elapsed_s=round(time.monotonic() - started, 3),
                retries=attempt_number,
                error=failure_reason,
                error_category=category,
                session_id=attempt.session_id,
                denials=list(attempt.permission_denials),
            )
        )
        if failure_reason is None:
            return attempt
        attempt.error = failure_reason
        attempt.output = None
        last_attempt = attempt
        if category == "budget":
            if harvest is None or not attempt.session_id:
                break
            harvested = _harvest(state, stage, label, model, harvest, attempt, schema)
            return harvested if harvested is not None else attempt
    return last_attempt


def _harvest(state, stage, label, model, harvest, stopped, schema):
    """Reopen a budget-stopped session and take whatever it already had.

    Returns the salvaged AgentResult, or None when nothing usable came back
    (the caller then reports the original budget stop). Its cost is recorded
    like any other attempt — this is real spend, not free.
    """
    started = time.monotonic()
    attempt = harvest(stopped.session_id)
    failure_reason = _attempt_error(attempt, schema)
    state.costs.append(
        CostEntry(
            stage=stage,
            label=f"{label} (harvest)",
            model=model,
            cost_usd=attempt.cost_usd,
            token_usage=attempt.token_usage,
            normalized_tokens=backend.normalize_token_usage(attempt.token_usage),
            elapsed_s=round(time.monotonic() - started, 3),
            retries=0,
            error=failure_reason,
            error_category=attempt.error_category or ("schema" if failure_reason else None),
            session_id=attempt.session_id or stopped.session_id,
            denials=list(attempt.permission_denials),
        )
    )
    if failure_reason is not None:
        return None
    state.issues.append(
        {
            "severity": "warning",
            "kind": "subagent_failure",
            "message": (
                f"{label}: stopped at its spend cap; findings below were "
                f"harvested from the partial run and may be incomplete"
            ),
            "source_component": label,
        }
    )
    return attempt


def _record_fan_out_step(
    state,
    step: str,
    plural_noun: str,
    total: int,
    failed: list[str],
    *,
    empty_is_fatal: bool = False,
) -> None:
    """One run-report row for a whole agent stage.

    A stage where some agents died still produces output, so nothing else
    marks it as incomplete — that is exactly the silence this row removes.

    "failed" is reserved for a stage that ends the run: losing every
    validator batch is a degradation (apply-verdicts.py passes those
    findings through and the run finishes), while losing every lens agent
    leaves nothing to consolidate and aborts — hence `empty_is_fatal`.
    """
    if total == 0:
        state.record_step(step, "skipped", f"no {plural_noun} to run")
        return
    if not failed:
        state.record_step(step, "ok", f"{total}/{total} {plural_noun} succeeded")
        return
    status = "failed" if (empty_is_fatal and len(failed) == total) else "degraded"
    state.record_step(
        step,
        status,
        f"{total - len(failed)}/{total} {plural_noun} succeeded; failed: "
        + ", ".join(sorted(failed)),
    )


def _record_agent_failure(state, component: str, result) -> None:
    """Record a final agent failure (and any denials) as envelope issues."""
    state.issues.append(
        {
            "severity": "warning",
            "kind": "subagent_failure",
            "message": f"{component}: {result.error}",
            "source_component": component,
        }
    )
    for denial in result.permission_denials:
        state.issues.append(
            {
                "severity": "warning",
                "kind": "permission_denied",
                "message": f"{component}: denied {json.dumps(denial)[:200]}",
                "source_component": component,
            }
        )


def stage_cli(
    script_name: str,
    *args: str,
    cwd: str,
    state=None,
    step: str | None = None,
    detail: str = "",
) -> None:
    """Run one of the tested stage CLIs; raise PipelineError on failure.

    Public: the simple-mode path reuses this and run_validators. When
    `state` is given the outcome is recorded as a run-report step — the
    failing one is named there as well as in the raised error, so an
    aborted run still says which stage ended it.
    """
    argv = [sys.executable, str(REVIEW_SCRIPTS / script_name), *args]
    proc = subprocess.run(argv, cwd=cwd, capture_output=True, text=True)
    if proc.stdout.strip():
        print(proc.stdout.strip(), file=sys.stderr)
    name = step or script_name
    if proc.returncode != 0:
        if state is not None:
            state.record_step(
                name,
                "failed",
                f"exit {proc.returncode}: {proc.stderr.strip()[:300]}",
            )
        raise PipelineError(
            f"{script_name} failed (exit {proc.returncode}):\n{proc.stderr.strip()}"
        )
    if state is not None:
        state.record_step(name, "ok", detail)


def maybe_diff_scope_filter(state, cwd: str) -> None:
    """Run the diff-scope filter on 10-merged for PR-scoped reviews only."""
    if not state.scope.merge_base:
        state.record_step("diff-scope-filter", "skipped", "no merge base (full-repo review)")
        return
    stage_cli(
        "diff-scope-filter.py",
        "--stage-dir",
        f"./{TMP_DIR_NAME}/10-merged/",
        "--base-ref",
        state.scope.merge_base,
        cwd=cwd,
        state=state,
        step="diff-scope-filter",
        detail=f"filtered against {state.scope.merge_base}",
    )


def _bootstrap(state) -> None:
    """Wipe and recreate the .tmp-review stage directories."""
    proc = subprocess.run(
        [
            "bash",
            str(PLUGIN_ROOT / "scripts" / "bootstrap-tmp.sh"),
            TMP_DIR_NAME,
            "00-raw",
            "10-merged",
            "15-validation",
            "20-findings",
            LOG_DIRNAME,
        ],
        cwd=state.options.project_root,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        raise PipelineError(f"bootstrap-tmp.sh failed: {proc.stderr.strip()}")


def _active_roster(state) -> tuple:
    """The lens roster minus user-skipped slugs."""
    return tuple(
        lens for lens in lenses.LENSES if lens.slug not in state.options.skip_lenses
    )


def _run_selector(state) -> dict | None:
    """Run the lens-selector agent; None on failure (callers fall back)."""
    schema = backend.load_resolved_schema("selector-output")
    prompt = prompts.build_selector_prompt(state.scope, _active_roster(state))
    result = _run_with_retry(
        state,
        "select",
        "lens-selector",
        "haiku",
        lambda: backend.run_agent(
            prompt,
            schema=schema,
            model="haiku",
            allowed_tools=list(SELECTOR_TOOLS.allowed),
            tools=SELECTOR_TOOLS.tools,
            cwd=state.options.project_root,
            effort="low",
            timeout_s=state.options.timeout_s,
            max_budget_usd=budget_for("haiku"),
            session_id=str(uuid.uuid4()),
            debug_file=state.log_dir / "lens-selector.log",
            trace_file=state.tmp_dir / TRACE_FILENAME,
            label="lens-selector",
            redact=state.scope.guidance or None,
            otel_attributes=state.agent_attributes("select", "lens-selector"),
            harness=state.options.harness,
        ),
        schema=schema,
    )
    if result.error is not None:
        _record_agent_failure(state, "lens-selector", result)
        return None
    return result.output


def _fan_out(state, items, run_one, on_success) -> list[str]:
    """Run agent jobs concurrently; failures become issues, successes call back.

    Returns the labels that failed, so the caller can record one run-report
    step for the whole stage instead of leaving the loss visible only as
    individual issues.
    """
    failed: list[str] = []
    with ThreadPoolExecutor(max_workers=state.options.parallel) as pool:
        futures = {pool.submit(run_one, item): item for item in items}
        for future, item in futures.items():
            result = future.result()
            label = item["label"]
            if result.error is not None:
                _record_agent_failure(state, label, result)
                failed.append(label)
                continue
            on_success(item, result)
    return failed


def _dispatch_review_agents(state, selected, dimensions) -> None:
    """One lens agent per lens x dimension, in parallel.

    Successful lens outputs land in 00-raw/<concern_slug>-<dimension_slug>.json.
    """
    schema_name = (
        "agent-output" if state.options.scoring == "categorical" else "agent-output-simple"
    )
    schema = backend.load_resolved_schema(schema_name)
    raw_dir = state.tmp_dir / "00-raw"

    def run_lens(lens, dimension):
        prompt = prompts.build_lens_prompt(
            lens, dimension, state.scope, scoring=state.options.scoring
        )
        label = f"{lens.slug}/{dimension['slug']}"
        log_stem = label.replace("/", "-")
        # Chosen up front, not read back, so a SIGKILLed attempt is still
        # identifiable and a budget-stopped one is still reopenable.
        lens_session_id = str(uuid.uuid4())
        return _run_with_retry(
            state,
            "review",
            label,
            lens.model,
            lambda: backend.run_agent(
                prompt,
                schema=schema,
                model=lens.model,
                allowed_tools=list(LENS_TOOLS.allowed),
                tools=LENS_TOOLS.tools,
                cwd=state.options.project_root,
                timeout_s=state.options.timeout_s,
                max_budget_usd=budget_for(lens.model),
                session_id=lens_session_id,
                persist_session=True,
                debug_file=state.log_dir / f"{log_stem}.log",
                trace_file=state.tmp_dir / TRACE_FILENAME,
                label=label,
                redact=state.scope.guidance or None,
                otel_attributes=state.agent_attributes("review", label),
                harness=state.options.harness,
            ),
            schema=schema,
            harvest=lambda sid: backend.run_agent(
                HARVEST_PROMPT,
                schema=schema,
                model=lens.model,
                allowed_tools=[],
                tools="",
                cwd=state.options.project_root,
                timeout_s=state.options.timeout_s,
                max_budget_usd=HARVEST_BUDGET_USD,
                resume_session_id=sid,
                persist_session=True,
                debug_file=state.log_dir / f"{log_stem}-harvest.log",
                trace_file=state.tmp_dir / TRACE_FILENAME,
                label=f"{label} (harvest)",
                redact=state.scope.guidance or None,
                otel_attributes=state.agent_attributes("review", f"{label}-harvest"),
                harness=state.options.harness,
            ),
        )

    jobs = [
        {"lens": lens, "dim": dim, "label": f"{lens.slug}/{dim['slug']}"}
        for dim in dimensions
        for lens in selected
    ]
    failed = _fan_out(
        state,
        jobs,
        lambda job: run_lens(job["lens"], job["dim"]),
        lambda job, result: (raw_dir / f"{job['label'].replace('/', '-')}.json").write_text(
            json.dumps(result.output, indent=2), encoding="utf-8"
        ),
    )
    _record_fan_out_step(
        state, "review", "lens agents", len(jobs), failed, empty_is_fatal=True
    )


def _revalidate_raw(state) -> None:
    """Defense-in-depth re-check of raw files; invalid files are removed."""
    excluded: list[str] = []
    raw_dir = state.tmp_dir / "00-raw"
    schema_arg = (
        "agent-output"
        if state.options.scoring == "categorical"
        else "agent-output-simple"
    )
    for path in sorted(raw_dir.glob("*.json")):
        proc = subprocess.run(
            [
                sys.executable,
                str(REVIEW_SCRIPTS / "validate-findings.py"),
                str(path),
                "--schema",
                schema_arg,
            ],
            capture_output=True,
            text=True,
        )
        if proc.returncode != 0:
            path.unlink()
            excluded.append(path.name)
            detail = (proc.stderr or "").strip().splitlines()
            state.issues.append(
                {
                    "severity": "warning",
                    "kind": "validation_failed",
                    "message": (
                        f"raw output {path.name} failed re-validation and was excluded"
                        + (f": {detail[0][:200]}" if detail else "")
                    ),
                    "source_component": "revalidate",
                }
            )
    if excluded:
        state.record_step(
            "revalidate",
            "degraded",
            f"{len(excluded)} raw agent output(s) excluded: " + ", ".join(excluded),
        )
    else:
        state.record_step("revalidate", "ok", "all raw agent outputs valid")


def _merge_issues_into_envelope(state, stage_dir: Path) -> None:
    """Append not-yet-merged orchestrator issues to a stage envelope.

    Called once after consolidation (agent/selector failures) and again
    after verdict application (validator failures) — tracked via
    state.issues_merged so nothing is duplicated or dropped.
    """
    pending = state.issues[state.issues_merged :]
    if not pending:
        return
    envelope_path = stage_dir / "_envelope.json"
    envelope = json.loads(envelope_path.read_text(encoding="utf-8"))
    envelope.setdefault("issues", []).extend(pending)
    envelope_path.write_text(json.dumps(envelope, indent=2), encoding="utf-8")
    state.issues_merged = len(state.issues)


def run_validators(state) -> None:
    """Dispatch one validator agent per batch input file."""
    validation_dir = state.tmp_dir / "15-validation"
    batch_files = sorted(validation_dir.glob("batch-*-input.json"))
    if not batch_files:
        state.record_step(
            "validate", "skipped", "no findings were batched for validation"
        )
        return
    simple = state.options.scoring == "simple"
    schema = backend.load_resolved_schema(
        "validation-output-simple" if simple else "validation-output"
    )

    def run_batch(batch):
        prompt = prompts.build_validator_prompt(
            batch, state.options.project_root, state.scope.merge_base, simple=simple
        )
        return _run_with_retry(
            state,
            "validate",
            f"batch-{batch['batch_number']}",
            "sonnet",
            lambda: backend.run_agent(
                prompt,
                schema=schema,
                model="sonnet",
                allowed_tools=list(VALIDATOR_TOOLS.allowed),
                tools=VALIDATOR_TOOLS.tools,
                cwd=state.options.project_root,
                timeout_s=state.options.timeout_s,
                max_budget_usd=budget_for("sonnet"),
                session_id=str(uuid.uuid4()),
                debug_file=state.log_dir
                / f"validator-batch-{batch['batch_number']}.log",
                trace_file=state.tmp_dir / TRACE_FILENAME,
                label=f"validator-batch-{batch['batch_number']}",
                redact=state.scope.guidance or None,
                otel_attributes=state.agent_attributes(
                    "validate", f"validator-batch-{batch['batch_number']}"
                ),
                harness=state.options.harness,
            ),
            schema=schema,
        )

    # Findings whose validator fails pass through unchanged
    # (apply-verdicts.py behavior) — _fan_out records the failure issue.
    jobs = [
        {"batch": json.loads(path.read_text(encoding="utf-8"))}
        for path in batch_files
    ]
    for job in jobs:
        job["label"] = f"validator-batch-{job['batch']['batch_number']}"
    failed = _fan_out(
        state,
        jobs,
        lambda job: run_batch(job["batch"]),
        lambda job, result: (
            validation_dir / f"batch-{job['batch']['batch_number']}-output.json"
        ).write_text(json.dumps(result.output, indent=2), encoding="utf-8"),
    )
    _record_fan_out_step(state, "validate", "validator batches", len(jobs), failed)
    if failed:
        unvalidated = sum(
            len(job["batch"].get("findings", []))
            for job in jobs
            if job["label"] in failed
        )
        # The consequence, not just the cause: apply-verdicts.py passes a
        # batch with no verdict file straight through, so those findings
        # ship with nothing having challenged them.
        state.issues.append(
            {
                "severity": "warning",
                "kind": "subagent_failure",
                "message": (
                    f"{unvalidated} finding(s) in {len(failed)} batch(es) were "
                    "never adversarially validated and pass through unchanged"
                ),
                "source_component": "validate",
            }
        )


def _write_run_report(state) -> Path:
    """Persist the run report and return its path.

    Written before rendering so the renderer can embed it in the findings
    envelope, where it outlives `.tmp-review/` (wiped by the next run).
    The render step itself is deliberately not a row: a rendered file is
    its own evidence that rendering worked, and a render failure aborts
    with the stage CLI's error rather than quietly degrading.
    """
    path = state.tmp_dir / RUN_REPORT_FILENAME
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(state.run_report(), indent=2), encoding="utf-8")
    return path


def _print_run_report(state) -> None:
    """Print the step table. The skill relays this output verbatim, so a
    degraded run says so here rather than only inside the JSON."""
    report = state.run_report()
    print(f"\nRun report ({report['status']}):")
    width = max([len(step["step"]) for step in report["steps"]] + [4])
    for step in report["steps"]:
        detail = f"  {step['detail']}" if step["detail"] else ""
        print(f"  {step['step']:<{width}} {step['status']:<9}{detail}")


def _write_costs(state) -> dict:
    """Persist the run ledger to .tmp-review/costs.json."""
    report = {
        "run_id": state.run_id,
        "harness": state.options.harness,
        # The session that drove this run. Its own spend is not in `entries` and
        # cannot be: the orchestrator issues no model calls, and the session
        # outlives the run. Recorded so the run joins back to it in telemetry.
        "orchestrating_session_id": state.orchestrating_session_id or None,
        "scoring": state.options.scoring,
        "total_cost_usd": round(sum(c.cost_usd for c in state.costs), 6),
        "token_normalization": backend.TOKEN_WEIGHTS,
        "total_normalized_tokens": round(
            sum(c.normalized_tokens for c in state.costs), 3
        ),
        # Also in the findings envelope. Duplicated here on purpose: a run
        # that dies before render never writes an envelope, and the ledger
        # is written on every exit path including the fatal ones.
        "steps": list(state.steps),
        "by_stage": {},
        "normalized_tokens_by_stage": {},
        "seconds_by_stage": {},
        "denials_by_tool": {},
        "entries": [
            {
                "stage": c.stage,
                "label": c.label,
                "model": c.model,
                "cost_usd": c.cost_usd,
                "token_usage": c.token_usage,
                "normalized_tokens": c.normalized_tokens,
                "elapsed_s": c.elapsed_s,
                "retries": c.retries,
                "error": c.error,
                "error_category": c.error_category,
                "session_id": c.session_id,
                "denials": c.denials,
            }
            for c in state.costs
        ],
    }
    for entry in state.costs:
        # Keyed by stage/model, not stage: a stage spans models (review runs
        # per-lens models), so a stage-only rollup hides where the spend went.
        key = f"{entry.stage}/{entry.model}"
        report["by_stage"][key] = round(
            report["by_stage"].get(key, 0.0) + entry.cost_usd, 6
        )
        report["seconds_by_stage"][key] = round(
            report["seconds_by_stage"].get(key, 0.0) + entry.elapsed_s, 1
        )
        report["normalized_tokens_by_stage"][key] = round(
            report["normalized_tokens_by_stage"].get(key, 0.0)
            + entry.normalized_tokens,
            3,
        )
        for denial in entry.denials:
            tool = denial.get("tool_name", "unknown")
            report["denials_by_tool"][tool] = report["denials_by_tool"].get(tool, 0) + 1
    (state.tmp_dir / "costs.json").write_text(
        json.dumps(report, indent=2), encoding="utf-8"
    )
    return report


DEFAULT_VALIDATION_BUCKETS = "critical,important"


def _validation_buckets(merged_dir: Path) -> str:
    """Which severity buckets go to the validators.

    Bucketing happens before validation, so a finding scored too low never
    reaches the only stage that challenges its dimensions. When a run puts
    nothing in critical or important, validate the suggestions instead of
    running no validators at all — the spend was budgeted for this run
    either way, and an all-suggestion result is the shape systematic
    under-scoring produces.
    """
    try:
        _envelope, findings = load_stage_dir(merged_dir)
    except (OSError, ValueError, json.JSONDecodeError):
        return DEFAULT_VALIDATION_BUCKETS
    if not findings:
        return DEFAULT_VALIDATION_BUCKETS
    if any(assign_bucket(f) in ("critical", "important") for f in findings):
        return DEFAULT_VALIDATION_BUCKETS
    return "suggestion"


def _print_summary(state, cost_report) -> None:
    """Print the terse end-of-run summary: counts, files, cost, tokens."""
    base = review_file_basename(state.scope.scope_slug)
    findings_path = Path(state.options.project_root) / f"{base}.json"
    try:
        envelope = json.loads(findings_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise PipelineError(
            f"rendered findings unreadable at {findings_path}: {exc}"
        ) from exc
    counts = {"critical": 0, "important": 0, "suggestion": 0, "needs-review": 0}
    for finding in envelope.get("findings", []):
        counts[finding["severity"]] = counts.get(finding["severity"], 0) + 1

    print(
        f"{counts['critical']} critical, {counts['important']} important, "
        f"{counts['suggestion']} suggestion, {counts['needs-review']} needs-review."
    )
    if counts["critical"] == 0 and counts["important"] == 0 and envelope.get("findings"):
        print(
            "No high-severity findings — the main report is empty and every "
            "finding is in the supplementary file. This is also what "
            "systematic under-scoring looks like; the suggestion bucket was "
            "sent to the validators for that reason."
        )
    print("\nFiles:")
    for suffix in (".json", ".md", "-supplementary.md"):
        print(f"- {base}{suffix}")

    _print_run_report(state)

    print(f"\nRun ID: {state.run_id} (telemetry label review_run_id)")
    if state.orchestrating_session_id:
        print(
            f"Orchestrating session: {state.orchestrating_session_id} "
            "(its spend is NOT in the table below)"
        )
    print(f"\nCost (backend-reported, scoring={cost_report['scoring']}):")
    width = max([len(k) for k in cost_report["by_stage"]] + [len("total")])
    for stage_model, cost in cost_report["by_stage"].items():
        seconds = cost_report["seconds_by_stage"].get(stage_model, 0.0)
        print(f"  {stage_model:<{width}} ${cost:.4f}  ({seconds:.0f}s agent time)")
    print(f"  {'total':<{width}} ${cost_report['total_cost_usd']:.4f}")
    print("\nTokens (normalized: input=1x, cache read=0.1x, cache write=1.25x, output=6x):")
    for stage_model, tokens in cost_report["normalized_tokens_by_stage"].items():
        print(f"  {stage_model:<{width}} {tokens:.3f}")
    print(f"  {'total':<{width}} {cost_report['total_normalized_tokens']:.3f}")
    if cost_report["denials_by_tool"]:
        denial_text = ", ".join(
            f"{tool} ({count})"
            for tool, count in sorted(cost_report["denials_by_tool"].items())
        )
        print(f"\nTool denials: {denial_text}")
    decisions = [i for i in state.issues if i["kind"] in DECISION_KINDS]
    failures = [i for i in state.issues if i["kind"] not in DECISION_KINDS]
    for heading, group in (("Operational issues", failures),
                           ("Pipeline decisions", decisions)):
        if not group:
            continue
        print(f"\n{heading} ({len(group)}):")
        for issue in group:
            component = issue.get("source_component", "")
            where = f" [{component}]" if component else ""
            print(f"  - {issue['severity']}/{issue['kind']}{where}: {issue['message']}")


def _head_sha(project_root: str) -> str:
    try:
        return scope_mod._git(project_root, "rev-parse", "HEAD")
    except (subprocess.CalledProcessError, OSError):
        return ""


def run_select_only(options: Options, selection_file: Path) -> int:
    """Phase 1 for interactive lens choice: scope + selector, no review.

    Prints the matched lenses (slug: rationale, one per line, machine
    readable) and saves the full selector output — keyed to HEAD and with
    its cost entries — for the subsequent run to consume without re-paying
    the selector.
    """
    try:
        review_scope = scope_mod.compute_scope(
            options.project_root, options.pr_number, options.guidance
        )
    except scope_mod.ScopeError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    state = RunState(options=options, scope=review_scope)
    selector_output = _run_selector(state)
    roster = _active_roster(state)
    selected, source, rationales = lenses.resolve_selection(selector_output, roster)

    selection_file.write_text(
        json.dumps(
            {
                "head": _head_sha(options.project_root),
                "run_id": state.run_id,
                "selector_output": selector_output,
                "costs": [
                    {
                        "stage": c.stage,
                        "label": c.label,
                        "model": c.model,
                        "cost_usd": c.cost_usd,
                        "token_usage": c.token_usage,
                        "normalized_tokens": c.normalized_tokens,
                        "elapsed_s": c.elapsed_s,
                        "retries": c.retries,
                        "error": c.error,
                        "error_category": c.error_category,
                        "session_id": c.session_id,
                        "denials": c.denials,
                    }
                    for c in state.costs
                ],
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    print(f"selection source: {source}")
    for lens in selected:
        print(f"lens: {lens.slug}: {rationales.get(lens.slug, '')}")
    return 0


def _load_saved_selection(state, selection_file: Path | None):
    """Selector output saved by --select-only, if present and HEAD matches.

    Consumed (deleted) on read either way; its cost entries are replayed
    into this run's ledger so the selector's spend is never lost.
    """
    if selection_file is None or not selection_file.is_file():
        return None
    try:
        saved = json.loads(selection_file.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        selection_file.unlink(missing_ok=True)
        return None
    selection_file.unlink(missing_ok=True)
    if saved.get("head") != _head_sha(state.options.project_root):
        print("saved lens selection is stale (HEAD moved); re-running selector", file=sys.stderr)
        return None
    saved_run_id = saved.get("run_id")
    if isinstance(saved_run_id, str) and saved_run_id:
        # One logical review, one run_id: the review run continues the
        # select-only phase's identity so telemetry is not split.
        state.run_id = saved_run_id
    known_fields = {f.name for f in fields(CostEntry)}
    costs = saved.get("costs")
    for entry in costs if isinstance(costs, list) else []:
        if isinstance(entry, dict):
            state.costs.append(
                CostEntry(**{k: v for k, v in entry.items() if k in known_fields})
            )
    output = saved.get("selector_output")
    return output if isinstance(output, dict) else None


def run_review(options: Options, selection_file: Path | None = None) -> int:
    """Run the full review pipeline; returns a process exit code."""
    try:
        review_scope = scope_mod.compute_scope(
            options.project_root, options.pr_number, options.guidance
        )
    except scope_mod.ScopeError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    state = RunState(options=options, scope=review_scope)
    state.record_step(
        "scope",
        "ok",
        f"{review_scope.project_name} ({review_scope.language}); "
        + (
            f"PR #{options.pr_number}, merge base {review_scope.merge_base}"
            if review_scope.merge_base
            else "full repo"
        ),
    )

    if options.dry_run:
        print(f"Project: {review_scope.project_name} ({review_scope.language})")
        print(f"Scope slug: {review_scope.scope_slug or '(full repo)'}")
        print(f"Merge base: {review_scope.merge_base or '(none)'}")
        print("\n--- selector prompt ---\n")
        print(prompts.build_selector_prompt(review_scope, _active_roster(state)))
        return 0

    _bootstrap(state)

    state.saved_selection = _load_saved_selection(state, selection_file)
    try:
        return _run_stages(state)
    except BaseException:
        # Real spend happened; persist the ledger and the step record before
        # propagating, whatever the failure (PipelineError, bug,
        # KeyboardInterrupt). No findings file gets written on this path, so
        # .tmp-review/ is the only place the report can land.
        _write_run_report(state)
        _write_costs(state)
        _print_run_report(state)
        raise


def _run_stages(state: RunState) -> int:
    options = state.options
    review_scope = state.scope

    roster = _active_roster(state)
    if not roster:
        print("ERROR: every lens was skipped; nothing to review.", file=sys.stderr)
        return 2
    if state.options.skip_lenses:
        print(
            f"Skipping lenses (user): {', '.join(state.options.skip_lenses)}",
            file=sys.stderr,
        )
    selector_output = state.saved_selection
    reused_selection = selector_output is not None
    if selector_output is None:
        selector_output = _run_selector(state)
    else:
        print("using saved lens selection from --select-only", file=sys.stderr)
    selected, source, rationales = lenses.resolve_selection(selector_output, roster)
    if reused_selection:
        state.record_step("select", "ok", "reused the --select-only selection")
    elif source == "selector":
        state.record_step(
            "select", "ok", f"selector matched {len(selected)} lens(es)"
        )
    else:
        # The fallback is a full-roster review, which is more expensive and
        # less targeted — not a neutral outcome, so not an "ok" row.
        state.record_step(
            "select",
            "degraded",
            f"selector produced no usable selection; fell back to all "
            f"{len(selected)} lens(es)",
        )
    if len(selected) > options.max_agents:
        dropped = [lens.slug for lens in selected[options.max_agents :]]
        selected = selected[: options.max_agents]
        print(
            f"max-agents={options.max_agents}: dropped lenses {', '.join(dropped)}",
            file=sys.stderr,
        )
    dimensions = lenses.resolve_dimensions(
        selector_output, len(selected), options.max_agents
    )
    print(
        f"Lenses ({source}): {', '.join(lens.slug for lens in selected)}; "
        f"{len(dimensions)} dimension(s)",
        file=sys.stderr,
    )
    for lens in selected:
        rationale = rationales.get(lens.slug)
        if rationale:
            print(f"  {lens.slug}: {rationale}", file=sys.stderr)

    _dispatch_review_agents(state, selected, dimensions)
    _revalidate_raw(state)

    if not any((state.tmp_dir / "00-raw").glob("*.json")):
        print("ERROR: no lens agent produced valid output.", file=sys.stderr)
        for issue in state.issues:
            print(f"ERROR: {issue['message']}", file=sys.stderr)
        _write_run_report(state)
        _write_costs(state)
        _print_run_report(state)
        return 1

    cwd = options.project_root
    if options.scoring == "categorical":
        consolidate_args = [
            "--raw-dir",
            f"./{TMP_DIR_NAME}/00-raw/",
            "--output-dir",
            f"./{TMP_DIR_NAME}/10-merged/",
            "--project-name",
            review_scope.project_name,
            "--cross-concern-threshold",
            "0.4",
        ]
        if review_scope.scope_slug:
            consolidate_args += ["--scope-slug", review_scope.scope_slug]
        stage_cli(
            "consolidate-findings.py",
            *consolidate_args,
            cwd=cwd,
            state=state,
            step="consolidate",
        )
        _merge_issues_into_envelope(state, state.tmp_dir / "10-merged")

        maybe_diff_scope_filter(state, cwd)

        buckets = _validation_buckets(state.tmp_dir / "10-merged")
        stage_cli(
            "batch-findings.py",
            "--input-dir",
            f"./{TMP_DIR_NAME}/10-merged/",
            "--output-dir",
            f"./{TMP_DIR_NAME}/15-validation/",
            "--only-buckets",
            buckets,
            cwd=cwd,
            state=state,
            step="batch",
            detail=f"buckets sent to validation: {buckets}",
        )
        run_validators(state)
        stage_cli(
            "apply-verdicts.py",
            "--input-dir",
            f"./{TMP_DIR_NAME}/10-merged/",
            "--verdicts-dir",
            f"./{TMP_DIR_NAME}/15-validation/",
            "--output-dir",
            f"./{TMP_DIR_NAME}/20-findings/",
            cwd=cwd,
            state=state,
            step="apply-verdicts",
        )
        # Validator failures were recorded after the 10-merged merge;
        # fold them into the post-verdict envelope.
        _merge_issues_into_envelope(state, state.tmp_dir / "20-findings")
        render_args = [
            "--input-dir",
            f"./{TMP_DIR_NAME}/20-findings/",
            "--out-dir",
            ".",
            "--project-name",
            review_scope.project_name,
            "--run-id",
            state.run_id,
            "--run-report",
            str(_write_run_report(state)),
        ]
        if state.orchestrating_session_id:
            render_args += [
                "--orchestrating-session-id",
                state.orchestrating_session_id,
            ]
        if review_scope.scope_slug:
            render_args += ["--scope-slug", review_scope.scope_slug]
        stage_cli("render-review.py", *render_args, cwd=cwd)
    else:
        from orchestrator import simple_mode

        simple_mode.run_simple_path(state)

    cost_report = _write_costs(state)
    _print_summary(state, cost_report)
    return 0
