# Generated By: Claude Code (Claude Fable 5)
"""Review pipeline: deterministic stage sequencing for the review skill.

Models are invoked only
for reasoning (selector, lens agents, validators) through the
backend seam; every other stage is the existing tested stage CLI run via
subprocess, or plain Python.
"""

import json
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass, field
from pathlib import Path

ORCHESTRATOR_ROOT = Path(__file__).resolve().parent
PLUGIN_ROOT = ORCHESTRATOR_ROOT.parent
if str(PLUGIN_ROOT) not in sys.path:
    sys.path.insert(0, str(PLUGIN_ROOT))

import jsonschema  # noqa: E402

from orchestrator import backend, lenses, prompts, scope as scope_mod  # noqa: E402

REVIEW_SCRIPTS = PLUGIN_ROOT / "skills" / "review" / "scripts"
TMP_DIR_NAME = ".tmp-review"
TRACE_FILENAME = "agent-trace.jsonl"

# Per-role tool boundaries: `tools` is which built-in tools exist at all
# (lens agents have no Bash, period); `allowed` is the permission allowlist
# within that set.
SELECTOR_TOOLS = {
    "tools": "Read,Glob,Grep,Bash",
    "allowed": ["Read", "Glob", "Grep", "Bash(git diff:*)", "Bash(git log:*)", "Bash(git ls-files:*)"],
}
LENS_TOOLS = {"tools": "Read,Glob,Grep", "allowed": ["Read", "Glob", "Grep"]}
VALIDATOR_TOOLS = {
    "tools": "Read,Glob,Grep,Bash",
    "allowed": [
        "Read",
        "Glob",
        "Grep",
        "Bash(git diff:*)",
        "Bash(git log:*)",
        "Bash(git show:*)",
        "Bash(git blame:*)",
    ],
}
@dataclass
class Options:
    project_root: str
    pr_number: int | None = None
    guidance: str = ""
    scoring: str = "categorical"  # or "simple"
    max_agents: int = 16
    parallel: int = 4
    timeout_s: int = 600
    dry_run: bool = False


@dataclass
class CostEntry:
    stage: str
    label: str
    model: str
    cost_usd: float
    retries: int = 0
    error: str | None = None
    denials: list = field(default_factory=list)  # denied tool inputs, if any


@dataclass
class RunState:
    options: Options
    scope: scope_mod.ReviewScope
    costs: list[CostEntry] = field(default_factory=list)
    issues: list[dict] = field(default_factory=list)

    @property
    def tmp_dir(self) -> Path:
        return Path(self.options.project_root) / TMP_DIR_NAME


class PipelineError(Exception):
    """Fatal pipeline failure — abort with this message."""


def _attempt_error(attempt_result, schema) -> str | None:
    """Why this attempt failed, or None if it succeeded.

    An attempt fails when the backend reported an error, or when the output
    does not validate locally against the source schema.
    """
    if attempt_result.error is not None:
        return attempt_result.error
    if schema is not None:
        try:
            jsonschema.validate(attempt_result.output, schema)
        except jsonschema.ValidationError as exc:
            return f"output failed local schema validation: {exc.message[:200]}"
    return None


def _run_with_retry(state, stage, label, model, fn, schema=None, retries=2):
    """Call fn() -> AgentResult up to 1 + retries times.

    Cost of every attempt is recorded — the ledger reports real spend.
    Returns the first successful AgentResult, or the last attempt with
    `error` set when all attempts failed.
    """
    last_attempt = None
    for attempt_number in range(retries + 1):
        attempt = fn()
        failure_reason = _attempt_error(attempt, schema)
        state.costs.append(
            CostEntry(
                stage=stage,
                label=label,
                model=model,
                cost_usd=attempt.cost_usd,
                retries=attempt_number,
                error=failure_reason,
                denials=list(attempt.permission_denials),
            )
        )
        if failure_reason is None:
            return attempt
        attempt.error = failure_reason
        attempt.output = None
        last_attempt = attempt
    return last_attempt


def _record_agent_failure(state, component: str, result) -> None:
    state.issues.append(
        {
            "severity": "warning",
            "kind": "subagent_failure",
            "message": f"{component}: {result.error}",
            "source_component": component,
        }
    )
    for denial in result.permission_denials:
        state.issues.append(
            {
                "severity": "warning",
                "kind": "permission_denied",
                "message": f"{component}: denied {json.dumps(denial)[:200]}",
                "source_component": component,
            }
        )


def _stage_cli(script_name: str, *args: str, cwd: str) -> None:
    """Run one of the tested stage CLIs; raise PipelineError on failure."""
    argv = [sys.executable, str(REVIEW_SCRIPTS / script_name), *args]
    proc = subprocess.run(argv, cwd=cwd, capture_output=True, text=True)
    if proc.returncode != 0:
        raise PipelineError(
            f"{script_name} failed (exit {proc.returncode}):\n{proc.stderr.strip()}"
        )


def _bootstrap(state) -> None:
    proc = subprocess.run(
        [
            "bash",
            str(PLUGIN_ROOT / "scripts" / "bootstrap-tmp.sh"),
            TMP_DIR_NAME,
            "00-raw",
            "10-merged",
            "15-validation",
            "20-findings",
        ],
        cwd=state.options.project_root,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        raise PipelineError(f"bootstrap-tmp.sh failed: {proc.stderr.strip()}")


def _run_selector(state) -> dict | None:
    schema = backend.load_resolved_schema("selector-output")
    prompt = prompts.build_selector_prompt(state.scope, lenses.LENSES)
    result = _run_with_retry(
        state,
        "select",
        "lens-selector",
        "haiku",
        lambda: backend.run_agent(
            prompt,
            schema=schema,
            model="haiku",
            allowed_tools=SELECTOR_TOOLS["allowed"],
            tools=SELECTOR_TOOLS["tools"],
            cwd=state.options.project_root,
            effort="low",
            timeout_s=state.options.timeout_s,
            trace_file=state.tmp_dir / TRACE_FILENAME,
            label="lens-selector",
        ),
    )
    if result.error is not None:
        _record_agent_failure(state, "lens-selector", result)
        return None
    return result.output


def _dispatch_review_agents(state, selected, dimensions) -> None:
    """One lens agent per lens x dimension, in parallel.

    Successful lens outputs land in 00-raw/<concern_slug>-<dimension_slug>.json.
    """
    schema_name = (
        "agent-output" if state.options.scoring == "categorical" else "agent-output-simple"
    )
    schema = backend.load_resolved_schema(schema_name)
    raw_dir = state.tmp_dir / "00-raw"

    def run_lens(lens, dimension):
        prompt = prompts.build_lens_prompt(
            lens, dimension, state.scope, scoring=state.options.scoring
        )
        label = f"{lens.slug}/{dimension['slug']}"
        return _run_with_retry(
            state,
            "review",
            label,
            lens.model,
            lambda: backend.run_agent(
                prompt,
                schema=schema,
                model=lens.model,
                allowed_tools=LENS_TOOLS["allowed"],
                tools=LENS_TOOLS["tools"],
                cwd=state.options.project_root,
                timeout_s=state.options.timeout_s,
                trace_file=state.tmp_dir / TRACE_FILENAME,
                label=label,
            ),
            schema=schema,
        )

    jobs = [(lens, dim) for dim in dimensions for lens in selected]
    with ThreadPoolExecutor(max_workers=state.options.parallel) as pool:
        lens_futures = {
            pool.submit(run_lens, lens, dim): (lens, dim) for lens, dim in jobs
        }
        for future, (lens, dim) in lens_futures.items():
            result = future.result()
            label = f"{lens.slug}/{dim['slug']}"
            if result.error is not None:
                _record_agent_failure(state, label, result)
                continue
            out_path = raw_dir / f"{lens.slug}-{dim['slug']}.json"
            out_path.write_text(
                json.dumps(result.output, indent=2), encoding="utf-8"
            )


def _revalidate_raw(state) -> None:
    """Defense-in-depth re-check of raw files; invalid files are removed."""
    raw_dir = state.tmp_dir / "00-raw"
    schema_arg = (
        "agent-output"
        if state.options.scoring == "categorical"
        else "agent-output-simple"
    )
    for path in sorted(raw_dir.glob("*.json")):
        proc = subprocess.run(
            [
                sys.executable,
                str(REVIEW_SCRIPTS / "validate-findings.py"),
                str(path),
                "--schema",
                schema_arg,
            ],
            capture_output=True,
            text=True,
        )
        if proc.returncode != 0:
            path.unlink()
            state.issues.append(
                {
                    "severity": "warning",
                    "kind": "validation_failed",
                    "message": f"raw output {path.name} failed re-validation and was excluded",
                    "source_component": "revalidate",
                }
            )


def _merge_issues_into_envelope(state, stage_dir: Path) -> None:
    """Append orchestrator-collected issues to a stage envelope."""
    if not state.issues:
        return
    envelope_path = stage_dir / "_envelope.json"
    envelope = json.loads(envelope_path.read_text(encoding="utf-8"))
    envelope.setdefault("issues", []).extend(state.issues)
    envelope_path.write_text(json.dumps(envelope, indent=2), encoding="utf-8")


def _run_validators(state) -> None:
    """Dispatch one validator agent per batch input file."""
    validation_dir = state.tmp_dir / "15-validation"
    batch_files = sorted(validation_dir.glob("batch-*-input.json"))
    if not batch_files:
        return
    simple = state.options.scoring == "simple"
    schema = backend.load_resolved_schema(
        "validation-output-simple" if simple else "validation-output"
    )

    def run_batch(batch):
        prompt = prompts.build_validator_prompt(
            batch, state.options.project_root, state.scope.merge_base, simple=simple
        )
        return _run_with_retry(
            state,
            "validate",
            f"batch-{batch['batch_number']}",
            "sonnet",
            lambda: backend.run_agent(
                prompt,
                schema=schema,
                model="sonnet",
                allowed_tools=VALIDATOR_TOOLS["allowed"],
                tools=VALIDATOR_TOOLS["tools"],
                cwd=state.options.project_root,
                timeout_s=state.options.timeout_s,
                trace_file=state.tmp_dir / TRACE_FILENAME,
                label=f"validator-batch-{batch['batch_number']}",
            ),
            schema=schema,
        )

    batches = [json.loads(p.read_text(encoding="utf-8")) for p in batch_files]
    with ThreadPoolExecutor(max_workers=state.options.parallel) as pool:
        futures = {pool.submit(run_batch, b): b for b in batches}
        for future, batch in futures.items():
            result = future.result()
            number = batch["batch_number"]
            if result.error is not None:
                # Findings without a verdict pass through unchanged
                # (apply-verdicts.py behavior) — record and continue.
                _record_agent_failure(state, f"validator-batch-{number}", result)
                continue
            (validation_dir / f"batch-{number}-output.json").write_text(
                json.dumps(result.output, indent=2), encoding="utf-8"
            )


def _write_costs(state) -> dict:
    report = {
        "scoring": state.options.scoring,
        "total_cost_usd": round(sum(c.cost_usd for c in state.costs), 6),
        "by_stage": {},
        "entries": [
            {
                "stage": c.stage,
                "label": c.label,
                "model": c.model,
                "cost_usd": c.cost_usd,
                "retries": c.retries,
                "error": c.error,
                "denials": c.denials,
            }
            for c in state.costs
        ],
    }
    for entry in state.costs:
        report["by_stage"][entry.stage] = round(
            report["by_stage"].get(entry.stage, 0.0) + entry.cost_usd, 6
        )
    (state.tmp_dir / "costs.json").write_text(
        json.dumps(report, indent=2), encoding="utf-8"
    )
    return report


def _print_summary(state, cost_report) -> None:
    slug = f"-{state.scope.scope_slug}" if state.scope.scope_slug else ""
    findings_path = Path(state.options.project_root) / f"Findings-review{slug}.json"
    envelope = json.loads(findings_path.read_text(encoding="utf-8"))
    counts = {"critical": 0, "important": 0, "suggestion": 0, "needs-review": 0}
    for finding in envelope.get("findings", []):
        counts[finding["severity"]] = counts.get(finding["severity"], 0) + 1

    print(
        f"{counts['critical']} critical, {counts['important']} important, "
        f"{counts['suggestion']} suggestion, {counts['needs-review']} needs-review."
    )
    print("\nFiles:")
    for suffix in (".json", ".md", "-supplementary.md"):
        print(f"- Findings-review{slug}{suffix}")

    print(f"\nCost (measured, scoring={cost_report['scoring']}):")
    for stage, cost in cost_report["by_stage"].items():
        print(f"  {stage:<10} ${cost:.4f}")
    print(f"  {'total':<10} ${cost_report['total_cost_usd']:.4f}")
    if state.issues:
        print(f"\n{len(state.issues)} issue(s) recorded in the findings envelope.")


def run_review(options: Options) -> int:
    try:
        review_scope = scope_mod.compute_scope(
            options.project_root, options.pr_number, options.guidance
        )
    except scope_mod.ScopeError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    state = RunState(options=options, scope=review_scope)

    if options.dry_run:
        print(f"Project: {review_scope.project_name} ({review_scope.language})")
        print(f"Scope slug: {review_scope.scope_slug or '(full repo)'}")
        print(f"Merge base: {review_scope.merge_base or '(none)'}")
        print("\n--- selector prompt ---\n")
        print(prompts.build_selector_prompt(review_scope, lenses.LENSES))
        return 0

    _bootstrap(state)

    selector_output = _run_selector(state)
    selected, source, rationales = lenses.resolve_selection(selector_output)
    dimensions = lenses.resolve_dimensions(
        selector_output, len(selected), options.max_agents
    )
    print(
        f"Lenses ({source}): {', '.join(lens.slug for lens in selected)}; "
        f"{len(dimensions)} dimension(s)",
        file=sys.stderr,
    )
    for lens in selected:
        rationale = rationales.get(lens.slug)
        if rationale:
            print(f"  {lens.slug}: {rationale}", file=sys.stderr)

    _dispatch_review_agents(state, selected, dimensions)
    _revalidate_raw(state)

    if not any((state.tmp_dir / "00-raw").glob("*.json")):
        print("ERROR: no lens agent produced valid output.", file=sys.stderr)
        _write_costs(state)
        return 1

    cwd = options.project_root
    if options.scoring == "categorical":
        consolidate_args = [
            "--raw-dir",
            f"./{TMP_DIR_NAME}/00-raw/",
            "--output-dir",
            f"./{TMP_DIR_NAME}/10-merged/",
            "--project-name",
            review_scope.project_name,
            "--cross-concern-threshold",
            "0.4",
        ]
        if review_scope.scope_slug:
            consolidate_args += ["--scope-slug", review_scope.scope_slug]
        _stage_cli("consolidate-findings.py", *consolidate_args, cwd=cwd)
        _merge_issues_into_envelope(state, state.tmp_dir / "10-merged")

        if review_scope.merge_base:
            _stage_cli(
                "diff-scope-filter.py",
                "--stage-dir",
                f"./{TMP_DIR_NAME}/10-merged/",
                "--base-ref",
                review_scope.merge_base,
                cwd=cwd,
            )

        _stage_cli(
            "batch-findings.py",
            "--input-dir",
            f"./{TMP_DIR_NAME}/10-merged/",
            "--output-dir",
            f"./{TMP_DIR_NAME}/15-validation/",
            "--only-buckets",
            "critical,important",
            cwd=cwd,
        )
        _run_validators(state)
        _stage_cli(
            "apply-verdicts.py",
            "--input-dir",
            f"./{TMP_DIR_NAME}/10-merged/",
            "--verdicts-dir",
            f"./{TMP_DIR_NAME}/15-validation/",
            "--output-dir",
            f"./{TMP_DIR_NAME}/20-findings/",
            cwd=cwd,
        )
        render_args = [
            "--input-dir",
            f"./{TMP_DIR_NAME}/20-findings/",
            "--out-dir",
            ".",
            "--project-name",
            review_scope.project_name,
        ]
        if review_scope.scope_slug:
            render_args += ["--scope-slug", review_scope.scope_slug]
        _stage_cli("render-review.py", *render_args, cwd=cwd)
    else:
        from orchestrator import simple_mode

        simple_mode.run_simple_path(state)

    cost_report = _write_costs(state)
    _print_summary(state, cost_report)
    return 0
