# Generated By: Claude Code (Claude Fable 5)
"""Scope computation for the review orchestrator.

Deterministic git/project context: git guard, PR scope + merge base,
guidance handling, standards gathering, and a project probe
(name/language/build system/test framework).
"""

import json
import re
import subprocess
from collections import Counter
from dataclasses import dataclass
from pathlib import Path


class ScopeError(Exception):
    """Unrecoverable scope problem — abort the review with this message."""


@dataclass
class ReviewScope:
    """Everything deterministic the pipeline knows about one review target."""

    project_root: str
    project_name: str
    default_branch: str  # e.g. "origin/main"
    language: str
    build_system: str
    test_framework: str
    pr_number: int | None = None
    merge_base: str = ""  # empty for full-repo reviews
    pr_scope_text: str = ""  # "## PR Scope" block for agent prompts
    guidance: str = ""
    standards: str = ""  # external + local standards text
    scope_slug: str = ""  # e.g. "pr-42"; empty when unconstrained


def _git(project_root: str, *args: str) -> str:
    proc = subprocess.run(
        ["git", *args],
        cwd=project_root,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        raise subprocess.CalledProcessError(
            proc.returncode, proc.args, proc.stdout, proc.stderr
        )
    return proc.stdout.strip()


def check_git_context(project_root: str) -> str:
    """Return the default branch (e.g. origin/main) or raise ScopeError."""
    try:
        _git(project_root, "rev-parse", "--is-inside-work-tree")
    except (subprocess.CalledProcessError, OSError) as exc:
        raise ScopeError(
            "Not inside a git repository. Are you in the right directory?"
        ) from exc
    try:
        ref = _git(project_root, "symbolic-ref", "refs/remotes/origin/HEAD")
    except subprocess.CalledProcessError as exc:
        raise ScopeError(
            "Cannot determine default branch. Are you in the right directory?"
        ) from exc
    return ref.removeprefix("refs/remotes/")


def compute_pr_scope(
    project_root: str, pr_number: int, default_branch: str
) -> tuple[str, str]:
    """Return (PR scope text block, merge base hash).

    Warnings are non-fatal: the block carries the warning and merge base
    stays empty (the diff-scope filter then no-ops).
    """
    header = f"## PR Scope: #{pr_number}\n"
    try:
        base = _git(project_root, "merge-base", "HEAD", default_branch)
    except subprocess.CalledProcessError:
        return (
            header
            + f"\nWARNING: Could not determine merge base against {default_branch}.",
            "",
        )
    try:
        diff_stat = _git(project_root, "diff", "--stat", f"{base}..HEAD")
    except subprocess.CalledProcessError:
        return (
            header + "\nWARNING: Could not compute diff stats against the merge base.",
            "",
        )
    if not diff_stat:
        return (
            header
            + "\nWARNING: No changed files detected between merge base and HEAD.",
            "",
        )
    text = f"""{header}
Merge base: {base[:12]} (against {default_branch})

### Diff Stats

{diff_stat}

### Scope Rules

- Report findings ONLY for the changed files listed above.
- You may read other files for context (understanding imports, call sites, interfaces),
  but do not report findings against unchanged files.
- When a changed file interacts with unchanged code in a problematic way, report the
  finding against the changed file with a note about the interaction.
- The output filename slug is: pr-{pr_number}"""
    return text, base


def gather_standards(project_root: str) -> str:
    """External standards plus local CLAUDE.md/AGENTS.md.

    External standards inject only for user-owned repos (gh login == origin
    owner) when ~/source/standards exists; every failure degrades to "".
    """
    parts: list[str] = []

    external = _external_standards(project_root)
    if external:
        parts.append(external)

    for name in ("CLAUDE.md", "AGENTS.md"):
        path = Path(project_root) / name
        if path.is_file():
            parts.append(
                f"### Project standards ({name})\n\n{path.read_text(encoding='utf-8')}"
            )

    return "\n\n".join(parts)


def _remote_owner(url: str) -> str:
    """Top-level owner segment of a git remote URL.

    Handles https://host/owner[/sub]/repo and git@host:owner[/sub]/repo —
    the owner is the first path segment, not the second-to-last (which
    breaks on nested/subgroup paths).
    """
    path = url.rstrip("/")
    if "://" in path:
        path = path.split("://", 1)[1]
        path = path.split("/", 1)[1] if "/" in path else ""
    elif ":" in path:
        path = path.split(":", 1)[1]
    return path.split("/", 1)[0] if path else ""


def _external_standards(project_root: str) -> str:
    standards_dir = Path.home() / "source" / "standards"
    claude_md = standards_dir / "CLAUDE.md"
    if not claude_md.is_file():
        return ""
    try:
        gh_user = subprocess.run(
            ["gh", "api", "user", "--jq", ".login"],
            capture_output=True,
            text=True,
            timeout=30,
        )
        if gh_user.returncode != 0:
            return ""
        url = _git(project_root, "remote", "get-url", "origin")
    except (subprocess.CalledProcessError, OSError, subprocess.TimeoutExpired):
        return ""
    owner = _remote_owner(url)
    if gh_user.stdout.strip() != owner:
        return ""
    text = claude_md.read_text(encoding="utf-8")
    return re.sub(r"\]\(([^)]+)\)", r"](~/source/standards/\1)", text)


_LANGUAGE_EXTENSIONS = {
    ".py": "Python",
    ".go": "Go",
    ".js": "JavaScript",
    ".ts": "TypeScript",
    ".rs": "Rust",
    ".java": "Java",
    ".rb": "Ruby",
    ".sh": "Shell",
    ".c": "C",
    ".cpp": "C++",
}


def probe_project(project_root: str) -> tuple[str, str, str, str]:
    """Return (name, language, build_system, test_framework) deterministically."""
    root = Path(project_root)

    try:
        url = _git(project_root, "remote", "get-url", "origin")
        name = url.rstrip("/").rsplit("/", 1)[-1].removesuffix(".git")
    except (subprocess.CalledProcessError, OSError):
        name = root.resolve().name

    try:
        files = _git(project_root, "ls-files").splitlines()
    except (subprocess.CalledProcessError, OSError):
        files = [str(p.relative_to(root)) for p in root.rglob("*") if p.is_file()]
    counts = Counter(
        Path(f).suffix for f in files if Path(f).suffix in _LANGUAGE_EXTENSIONS
    )
    language = (
        _LANGUAGE_EXTENSIONS[counts.most_common(1)[0][0]] if counts else "unknown"
    )

    if (root / "Makefile").is_file():
        build_system = "make"
    elif (root / "package.json").is_file():
        build_system = "npm"
    elif (root / "pyproject.toml").is_file():
        build_system = "python/pyproject"
    else:
        build_system = "unknown"

    test_framework = "unknown"
    if (root / "pyproject.toml").is_file() or language == "Python":
        test_framework = "pytest"
    elif (root / "package.json").is_file():
        try:
            pkg = json.loads((root / "package.json").read_text(encoding="utf-8"))
            if "test" in pkg.get("scripts", {}):
                test_framework = "npm test"
        except (json.JSONDecodeError, OSError):
            pass
    elif language == "Go":
        test_framework = "go test"

    return name, language, build_system, test_framework


def compute_scope(
    project_root: str,
    pr_number: int | None,
    guidance: str,
) -> ReviewScope:
    """Build the full ReviewScope: git context, PR scope, standards, probe."""
    default_branch = check_git_context(project_root)
    name, language, build_system, test_framework = probe_project(project_root)

    scope = ReviewScope(
        project_root=project_root,
        project_name=name,
        default_branch=default_branch,
        language=language,
        build_system=build_system,
        test_framework=test_framework,
        pr_number=pr_number,
        guidance=guidance.strip(),
        standards=gather_standards(project_root),
    )
    if pr_number is not None:
        scope.pr_scope_text, scope.merge_base = compute_pr_scope(
            project_root, pr_number, default_branch
        )
        scope.scope_slug = f"pr-{pr_number}"
    elif scope.guidance:
        # Slug from guidance: max 12 chars, lowercase, hyphens (SKILL.md rule).
        slug = re.sub(r"[^a-z0-9]+", "-", scope.guidance.lower()).strip("-")[:12]
        scope.scope_slug = slug.strip("-")
    return scope
