# Generated By: Claude Code (Claude Fable 5)
"""Simple-scoring pipeline path.

Simple mode never enters consolidate-findings.py / batch-findings.py /
apply-verdicts.py — their ordinal aggregation IS the categorical rubric.
Instead: deterministic Python dedup, batch, and verdict application, with
diff-scope-filter.py and render-review.py (--scoring simple) reused as-is.
"""

import json
import sys
from pathlib import Path

ORCHESTRATOR_ROOT = Path(__file__).resolve().parent
PLUGIN_ROOT = ORCHESTRATOR_ROOT.parent
if str(PLUGIN_ROOT) not in sys.path:
    sys.path.insert(0, str(PLUGIN_ROOT))

from orchestrator import pipeline  # noqa: E402
from scripts.envelope import (  # noqa: E402
    content_hash,
    primary_location,
    load_stage_dir,
    write_stage_dir,
    _line_start,
)

SEVERITY_ORDER = {"critical": 0, "important": 1, "suggestion": 2}
CONFIDENCE_ORDER = {"high": 0, "medium": 1, "low": 2}
BATCH_SIZE = 8  # keep in sync with MAX_BATCH_SIZE in skills/review/scripts/batch-findings.py


def _dedup_key(finding: dict) -> tuple:
    """Identity for merging: (concern, primary path, primary start line)."""
    loc = primary_location(finding)
    return (
        finding["concern_slug"],
        loc["path"],
        _line_start(loc.get("line", "0")),
    )


def _merge(winner: dict, loser: dict) -> dict:
    """Union locations (dedup by path+line); winner's fields otherwise."""
    seen = {(loc["path"], loc.get("line")) for loc in winner["locations"]}
    for loc in loser["locations"]:
        if (loc["path"], loc.get("line")) not in seen:
            winner["locations"].append(loc)
            seen.add((loc["path"], loc.get("line")))
    return winner


def collect_findings(raw_dir: Path) -> tuple[list[dict], list[dict], list[dict]]:
    """Flatten agent outputs into hashed findings, a decomposition list, and
    deduplicated cross-cutting observations."""
    findings: dict[tuple, dict] = {}
    decomposition: dict[str, dict] = {}
    seen_observations: set[tuple[str, str]] = set()
    observations: list[dict] = []
    for path in sorted(raw_dir.glob("*.json")):
        output = json.loads(path.read_text(encoding="utf-8"))
        agent = f"{output['concern_slug']}/{output['dimension_slug']}"
        for text in output.get("cross_cutting_observations", []):
            if text and (agent, text) not in seen_observations:
                seen_observations.add((agent, text))
                observations.append({"agent": agent, "text": text})
        decomposition.setdefault(
            output["dimension_slug"],
            {
                "dimension_name": output["dimension_name"],
                "dimension_slug": output["dimension_slug"],
                "dimension_scope": output.get("dimension_scope", {}),
            },
        )
        for finding in output["findings"]:
            entry = dict(finding)
            entry["concern_slug"] = output["concern_slug"]
            loc = primary_location(entry)
            entry["content_hash"] = content_hash(
                output["concern_slug"],
                output["dimension_slug"],
                f"{loc['path']}:{loc.get('line', '')}",
                entry["title"],
            )
            key = _dedup_key(entry)
            existing = findings.get(key)
            if existing is None:
                findings[key] = entry
                continue
            # Keep the more severe entry; tie-break on confidence.
            existing_rank = (
                SEVERITY_ORDER.get(existing["severity"], 9),
                CONFIDENCE_ORDER.get(existing["confidence"], 9),
            )
            entry_rank = (
                SEVERITY_ORDER.get(entry["severity"], 9),
                CONFIDENCE_ORDER.get(entry["confidence"], 9),
            )
            winner, loser = (
                (entry, existing) if entry_rank < existing_rank else (existing, entry)
            )
            print(
                f"simple-mode dedup: merged '{loser['title']}' into "
                f"'{winner['title']}' at {key[1]}:{key[2]}",
                file=sys.stderr,
            )
            findings[key] = _merge(winner, loser)
    ordered = sorted(findings.values(), key=lambda f: f["content_hash"])
    return ordered, list(decomposition.values()), observations


def write_stage(stage_dir: Path, project: dict, decomposition, issues, findings, observations=None):
    """Write a stage dir (envelope + per-finding files) via the shared helper."""
    stage_dir.mkdir(parents=True, exist_ok=True)
    envelope = {
        "project": project,
        "decomposition": decomposition,
        "issues": list(issues),
    }
    if observations:
        envelope["cross_cutting_observations"] = list(observations)
    write_stage_dir(stage_dir, envelope, findings)


def load_stage(stage_dir: Path) -> tuple[dict, list[dict]]:
    """Read a stage dir back via the shared helper."""
    return load_stage_dir(stage_dir)


def write_batches(validation_dir: Path, findings: list[dict]) -> int:
    """Slice critical/important findings into validator batch input files.

    When nothing is critical or important, validate suggestions instead —
    same rationale as `pipeline._validation_buckets`: severity is assigned
    before validation, so an under-scored finding otherwise never reaches
    the stage that would challenge its rating.
    """
    wanted = ("critical", "important")
    if not any(f["severity"] in wanted for f in findings):
        wanted = ("suggestion",)
    to_validate = sorted(
        (f for f in findings if f["severity"] in wanted),
        key=lambda f: (SEVERITY_ORDER[f["severity"]], f["content_hash"]),
    )
    batches = [
        to_validate[i : i + BATCH_SIZE] for i in range(0, len(to_validate), BATCH_SIZE)
    ]
    for number, batch in enumerate(batches, start=1):
        payload = {
            "batch_number": number,
            "total_batches": len(batches),
            "findings": batch,
        }
        (validation_dir / f"batch-{number}-input.json").write_text(
            json.dumps(payload, indent=2), encoding="utf-8"
        )
    return len(batches)


def apply_verdicts(validation_dir: Path, findings: list[dict]) -> tuple[list[dict], list[dict]]:
    """Apply confirm/rescore/remove verdicts; return (survivors, issues)."""
    verdicts: dict[str, dict] = {}
    for path in sorted(validation_dir.glob("batch-*-output.json")):
        output = json.loads(path.read_text(encoding="utf-8"))
        for verdict in output["verdicts"]:
            verdicts[verdict["finding_ref"]["content_hash"]] = verdict

    survivors: list[dict] = []
    issues: list[dict] = []
    for finding in findings:
        verdict = verdicts.get(finding["content_hash"])
        if verdict is None or verdict["action"] == "confirm":
            survivors.append(finding)
            continue
        if verdict["action"] == "rescore":
            updated = dict(finding)
            # null means "not changing this" — the schema requires the key.
            if verdict.get("new_severity") is not None:
                updated["severity"] = verdict["new_severity"]
            if verdict.get("new_confidence") is not None:
                updated["confidence"] = verdict["new_confidence"]
            survivors.append(updated)
            continue
        issues.append(
            {
                "severity": "warning",
                "kind": "other",
                "message": (
                    f"validator_removed[{verdict['remove_reason']}]: finding "
                    f"'{finding['title']}' ({finding['content_hash']}) — "
                    f"{verdict['reasoning']}"
                ),
                "source_component": "apply-verdicts",
            }
        )
    return survivors, issues


def run_simple_path(state) -> None:
    """Simple-mode stages after fan-out: dedup -> filter -> validate -> render."""
    tmp = state.tmp_dir
    cwd = state.options.project_root
    review_scope = state.scope

    findings, decomposition, observations = collect_findings(tmp / "00-raw")
    project = {"name": review_scope.project_name}
    if review_scope.scope_slug:
        project["scope_slug"] = review_scope.scope_slug

    issues_written = len(state.issues)
    write_stage(
        tmp / "10-merged", project, decomposition, state.issues, findings, observations
    )
    state.record_step(
        "consolidate", "ok", f"{len(findings)} finding(s) after dedup"
    )

    pipeline.maybe_diff_scope_filter(state, cwd)

    envelope, findings = load_stage(tmp / "10-merged")
    batch_count = write_batches(tmp / "15-validation", findings)
    state.record_step("batch", "ok", f"{batch_count} validator batch(es)")
    pipeline.run_validators(state)

    survivors, verdict_issues = apply_verdicts(tmp / "15-validation", findings)
    state.record_step(
        "apply-verdicts",
        "ok",
        f"{len(survivors)}/{len(findings)} finding(s) survived validation",
    )
    # envelope["issues"] already holds everything written before the filter
    # (plus any diff_scope_filtered entries); append only what came later.
    late_issues = state.issues[issues_written:]
    envelope_issues = envelope.get("issues", []) + late_issues + verdict_issues
    write_stage(
        tmp / "20-findings",
        envelope.get("project", project),
        envelope.get("decomposition", decomposition),
        envelope_issues,
        survivors,
        envelope.get("cross_cutting_observations"),
    )

    render_args = [
        "--input-dir",
        f"./{pipeline.TMP_DIR_NAME}/20-findings/",
        "--out-dir",
        ".",
        "--project-name",
        review_scope.project_name,
        "--scoring",
        "simple",
        "--run-id",
        state.run_id,
        "--run-report",
        str(pipeline._write_run_report(state)),
    ]
    if state.orchestrating_session_id:
        render_args += [
            "--orchestrating-session-id",
            state.orchestrating_session_id,
        ]
    if review_scope.scope_slug:
        render_args += ["--scope-slug", review_scope.scope_slug]
    pipeline.stage_cli("render-review.py", *render_args, cwd=cwd)
