#!/usr/bin/env bash
# Generated By: Claude Code (Claude Opus 4.6)
#
# Guard script: verifies .tmp-review/10-merged/ exists with findings
# from a prior /review run. Exits non-zero to abort skill loading.

set -euo pipefail

MERGED_DIR=".tmp-review/10-merged"

if [ ! -d "$MERGED_DIR" ]; then
  echo "ERROR: No prior review workspace found ($MERGED_DIR missing). Run /review first." >&2
  exit 1
fi

if [ ! -f "$MERGED_DIR/_envelope.json" ]; then
  echo "ERROR: $MERGED_DIR exists but has no _envelope.json. Run /review first." >&2
  exit 1
fi

FINDING_COUNT=$(find "$MERGED_DIR" -maxdepth 1 -name '*.json' ! -name '_envelope.json' | wc -l)
if [ "$FINDING_COUNT" -eq 0 ]; then
  echo "ERROR: $MERGED_DIR has no findings. Nothing to validate." >&2
  exit 1
fi

echo "Prior review workspace found: $FINDING_COUNT finding(s) in $MERGED_DIR"
