#!/usr/bin/env bash
# Generated By: Claude Code (Claude Opus 4.6)
#
# Post-validation script: apply verdicts, re-render, output summary.

set -euo pipefail

PLUGIN_ROOT="${1:?usage: finalize-supplementary.sh <plugin-root>}"
MERGED_DIR=".tmp-review/10-merged"
VALIDATION_DIR=".tmp-review/15-validation"
FINDINGS_DIR=".tmp-review/20-findings"

# --- Read project name and scope slug from envelope ---
PROJECT_NAME=$(python3 -c "
import json, sys
with open('$MERGED_DIR/_envelope.json') as f:
    env = json.load(f)
print(env.get('project', {}).get('name', 'unknown'))
")

SCOPE_SLUG=$(python3 -c "
import json, sys
with open('$MERGED_DIR/_envelope.json') as f:
    env = json.load(f)
print(env.get('project', {}).get('scope_slug', ''))
")

# --- Apply verdicts ---
python3 "$PLUGIN_ROOT/skills/review/scripts/apply-verdicts.py" \
  --input-dir "$MERGED_DIR" \
  --verdicts-dir "$VALIDATION_DIR" \
  --output-dir "$FINDINGS_DIR"

# --- Render ---
RENDER_ARGS=(
  --input-dir "$FINDINGS_DIR"
  --out-dir .
  --project-name "$PROJECT_NAME"
)
if [ -n "$SCOPE_SLUG" ]; then
  RENDER_ARGS+=(--scope-slug "$SCOPE_SLUG")
fi

python3 "$PLUGIN_ROOT/skills/review/scripts/render-review.py" "${RENDER_ARGS[@]}"

# --- Summary ---
COUNTS=$(python3 -c "
import json
from pathlib import Path

findings_dir = Path('$FINDINGS_DIR')
buckets = {'critical': 0, 'important': 0, 'suggestion': 0, 'needs-review': 0}

# Import assign_bucket from envelope
import sys
sys.path.insert(0, '$PLUGIN_ROOT')
from scripts.envelope import assign_bucket

for f in findings_dir.glob('*.json'):
    if f.name == '_envelope.json':
        continue
    finding = json.loads(f.read_text())
    bucket = assign_bucket(finding)
    buckets[bucket] = buckets.get(bucket, 0) + 1

parts = []
for b in ('critical', 'important', 'suggestion', 'needs-review'):
    parts.append(f'{buckets[b]} {b}')
print(', '.join(parts) + '.')
")

SLUG_SUFFIX=""
if [ -n "$SCOPE_SLUG" ]; then
  SLUG_SUFFIX="-$SCOPE_SLUG"
fi

echo ""
echo "Supplementary validation complete."
echo "$COUNTS"
echo ""
echo "Files updated:"
echo "  Findings-review${SLUG_SUFFIX}.json"
echo "  Findings-review${SLUG_SUFFIX}.md"
echo "  Findings-review${SLUG_SUFFIX}-supplementary.md"
