#!/usr/bin/env bash
# Generated By: Claude Code (Claude Opus 4.6)
#
# Pre-fetch script: validates workspace, counts existing batches,
# runs batcher for supplementary findings. Exits non-zero if no work.

set -euo pipefail

PLUGIN_ROOT="${1:?usage: prepare-supplementary.sh <plugin-root>}"
MERGED_DIR=".tmp-review/10-merged"
VALIDATION_DIR=".tmp-review/15-validation"

# --- Workspace guard ---
if [ ! -d "$MERGED_DIR" ]; then
  echo "ERROR: No prior review workspace found ($MERGED_DIR missing). Run /review first." >&2
  exit 1
fi

if [ ! -f "$MERGED_DIR/_envelope.json" ]; then
  echo "ERROR: $MERGED_DIR exists but has no _envelope.json. Run /review first." >&2
  exit 1
fi

FINDING_COUNT=$(find "$MERGED_DIR" -maxdepth 1 -name '*.json' ! -name '_envelope.json' | wc -l)
if [ "$FINDING_COUNT" -eq 0 ]; then
  echo "ERROR: $MERGED_DIR has no findings. Nothing to validate." >&2
  exit 1
fi

# --- Count existing batch output files for offset ---
OFFSET=0
if [ -d "$VALIDATION_DIR" ]; then
  OFFSET=$(find "$VALIDATION_DIR" -maxdepth 1 -name 'batch-*-output.json' 2>/dev/null | wc -l)
fi

# --- Batch supplementary findings ---
python3 "$PLUGIN_ROOT/skills/review/scripts/batch-findings.py" \
  --input-dir "$MERGED_DIR" \
  --output-dir "$VALIDATION_DIR" \
  --only-buckets suggestion,needs-review \
  --batch-offset "$OFFSET"

# --- Report batch files for validator dispatch ---
BATCH_FILES=$(find "$VALIDATION_DIR" -maxdepth 1 -name 'batch-*-input.json' | sort | while read -r f; do
  NUM=$(basename "$f" | sed 's/batch-\([0-9]*\)-input.json/\1/')
  if [ "$NUM" -gt "$OFFSET" ]; then
    echo "$f"
  fi
done)

if [ -z "$BATCH_FILES" ]; then
  echo "No supplementary findings to validate."
  exit 0
fi

echo "Batches to validate:"
for f in $BATCH_FILES; do
  echo "  $f"
done
