#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.7)
"""Emit the apply-review action report as shared-schema JSON.

apply-review is a consumer skill, not a producer of findings, so the output
has `findings: []` and a populated `applied[]` array plus any meta-issues
from the run. No markdown is produced — apply-review has no user-facing
review document.

Exits non-zero if validation against the shared schema fails; no file is
written on validation failure.
"""

import argparse
import json
import sys
from pathlib import Path

import jsonschema

SKILL_ROOT = Path(__file__).resolve().parent.parent
PLUGIN_ROOT = SKILL_ROOT.parent.parent

sys.path.insert(0, str(PLUGIN_ROOT))
from scripts.envelope import (  # noqa: E402
    build_envelope,
    format_validation_error,
    validate_envelope,
)

SOURCE = "apply-review"


def _build_apply_envelope(pre_render: dict, project_name: str) -> dict:
    project = pre_render.get("project") or {"name": project_name}
    return build_envelope(
        source=SOURCE,
        project=project,
        findings=[],
        issues=pre_render.get("issues", []),
        applied=pre_render.get("applied", []),
    )


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        required=True,
        help=(
            "pre-render JSON with `applied[]` and optional `issues[]` and "
            "`project` keys"
        ),
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        required=True,
        help="directory for the output JSON (typically the project root)",
    )
    parser.add_argument("--project-name", required=True)
    args = parser.parse_args(argv)

    with args.input.open("r", encoding="utf-8") as fh:
        pre_render = json.load(fh)

    envelope = _build_apply_envelope(pre_render, args.project_name)

    try:
        validate_envelope(envelope)
    except jsonschema.ValidationError as exc:
        print(format_validation_error(exc, "apply-review"), file=sys.stderr)
        return 1

    args.out_dir.mkdir(parents=True, exist_ok=True)
    json_path = args.out_dir / "Report-apply-review.json"
    with json_path.open("w", encoding="utf-8") as fh:
        json.dump(envelope, fh, indent=2)
        fh.write("\n")

    print(f"render-apply-report: wrote {json_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
