#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.7)
"""Emit the apply-review action report as shared-schema JSON.

apply-review is a consumer skill, not a producer of findings, so the output
has `findings: []` and a populated `applied[]` array plus any meta-issues
from the run. No markdown is produced — apply-review has no user-facing
review document.

Exits non-zero if validation against the shared schema fails; no file is
written on validation failure.
"""

import argparse
import json
import logging
import sys
from pathlib import Path

import jsonschema

logger = logging.getLogger("render-apply-report")

SKILL_ROOT = Path(__file__).resolve().parent.parent
PLUGIN_ROOT = SKILL_ROOT.parent.parent

sys.path.insert(0, str(PLUGIN_ROOT))
from scripts.envelope import (  # noqa: E402
    build_envelope,
    format_validation_error,
    validate_envelope,
)

SOURCE = "apply-review"


def _build_apply_review_envelope(pre_render: dict, project_name: str) -> dict:
    project = pre_render.get("project") or {"name": project_name}
    return build_envelope(
        source=SOURCE,
        project=project,
        findings=[],
        issues=pre_render.get("issues", []),
        applied=pre_render.get("applied", []),
    )


def _validate_input(path: Path) -> int:
    """Validate a Findings-*.json (or any shared-schema envelope) as input.

    apply-review's main agent invokes this BEFORE any code changes so that
    malformed input is caught and surfaced to the user — not parsed partially
    and acted on.
    """
    if not path.exists():
        print(f"error: input file not found: {path}", file=sys.stderr)
        return 1
    try:
        with path.open("r", encoding="utf-8") as fh:
            doc = json.load(fh)
    except json.JSONDecodeError as exc:
        print(
            f"error: {path} is not valid JSON: {exc}"
            f" (line {exc.lineno}, col {exc.colno})",
            file=sys.stderr,
        )
        return 1
    try:
        validate_envelope(doc)
    except jsonschema.ValidationError as exc:
        print(format_validation_error(exc, "apply-review input"), file=sys.stderr)
        return 1
    print(f"input-validate: {path} validates against the shared schema")
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        help=(
            "pre-render JSON with `applied[]` and optional `issues[]` and "
            "`project` keys (required unless --validate-input is used)"
        ),
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        help="directory for the output JSON (typically the project root)",
    )
    parser.add_argument("--project-name")
    parser.add_argument(
        "--validate-input",
        type=Path,
        default=None,
        help=(
            "validate-only mode: checks the given Findings-*.json against the "
            "shared schema and exits. Used by the skill before acting on "
            "input to fail fast on malformed producer output."
        ),
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="verbose diagnostic logging to stderr",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="suppress the success summary line on stdout",
    )
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.DEBUG if args.debug else logging.INFO,
        format="%(levelname)s: %(message)s",
        stream=sys.stderr,
    )

    if args.validate_input is not None:
        return _validate_input(args.validate_input)

    # Report-emission mode requires the usual args.
    missing = [
        name
        for name, value in (
            ("--input", args.input),
            ("--out-dir", args.out_dir),
            ("--project-name", args.project_name),
        )
        if value is None
    ]
    if missing:
        parser.error(f"the following arguments are required: {', '.join(missing)}")

    logger.debug("input=%s out-dir=%s project-name=%s", args.input, args.out_dir, args.project_name)

    try:
        with args.input.open("r", encoding="utf-8") as fh:
            pre_render = json.load(fh)
    except FileNotFoundError:
        logger.error("input file not found: %s", args.input)
        return 1
    except json.JSONDecodeError as exc:
        logger.error(
            "invalid JSON in %s: %s (line %d, col %d)",
            args.input, exc, exc.lineno, exc.colno,
        )
        return 1

    envelope = _build_apply_review_envelope(pre_render, args.project_name)

    try:
        validate_envelope(envelope)
    except jsonschema.ValidationError as exc:
        logger.error("%s", format_validation_error(exc, "apply-review"))
        return 1

    args.out_dir.mkdir(parents=True, exist_ok=True)
    json_path = args.out_dir / "Report-apply-review.json"
    with json_path.open("w", encoding="utf-8") as fh:
        json.dump(envelope, fh, indent=2)
        fh.write("\n")

    if not args.quiet:
        print(f"render-apply-report: wrote {json_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
