# Generated By: Claude Code (Claude Fable 5)
"""Shared fixtures for orchestrator tests."""

import subprocess
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
FIXTURES_DIR = REPO_ROOT / "skills" / "review" / "tests" / "fixtures"


def _git(cwd, *args):
    subprocess.run(
        ["git", *args], cwd=cwd, check=True, capture_output=True, text=True
    )


@pytest.fixture
def git_repo(tmp_path):
    """Repo with origin/HEAD pointing at main and one feature commit."""
    repo = tmp_path / "repo"
    repo.mkdir()
    _git(repo, "init", "-b", "main")
    _git(repo, "config", "user.email", "t@t")
    _git(repo, "config", "user.name", "t")
    (repo / "app.py").write_text("print('hi')\n")
    _git(repo, "add", ".")
    _git(repo, "commit", "-m", "initial")
    _git(repo, "update-ref", "refs/remotes/origin/main", "HEAD")
    _git(
        repo,
        "symbolic-ref",
        "refs/remotes/origin/HEAD",
        "refs/remotes/origin/main",
    )
    _git(repo, "checkout", "-b", "feature")
    (repo / "feature.py").write_text("x = 1\n")
    _git(repo, "add", ".")
    _git(repo, "commit", "-m", "feature change")
    return repo


@pytest.fixture
def fixtures_dir() -> Path:
    return FIXTURES_DIR
