# Generated By: Claude Code (Claude Fable 5)
"""Tests for orchestrator/scope.py against throwaway git repos."""

import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO_ROOT))
from orchestrator import scope  # noqa: E402


def _git(cwd, *args):
    subprocess.run(
        ["git", *args], cwd=cwd, check=True, capture_output=True, text=True
    )


class TestGitContext:
    def test_default_branch(self, git_repo):
        assert scope.check_git_context(str(git_repo)) == "origin/main"

    def test_not_a_repo(self, tmp_path):
        with pytest.raises(scope.ScopeError, match="Not inside a git repository"):
            scope.check_git_context(str(tmp_path))

    def test_no_origin_head(self, tmp_path):
        repo = tmp_path / "bare"
        repo.mkdir()
        _git(repo, "init", "-b", "main")
        with pytest.raises(scope.ScopeError, match="default branch"):
            scope.check_git_context(str(repo))


class TestPrScope:
    def test_scope_block(self, git_repo):
        text, base = scope.compute_pr_scope(str(git_repo), 42, "origin/main")
        assert text.startswith("## PR Scope: #42")
        assert f"Merge base: {base[:12]}" in text
        assert "feature.py" in text
        assert "Report findings ONLY for the changed files" in text
        assert "The output filename slug is: pr-42" in text
        assert len(base) == 40

    def test_no_changes_warns(self, git_repo):
        _git(git_repo, "checkout", "main")
        text, base = scope.compute_pr_scope(str(git_repo), 7, "origin/main")
        assert "WARNING: No changed files" in text
        assert base == ""

    def test_bad_branch_warns(self, git_repo):
        text, base = scope.compute_pr_scope(str(git_repo), 7, "origin/nope")
        assert "WARNING: Could not determine merge base" in text
        assert base == ""


class TestStandards:
    def test_local_claude_md_included(self, git_repo):
        (git_repo / "CLAUDE.md").write_text("Use tabs.\n")
        text = scope.gather_standards(str(git_repo))
        assert "Project standards (CLAUDE.md)" in text
        assert "Use tabs." in text

    def test_absent_files_yield_empty(self, git_repo, monkeypatch):
        monkeypatch.setattr(scope, "_external_standards", lambda root: "")
        assert scope.gather_standards(str(git_repo)) == ""

    def test_external_failure_is_graceful(self, git_repo, monkeypatch):
        # No gh, no ~/source/standards in test env: must not raise.
        monkeypatch.setenv("HOME", str(git_repo))
        assert scope._external_standards(str(git_repo)) == ""

    def test_external_injected_when_owner_matches(self, git_repo, tmp_path, monkeypatch):
        home = tmp_path / "home"
        standards = home / "source" / "standards"
        standards.mkdir(parents=True)
        (standards / "CLAUDE.md").write_text("See [naming](common/naming.md).\n")
        monkeypatch.setenv("HOME", str(home))
        _git(git_repo, "remote", "add", "origin", "git@github.com:jewzaam/repo.git")

        real_run = scope.subprocess.run

        def fake_run(argv, **kwargs):
            if argv[:2] == ["gh", "api"]:
                class R:
                    returncode = 0
                    stdout = "jewzaam\n"
                    stderr = ""
                return R()
            return real_run(argv, **kwargs)

        monkeypatch.setattr(scope.subprocess, "run", fake_run)
        text = scope._external_standards(str(git_repo))
        # Injected with relative links rewritten to absolute standards paths.
        assert "~/source/standards/common/naming.md" in text

    def test_external_skipped_when_owner_differs(self, git_repo, tmp_path, monkeypatch):
        home = tmp_path / "home"
        standards = home / "source" / "standards"
        standards.mkdir(parents=True)
        (standards / "CLAUDE.md").write_text("content\n")
        monkeypatch.setenv("HOME", str(home))
        _git(git_repo, "remote", "add", "origin", "git@github.com:someone-else/repo.git")

        real_run = scope.subprocess.run

        def fake_run(argv, **kwargs):
            if argv[:2] == ["gh", "api"]:
                class R:
                    returncode = 0
                    stdout = "jewzaam\n"
                    stderr = ""
                return R()
            return real_run(argv, **kwargs)

        monkeypatch.setattr(scope.subprocess, "run", fake_run)
        assert scope._external_standards(str(git_repo)) == ""


class TestProbe:
    def test_python_repo(self, git_repo):
        name, language, build, test = scope.probe_project(str(git_repo))
        assert name == "repo"  # no origin URL -> directory name
        assert language == "Python"
        assert test == "pytest"

    def test_makefile_wins(self, git_repo):
        (git_repo / "Makefile").write_text("test:\n\ttrue\n")
        _, _, build, _ = scope.probe_project(str(git_repo))
        assert build == "make"


class TestComputeScope:
    def test_pr_review(self, git_repo):
        s = scope.compute_scope(str(git_repo), 42, "")
        assert s.pr_number == 42
        assert s.scope_slug == "pr-42"
        assert s.merge_base
        assert "## PR Scope: #42" in s.pr_scope_text

    def test_full_repo_review(self, git_repo):
        s = scope.compute_scope(str(git_repo), None, "")
        assert s.merge_base == ""
        assert s.scope_slug == ""
        assert s.pr_scope_text == ""

    def test_guidance_slug(self, git_repo):
        s = scope.compute_scope(str(git_repo), None, "Focus on Auth Layer!")
        assert s.guidance == "Focus on Auth Layer!"
        assert s.scope_slug == "focus-on-aut"
        assert len(s.scope_slug) <= 12


class TestRemoteOwner:
    def test_https_simple(self):
        assert scope._remote_owner("https://github.com/jewzaam/repo.git") == "jewzaam"

    def test_ssh_simple(self):
        assert scope._remote_owner("git@gitlab.com:nmalik/repo.git") == "nmalik"

    def test_nested_subgroup_path(self):
        assert scope._remote_owner("https://gitlab.com/topgroup/sub/repo.git") == "topgroup"
        assert scope._remote_owner("git@gitlab.com:topgroup/sub/repo.git") == "topgroup"


class TestDiffStatFailure:
    def test_diff_stat_error_degrades_to_warning(self, git_repo, monkeypatch):
        real_git = scope._git

        def failing_git(root, *args):
            if args[0] == "diff":
                raise scope.subprocess.CalledProcessError(128, ["git", "diff"])
            return real_git(root, *args)

        monkeypatch.setattr(scope, "_git", failing_git)
        text, base = scope.compute_pr_scope(str(git_repo), 5, "origin/main")
        assert "WARNING: Could not compute diff stats" in text
        assert base == ""


class TestProbeBranches:
    def test_go_repo(self, tmp_path):
        repo = tmp_path / "gorepo"
        repo.mkdir()
        (repo / "main.go").write_text("package main\n")
        name, language, build, test = scope.probe_project(str(repo))
        assert language == "Go"
        assert test == "go test"

    def test_npm_repo_with_test_script(self, tmp_path):
        repo = tmp_path / "js"
        repo.mkdir()
        (repo / "app.js").write_text("x\n")
        (repo / "package.json").write_text('{"scripts": {"test": "jest"}}')
        name, language, build, test = scope.probe_project(str(repo))
        assert build == "npm"
        assert test == "npm test"

    def test_unknown_everything(self, tmp_path):
        repo = tmp_path / "empty"
        repo.mkdir()
        (repo / "data.txt").write_text("x\n")
        name, language, build, test = scope.probe_project(str(repo))
        assert (language, build, test) == ("unknown", "unknown", "unknown")


class TestProbeFallback:
    def test_rglob_fallback_outside_git(self, tmp_path):
        repo = tmp_path / "plain"
        (repo / "sub").mkdir(parents=True)
        (repo / "sub" / "thing.py").write_text("x\n")
        name, language, build, test = scope.probe_project(str(repo))
        assert language == "Python"  # found via rglob, no git
