# Generated By: Claude Code (Claude Fable 5)
"""Tests for orchestrator/pipeline.py with a monkeypatched agent backend."""

import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO_ROOT))
from orchestrator import backend, pipeline  # noqa: E402


def _lens_output(concern, concern_slug, dimension_slug="full-scope"):
    return {
        "agent_id": f"{concern_slug}/{dimension_slug}",
        "concern": concern,
        "concern_slug": concern_slug,
        "dimension_name": "full scope",
        "dimension_slug": dimension_slug,
        "dimension_scope": {},
        "findings": [
            {
                "title": f"{concern_slug} finding",
                "runtime_scope": "service-internal",
                "runtime_scope_justification": "app.py is runtime code.",
                "failure_mode": "crash-or-outage",
                "failure_mode_justification": "Unhandled error path crashes.",
                "evidence_quality": "demonstrated",
                "evidence_quality_justification": "Traced directly in code.",
                "trace_origin": "entry-point",
                "trace_origin_justification": "Traced from app.py main entry.",
                "effort_to_fix": "small",
                "effort_to_fix_justification": "One guard clause.",
                "locations": [{"path": "app.py", "line": "1", "role": "primary"}],
                "issue": "It crashes on empty input.",
                "why_it_matters": "Production outage on bad input.",
                "suggested_fix": "Add a guard clause.",
            }
        ],
        "cross_cutting_observations": [],
    }


def _fake_run_agent_factory(calls, selector_response="default", fail_labels=(), fail_validators=False):
    """Route fake responses by prompt content; record every call."""

    def fake_run_agent(prompt, *, schema, model, allowed_tools, cwd, tools=None, effort=None, timeout_s=600, trace_file=None, label="", redact=None, otel_attributes=None):
        calls.append({"prompt": prompt, "model": model, "allowed": allowed_tools, "tools": tools})

        if "Select which review lenses" in prompt:
            if selector_response == "fail":
                return backend.AgentResult(error="selector exploded", cost_usd=0.001)
            if selector_response == "two-dims":
                return backend.AgentResult(
                    output={
                        "lenses": [{"name": "implementation", "rationale": "always"}],
                        "dimensions": [
                            {"name": "core", "slug": "core", "scope": {}},
                            {"name": "docs", "slug": "docs", "scope": {}},
                        ],
                    },
                    cost_usd=0.001,
                )
            if selector_response == "empty":
                return backend.AgentResult(
                    output={"lenses": []},
                    cost_usd=0.001,
                )
            return backend.AgentResult(
                output={
                    "lenses": [{"name": "implementation", "rationale": "always"}],
                },
                cost_usd=0.001,
            )

        if "validator agent" in prompt:
            if fail_validators:
                return backend.AgentResult(error="validator exploded", cost_usd=0.002)
            hashes = re.findall(r"content_hash: ([a-f0-9]{16,64})", prompt)
            return backend.AgentResult(
                output={
                    "batch_number": 1,
                    "verdicts": [
                        {
                            "finding_ref": {"content_hash": h},
                            "action": "confirm",
                            "reasoning": "verified in code",
                        }
                        for h in hashes
                    ],
                },
                cost_usd=0.005,
            )

        match = re.search(r'agent_id to "([a-z]+)/([a-z-]+)"', prompt)
        slug = match.group(1) if match else "implementation"
        dim_slug = match.group(2) if match else "full-scope"
        if slug in fail_labels:
            return backend.AgentResult(error=f"{slug} agent failed", cost_usd=0.003)
        concern_match = re.search(r"for the \*\*(.+?)\*\* axis", prompt)
        return backend.AgentResult(
            output=_lens_output(concern_match.group(1), slug, dimension_slug=dim_slug),
            cost_usd=0.01,
        )

    return fake_run_agent


def _options(git_repo, **overrides):
    defaults = dict(project_root=str(git_repo), parallel=2, timeout_s=30)
    defaults.update(overrides)
    return pipeline.Options(**defaults)


class TestCategoricalEndToEnd:
    def test_full_run(self, git_repo, monkeypatch):
        calls = []
        monkeypatch.setattr(backend, "run_agent", _fake_run_agent_factory(calls))
        rc = pipeline.run_review(_options(git_repo))
        assert rc == 0

        findings = json.loads((git_repo / "Findings-review.json").read_text())
        assert findings["source"] == "review"
        assert len(findings["findings"]) == 1
        assert findings["findings"][0]["severity"] in ("critical", "important")
        assert (git_repo / "Findings-review.md").is_file()
        assert (git_repo / "Findings-review-supplementary.md").is_file()

        costs = json.loads((git_repo / ".tmp-review" / "costs.json").read_text())
        assert costs["total_cost_usd"] > 0
        assert set(costs["by_stage"]) >= {"select", "review", "validate"}
        # Only the selected lens ran (selector picked implementation only).
        lens_calls = [c for c in calls if "axis within the dimension" in c["prompt"]]
        assert len(lens_calls) == 1
        assert lens_calls[0]["allowed"] == list(pipeline.LENS_TOOLS.allowed)
        assert lens_calls[0]["tools"] == pipeline.LENS_TOOLS.tools  # no Bash

    def test_selector_failure_falls_back_to_all_lenses(self, git_repo, monkeypatch):
        calls = []
        monkeypatch.setattr(
            backend,
            "run_agent",
            _fake_run_agent_factory(calls, selector_response="fail"),
        )
        rc = pipeline.run_review(_options(git_repo))
        assert rc == 0
        lens_calls = [c for c in calls if "axis within the dimension" in c["prompt"]]
        assert len(lens_calls) == len(pipeline.lenses.LENSES)  # all lenses ran
        # Selector failure recorded as an issue in the envelope.
        findings = json.loads((git_repo / "Findings-review.json").read_text())
        kinds = [issue["kind"] for issue in findings["issues"]]
        assert "subagent_failure" in kinds

    def test_failed_lens_agent_becomes_issue(self, git_repo, monkeypatch):
        calls = []
        monkeypatch.setattr(
            backend,
            "run_agent",
            _fake_run_agent_factory(calls, fail_labels={"implementation"}),
        )
        # Selector picks implementation only; its agent fails every retry.
        rc = pipeline.run_review(_options(git_repo))
        assert rc == 1  # no lens output at all
        costs = json.loads((git_repo / ".tmp-review" / "costs.json").read_text())
        impl_entries = [e for e in costs["entries"] if e["label"] == "implementation/full-scope"]
        assert len(impl_entries) == 3  # initial + 2 retries, all costed

    def test_validator_failure_passes_findings_through(self, git_repo, monkeypatch):
        calls = []
        monkeypatch.setattr(
            backend,
            "run_agent",
            _fake_run_agent_factory(calls, fail_validators=True),
        )
        rc = pipeline.run_review(_options(git_repo))
        assert rc == 0  # run completes despite validator failure
        findings = json.loads((git_repo / "Findings-review.json").read_text())
        # Finding survives unvalidated (apply-verdicts passthrough).
        assert len(findings["findings"]) == 1
        kinds = [issue["kind"] for issue in findings["issues"]]
        assert "subagent_failure" in kinds

    def test_dry_run_dispatches_nothing(self, git_repo, monkeypatch, capsys):
        def explode(*args, **kwargs):
            raise AssertionError("agent dispatched during dry run")

        monkeypatch.setattr(backend, "run_agent", explode)
        rc = pipeline.run_review(_options(git_repo, dry_run=True))
        assert rc == 0
        out = capsys.readouterr().out
        assert "selector prompt" in out
        assert not (git_repo / ".tmp-review").exists()


class TestRetry:
    def test_retry_then_success_accumulates_cost(self, git_repo, monkeypatch):
        state = pipeline.RunState(
            options=_options(git_repo),
            scope=None,  # unused by _run_with_retry
        )
        results = [
            backend.AgentResult(error="flaky", cost_usd=0.01),
            backend.AgentResult(output={"ok": True}, cost_usd=0.02),
        ]
        final = pipeline._run_with_retry(
            state, "review", "x", "sonnet", lambda: results.pop(0)
        )
        assert final.error is None
        assert [c.cost_usd for c in state.costs] == [0.01, 0.02]
        assert [c.retries for c in state.costs] == [0, 1]

    def test_denials_recorded_in_cost_entry(self, git_repo):
        state = pipeline.RunState(options=_options(git_repo), scope=None)
        denial = {"tool_name": "Bash", "tool_input": {"command": "touch x"}}
        result = backend.AgentResult(output={"ok": True}, cost_usd=0.01)
        result.permission_denials = [denial]
        final = pipeline._run_with_retry(
            state, "review", "x", "sonnet", lambda: result
        )
        assert final.error is None
        assert state.costs[0].denials == [denial]

    def test_local_schema_validation_triggers_retry(self, git_repo):
        state = pipeline.RunState(options=_options(git_repo), scope=None)
        schema = {"type": "object", "required": ["needed"]}
        results = [
            backend.AgentResult(output={"wrong": 1}, cost_usd=0.01),
            backend.AgentResult(output={"needed": 1}, cost_usd=0.01),
        ]
        final = pipeline._run_with_retry(
            state, "review", "x", "sonnet", lambda: results.pop(0), schema=schema
        )
        assert final.error is None
        assert final.output == {"needed": 1}
        assert len(state.costs) == 2


class TestStageCli:
    def test_nonzero_exit_raises_pipeline_error(self, tmp_path):
        state_cwd = str(tmp_path)
        try:
            pipeline.stage_cli("validate-findings.py", "/nonexistent.json", cwd=state_cwd)
        except pipeline.PipelineError as exc:
            assert "validate-findings.py failed" in str(exc)
        else:
            raise AssertionError("expected PipelineError")


class TestRevalidateRaw:
    def test_invalid_raw_file_removed_and_recorded(self, git_repo):
        state = pipeline.RunState(
            options=_options(git_repo), scope=None
        )
        raw = state.tmp_dir / "00-raw"
        raw.mkdir(parents=True)
        (raw / "implementation-full-scope.json").write_text('{"not": "agent output"}')
        pipeline._revalidate_raw(state)
        assert not (raw / "implementation-full-scope.json").exists()
        assert state.issues and state.issues[0]["kind"] == "validation_failed"


class TestLedgerOnFatal:
    def test_costs_written_when_stage_raises(self, git_repo, monkeypatch):
        calls = []
        monkeypatch.setattr(backend, "run_agent", _fake_run_agent_factory(calls))

        def boom(*args, **kwargs):
            raise pipeline.PipelineError("consolidator exploded")

        monkeypatch.setattr(pipeline, "stage_cli", boom)
        try:
            pipeline.run_review(_options(git_repo))
        except pipeline.PipelineError:
            pass
        else:
            raise AssertionError("expected PipelineError")
        costs = json.loads((git_repo / ".tmp-review" / "costs.json").read_text())
        assert costs["total_cost_usd"] > 0  # spend persisted despite fatal error


class TestMaxAgentsCapsLenses:
    def test_lens_count_trimmed_to_max_agents(self, git_repo, monkeypatch):
        calls = []
        monkeypatch.setattr(
            backend,
            "run_agent",
            _fake_run_agent_factory(calls, selector_response="fail"),  # all 7 lenses
        )
        rc = pipeline.run_review(_options(git_repo, max_agents=3))
        assert rc == 0
        lens_calls = [c for c in calls if "axis within the dimension" in c["prompt"]]
        assert len(lens_calls) == 3


class TestPartialFanOutFailure:
    def test_one_failed_lens_does_not_block_others(self, git_repo, monkeypatch):
        calls = []
        monkeypatch.setattr(
            backend,
            "run_agent",
            _fake_run_agent_factory(
                calls, selector_response="fail", fail_labels={"security"}
            ),
        )
        rc = pipeline.run_review(_options(git_repo))
        assert rc == 0
        findings = json.loads((git_repo / "Findings-review.json").read_text())
        assert len(findings["findings"]) >= 1  # survivors consolidated
        kinds = [i["kind"] for i in findings["issues"]]
        assert "subagent_failure" in kinds


class TestIssuesMergedOffsets:
    def test_no_duplicate_issues_across_two_merges(self, git_repo, monkeypatch):
        calls = []
        monkeypatch.setattr(
            backend,
            "run_agent",
            _fake_run_agent_factory(
                calls, fail_labels={"security"}, fail_validators=True,
                selector_response="fail",
            ),
        )
        rc = pipeline.run_review(_options(git_repo))
        assert rc == 0
        findings = json.loads((git_repo / "Findings-review.json").read_text())
        messages = [i["message"] for i in findings["issues"]]
        assert len(messages) == len(set(messages))  # merged once each
        assert any("security" in m for m in messages)
        assert any("validator" in m for m in messages)


class TestMultiDimensionFanOut:
    def test_two_dimensions_produce_two_raw_files(self, git_repo, monkeypatch):
        calls = []
        monkeypatch.setattr(
            backend,
            "run_agent",
            _fake_run_agent_factory(calls, selector_response="two-dims"),
        )
        rc = pipeline.run_review(_options(git_repo))
        assert rc == 0
        raw = git_repo / ".tmp-review" / "00-raw"
        # wiped-then-refilled by the run; findings JSON aggregates both dims
        findings = json.loads((git_repo / "Findings-review.json").read_text())
        dims = {d["dimension_slug"] for d in findings["decomposition"]}
        assert dims == {"core", "docs"}


class TestDenialAggregation:
    def test_denials_by_tool_in_costs(self, git_repo):
        state = pipeline.RunState(options=_options(git_repo), scope=None)
        state.tmp_dir.mkdir(exist_ok=True)
        denial = {"tool_name": "Bash", "tool_input": {"command": "git -C x diff"}}
        result = backend.AgentResult(output={"ok": True}, cost_usd=0.01)
        result.permission_denials = [denial, dict(denial)]
        pipeline._run_with_retry(state, "select", "x", "haiku", lambda: result)
        report = pipeline._write_costs(state)
        assert report["denials_by_tool"] == {"Bash": 2}


class TestSelectOnly:
    def test_select_only_saves_and_run_consumes(self, git_repo, monkeypatch, tmp_path, capsys):
        calls = []
        monkeypatch.setattr(backend, "run_agent", _fake_run_agent_factory(calls))
        selection_file = tmp_path / "sel.json"
        rc = pipeline.run_select_only(_options(git_repo), selection_file)
        assert rc == 0
        out = capsys.readouterr().out
        assert "lens: implementation:" in out
        assert selection_file.is_file()
        selector_calls = [c for c in calls if "Select which review lenses" in c["prompt"]]
        assert len(selector_calls) == 1

        rc = pipeline.run_review(_options(git_repo), selection_file=selection_file)
        assert rc == 0
        selector_calls = [c for c in calls if "Select which review lenses" in c["prompt"]]
        assert len(selector_calls) == 1  # NOT re-run
        assert not selection_file.exists()  # consumed
        costs = json.loads((git_repo / ".tmp-review" / "costs.json").read_text())
        assert any(e["stage"] == "select" for e in costs["entries"])  # cost replayed

    def test_stale_selection_ignored(self, git_repo, monkeypatch, tmp_path):
        calls = []
        monkeypatch.setattr(backend, "run_agent", _fake_run_agent_factory(calls))
        selection_file = tmp_path / "sel.json"
        selection_file.write_text(json.dumps({
            "head": "0" * 40, "selector_output": {"lenses": []}, "costs": [],
        }))
        rc = pipeline.run_review(_options(git_repo), selection_file=selection_file)
        assert rc == 0
        selector_calls = [c for c in calls if "Select which review lenses" in c["prompt"]]
        assert len(selector_calls) == 1  # re-ran due to stale head
        assert not selection_file.exists()


    def test_malformed_selection_file_tolerated(self, git_repo, monkeypatch, tmp_path):
        calls = []
        monkeypatch.setattr(backend, "run_agent", _fake_run_agent_factory(calls))
        selection_file = tmp_path / "sel.json"
        head = pipeline._head_sha(str(git_repo))
        selection_file.write_text(json.dumps({
            "head": head,
            "selector_output": ["not", "a", "dict"],
            "costs": [{"stage": "select", "label": "x", "model": "haiku",
                       "cost_usd": 0.01, "bogus_key": True}, "junk"],
        }))
        rc = pipeline.run_review(_options(git_repo), selection_file=selection_file)
        assert rc == 0  # non-dict selector_output -> selector re-ran; no crash
        costs = json.loads((git_repo / ".tmp-review" / "costs.json").read_text())
        replayed = [e for e in costs["entries"] if e["label"] == "x"]
        assert len(replayed) == 1  # valid keys replayed, bogus dropped
