# Generated By: Claude Code (Claude Fable 5)
"""Tests for orchestrator/lenses.py selection and dimension capping."""

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO_ROOT))
from orchestrator import lenses  # noqa: E402


def test_roster_matches_agent_output_enum():
    schema = json.loads(
        (
            REPO_ROOT / "skills" / "review" / "schemas" / "agent-output.schema.json"
        ).read_text(encoding="utf-8")
    )
    schema_slugs = set(schema["properties"]["concern_slug"]["enum"])
    schema_concerns = set(schema["properties"]["concern"]["enum"])
    assert {lens.slug for lens in lenses.LENSES} == schema_slugs
    assert {lens.concern for lens in lenses.LENSES} == schema_concerns


def test_selector_subset_plus_always_run():
    out = {
        "lenses": [
            {"name": "security", "rationale": "touches auth"},
            {"name": "test", "rationale": "no tests added"},
        ]
    }
    selected, source, rationales = lenses.resolve_selection(out)
    slugs = [lens.slug for lens in selected]
    assert source == "selector"
    assert slugs[0] == "implementation"  # force-included first
    assert set(slugs) == {"implementation", "security", "test"}
    assert rationales["security"] == "touches auth"


def test_empty_selection_falls_back_to_all():
    for bad in (None, {}, {"lenses": []}, {"lenses": [{"name": "nope", "rationale": "x"}]}):
        selected, source, _ = lenses.resolve_selection(bad)
        assert source == "all-lenses-fallback"
        assert len(selected) == len(lenses.LENSES)


def test_duplicates_dropped():
    out = {
        "lenses": [
            {"name": "implementation", "rationale": "a"},
            {"name": "implementation", "rationale": "b"},
        ]
    }
    selected, _, _ = lenses.resolve_selection(out)
    assert [lens.slug for lens in selected] == ["implementation"]


def test_dimensions_default_single():
    dims = lenses.resolve_dimensions(None, lens_count=3, max_agents=16)
    # Every scope key present, unset ones null — the agent-output schema
    # requires all three, and the lens prompt has the agent echo this back.
    assert dims == [
        {"name": "full scope", "slug": "full-scope", "scope": lenses.EMPTY_SCOPE}
    ]


def test_dimensions_capped_by_max_agents():
    out = {
        "dimensions": [
            {"name": "a", "slug": "a", "scope": {}},
            {"name": "b", "slug": "b", "scope": {}},
            {"name": "c", "slug": "c", "scope": {}},
        ]
    }
    # 7 lenses x 2 dims = 14 <= 16, but 3 dims = 21 > 16.
    dims = lenses.resolve_dimensions(out, lens_count=7, max_agents=16)
    assert [d["slug"] for d in dims] == ["a", "b"]


def test_dimensions_invalid_entries_dropped():
    out = {"dimensions": [{"name": "", "slug": "x"}, "junk", {"slug": "y"}]}
    dims = lenses.resolve_dimensions(out, lens_count=2, max_agents=16)
    assert dims[0]["slug"] == "full-scope"


def test_duplicate_dimension_slugs_deduped():
    out = {
        "dimensions": [
            {"name": "a", "slug": "same", "scope": {}},
            {"name": "b", "slug": "same", "scope": {}},
            {"name": "c", "slug": "other", "scope": {}},
        ]
    }
    dims = lenses.resolve_dimensions(out, lens_count=2, max_agents=16)
    assert [d["slug"] for d in dims] == ["same", "other"]


def test_roster_restriction_drops_out_of_roster_picks():
    roster = tuple(l for l in lenses.LENSES if l.slug not in ("security", "implementation"))
    out = {"lenses": [
        {"name": "security", "rationale": "x"},   # skipped by user
        {"name": "test", "rationale": "y"},
    ]}
    selected, source, _ = lenses.resolve_selection(out, roster)
    slugs = [l.slug for l in selected]
    assert source == "selector"
    assert slugs == ["test"]  # security dropped; implementation NOT re-added


def test_fallback_respects_roster():
    roster = tuple(l for l in lenses.LENSES if l.slug in ("test", "documentation"))
    selected, source, _ = lenses.resolve_selection(None, roster)
    assert source == "all-lenses-fallback"
    assert {l.slug for l in selected} == {"test", "documentation"}
