# Generated By: Claude Code (Claude Fable 5)
"""Tests for orchestrator/pipeline.py with a monkeypatched agent backend."""

import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO_ROOT))
from orchestrator import backend, pipeline  # noqa: E402


_SCOPE = {"paths": None, "theme": None, "shared_infrastructure": None}


def _lens_output(concern, concern_slug, dimension_slug="full-scope"):
    return {
        "agent_id": f"{concern_slug}/{dimension_slug}",
        "concern": concern,
        "concern_slug": concern_slug,
        "dimension_name": "full scope",
        "dimension_slug": dimension_slug,
        "dimension_scope": {"paths": None, "theme": None, "shared_infrastructure": None},
        "findings": [
            {
                "title": f"{concern_slug} finding",
                "runtime_scope": "service-internal",
                "runtime_scope_justification": "app.py is runtime code.",
                "failure_mode": "crash-or-outage",
                "failure_mode_justification": "Unhandled error path crashes.",
                "evidence_quality": "demonstrated",
                "evidence_quality_justification": "Traced directly in code.",
                "trace_origin": "entry-point",
                "trace_origin_justification": "Traced from app.py main entry.",
                "effort_to_fix": "small",
                "effort_to_fix_justification": "One guard clause.",
                "locations": [{"path": "app.py", "line": "1", "role": "primary"}],
                "issue": "It crashes on empty input.",
                "why_it_matters": "Production outage on bad input.",
                "suggested_fix": "Add a guard clause.",
            }
        ],
        "cross_cutting_observations": [],
    }


def _fake_run_agent_factory(calls, selector_response="default", fail_labels=(), fail_validators=False):
    """Route fake responses by prompt content; record every call."""

    def fake_run_agent(prompt, *, schema, model, allowed_tools, cwd, tools=None, effort=None, timeout_s=3600, trace_file=None, label="", redact=None, otel_attributes=None, **kwargs):
        calls.append({
            "prompt": prompt,
            "model": model,
            "allowed": allowed_tools,
            "tools": tools,
            **kwargs,
        })

        if "Select which review lenses" in prompt:
            if selector_response == "fail":
                return backend.AgentResult(error="selector exploded", cost_usd=0.001)
            if selector_response == "two-dims":
                return backend.AgentResult(
                    output={
                        "lenses": [{"name": "implementation", "rationale": "always"}],
                        "dimensions": [
                            {"name": "core", "slug": "core", "scope": _SCOPE},
                            {"name": "docs", "slug": "docs", "scope": _SCOPE},
                        ],
                    },
                    cost_usd=0.001,
                )
            if selector_response == "empty":
                return backend.AgentResult(
                    output={"lenses": [], "dimensions": []},
                    cost_usd=0.001,
                )
            return backend.AgentResult(
                output={
                    "lenses": [{"name": "implementation", "rationale": "always"}],
                    "dimensions": [],
                },
                cost_usd=0.001,
            )

        if "validator agent" in prompt:
            if fail_validators:
                return backend.AgentResult(error="validator exploded", cost_usd=0.002)
            hashes = re.findall(r"content_hash: ([a-f0-9]{16,64})", prompt)
            return backend.AgentResult(
                output={
                    "batch_number": 1,
                    "verdicts": [
                        {
                            "finding_ref": {"content_hash": h},
                            "action": "confirm",
                            "reasoning": "verified in code",
                        }
                        for h in hashes
                    ],
                },
                cost_usd=0.005,
            )

        match = re.search(r'agent_id to "([a-z]+)/([a-z-]+)"', prompt)
        slug = match.group(1) if match else "implementation"
        dim_slug = match.group(2) if match else "full-scope"
        if slug in fail_labels:
            return backend.AgentResult(error=f"{slug} agent failed", cost_usd=0.003)
        concern_match = re.search(r"for the \*\*(.+?)\*\* axis", prompt)
        return backend.AgentResult(
            output=_lens_output(concern_match.group(1), slug, dimension_slug=dim_slug),
            cost_usd=0.01,
        )

    return fake_run_agent


def _options(git_repo, **overrides):
    defaults = dict(project_root=str(git_repo), parallel=2, timeout_s=30)
    defaults.update(overrides)
    return pipeline.Options(**defaults)


class TestCategoricalEndToEnd:
    def test_full_run(self, git_repo, monkeypatch):
        calls = []
        monkeypatch.setenv("CLAUDE_CODE_SESSION_ID", "sess-e2e")
        monkeypatch.setattr(backend, "run_agent", _fake_run_agent_factory(calls))
        rc = pipeline.run_review(_options(git_repo))
        assert rc == 0
        # Run identity reaches both durable artifacts, and the two agree.
        costs = json.loads((git_repo / ".tmp-review" / "costs.json").read_text())
        findings = json.loads((git_repo / "Findings-review.json").read_text())
        assert costs["orchestrating_session_id"] == "sess-e2e"
        assert findings["orchestrating_session_id"] == "sess-e2e"
        assert findings["run_id"] == costs["run_id"]

        findings = json.loads((git_repo / "Findings-review.json").read_text())
        assert findings["source"] == "review"
        assert len(findings["findings"]) == 1
        assert findings["findings"][0]["severity"] in ("critical", "important")
        assert (git_repo / "Findings-review.md").is_file()
        assert (git_repo / "Findings-review-supplementary.md").is_file()

        costs = json.loads((git_repo / ".tmp-review" / "costs.json").read_text())
        assert costs["total_cost_usd"] > 0
        # Rolled up per stage/model, so the table shows where the spend went.
        assert all("/" in key for key in costs["by_stage"])
        assert {key.split("/", 1)[0] for key in costs["by_stage"]} >= {
            "select",
            "review",
            "validate",
        }
        assert "select/haiku" in costs["by_stage"]
        assert "validate/sonnet" in costs["by_stage"]
        assert set(costs["seconds_by_stage"]) == set(costs["by_stage"])
        # Only the selected lens ran (selector picked implementation only).
        lens_calls = [c for c in calls if "axis within the dimension" in c["prompt"]]
        assert len(lens_calls) == 1
        assert lens_calls[0]["allowed"] == list(pipeline.LENS_TOOLS.allowed)
        assert lens_calls[0]["tools"] == pipeline.LENS_TOOLS.tools  # no Bash

    def test_selector_failure_falls_back_to_all_lenses(self, git_repo, monkeypatch):
        calls = []
        monkeypatch.setattr(
            backend,
            "run_agent",
            _fake_run_agent_factory(calls, selector_response="fail"),
        )
        rc = pipeline.run_review(_options(git_repo))
        assert rc == 0
        lens_calls = [c for c in calls if "axis within the dimension" in c["prompt"]]
        assert len(lens_calls) == len(pipeline.lenses.LENSES)  # all lenses ran
        # Selector failure recorded as an issue in the envelope.
        findings = json.loads((git_repo / "Findings-review.json").read_text())
        kinds = [issue["kind"] for issue in findings["issues"]]
        assert "subagent_failure" in kinds

    def test_failed_lens_agent_becomes_issue(self, git_repo, monkeypatch, capsys):
        calls = []
        monkeypatch.setattr(
            backend,
            "run_agent",
            _fake_run_agent_factory(calls, fail_labels={"implementation"}),
        )
        # Selector picks implementation only; its agent fails every retry.
        rc = pipeline.run_review(_options(git_repo))
        assert rc == 1  # no lens output at all
        costs = json.loads((git_repo / ".tmp-review" / "costs.json").read_text())
        impl_entries = [e for e in costs["entries"] if e["label"] == "implementation/full-scope"]
        assert len(impl_entries) == 3  # initial + 2 retries, all costed
        assert "implementation/full-scope: implementation agent failed" in capsys.readouterr().err

    def test_validator_failure_passes_findings_through(self, git_repo, monkeypatch):
        calls = []
        monkeypatch.setattr(
            backend,
            "run_agent",
            _fake_run_agent_factory(calls, fail_validators=True),
        )
        rc = pipeline.run_review(_options(git_repo))
        assert rc == 0  # run completes despite validator failure
        findings = json.loads((git_repo / "Findings-review.json").read_text())
        # Finding survives unvalidated (apply-verdicts passthrough).
        assert len(findings["findings"]) == 1
        kinds = [issue["kind"] for issue in findings["issues"]]
        assert "subagent_failure" in kinds

    def test_dry_run_dispatches_nothing(self, git_repo, monkeypatch, capsys):
        def explode(*args, **kwargs):
            raise AssertionError("agent dispatched during dry run")

        monkeypatch.setattr(backend, "run_agent", explode)
        rc = pipeline.run_review(_options(git_repo, dry_run=True))
        assert rc == 0
        out = capsys.readouterr().out
        assert "selector prompt" in out
        assert not (git_repo / ".tmp-review").exists()


class TestRetry:
    def test_retry_then_success_accumulates_cost(self, git_repo, monkeypatch):
        state = pipeline.RunState(
            options=_options(git_repo),
            scope=None,  # unused by _run_with_retry
        )
        results = [
            backend.AgentResult(error="flaky", cost_usd=0.01),
            backend.AgentResult(output={"ok": True}, cost_usd=0.02),
        ]
        final = pipeline._run_with_retry(
            state, "review", "x", "sonnet", lambda: results.pop(0)
        )
        assert final.error is None
        assert [c.cost_usd for c in state.costs] == [0.01, 0.02]
        assert [c.retries for c in state.costs] == [0, 1]

    def test_denials_recorded_in_cost_entry(self, git_repo):
        state = pipeline.RunState(options=_options(git_repo), scope=None)
        denial = {"tool_name": "Bash", "tool_input": {"command": "touch x"}}
        result = backend.AgentResult(output={"ok": True}, cost_usd=0.01)
        result.permission_denials = [denial]
        final = pipeline._run_with_retry(
            state, "review", "x", "sonnet", lambda: result
        )
        assert final.error is None
        assert state.costs[0].denials == [denial]

    def test_local_schema_validation_triggers_retry(self, git_repo):
        state = pipeline.RunState(options=_options(git_repo), scope=None)
        schema = {"type": "object", "required": ["needed"]}
        results = [
            backend.AgentResult(output={"wrong": 1}, cost_usd=0.01),
            backend.AgentResult(output={"needed": 1}, cost_usd=0.01),
        ]
        final = pipeline._run_with_retry(
            state, "review", "x", "sonnet", lambda: results.pop(0), schema=schema
        )
        assert final.error is None
        assert final.output == {"needed": 1}
        assert len(state.costs) == 2


class TestStageCli:
    def test_nonzero_exit_raises_pipeline_error(self, tmp_path):
        state_cwd = str(tmp_path)
        try:
            pipeline.stage_cli("validate-findings.py", "/nonexistent.json", cwd=state_cwd)
        except pipeline.PipelineError as exc:
            assert "validate-findings.py failed" in str(exc)
        else:
            raise AssertionError("expected PipelineError")


class TestRevalidateRaw:
    def test_invalid_raw_file_removed_and_recorded(self, git_repo):
        state = pipeline.RunState(
            options=_options(git_repo), scope=None
        )
        raw = state.tmp_dir / "00-raw"
        raw.mkdir(parents=True)
        (raw / "implementation-full-scope.json").write_text('{"not": "agent output"}')
        pipeline._revalidate_raw(state)
        assert not (raw / "implementation-full-scope.json").exists()
        assert state.issues and state.issues[0]["kind"] == "validation_failed"


class TestLedgerOnFatal:
    def test_costs_written_when_stage_raises(self, git_repo, monkeypatch):
        calls = []
        monkeypatch.setattr(backend, "run_agent", _fake_run_agent_factory(calls))

        def boom(*args, **kwargs):
            raise pipeline.PipelineError("consolidator exploded")

        monkeypatch.setattr(pipeline, "stage_cli", boom)
        try:
            pipeline.run_review(_options(git_repo))
        except pipeline.PipelineError:
            pass
        else:
            raise AssertionError("expected PipelineError")
        costs = json.loads((git_repo / ".tmp-review" / "costs.json").read_text())
        assert costs["total_cost_usd"] > 0  # spend persisted despite fatal error


class TestMaxAgentsCapsLenses:
    def test_lens_count_trimmed_to_max_agents(self, git_repo, monkeypatch):
        calls = []
        monkeypatch.setattr(
            backend,
            "run_agent",
            _fake_run_agent_factory(calls, selector_response="fail"),  # all 7 lenses
        )
        rc = pipeline.run_review(_options(git_repo, max_agents=3))
        assert rc == 0
        lens_calls = [c for c in calls if "axis within the dimension" in c["prompt"]]
        assert len(lens_calls) == 3


class TestPartialFanOutFailure:
    def test_one_failed_lens_does_not_block_others(self, git_repo, monkeypatch):
        calls = []
        monkeypatch.setattr(
            backend,
            "run_agent",
            _fake_run_agent_factory(
                calls, selector_response="fail", fail_labels={"security"}
            ),
        )
        rc = pipeline.run_review(_options(git_repo))
        assert rc == 0
        findings = json.loads((git_repo / "Findings-review.json").read_text())
        assert len(findings["findings"]) >= 1  # survivors consolidated
        kinds = [i["kind"] for i in findings["issues"]]
        assert "subagent_failure" in kinds


class TestIssuesMergedOffsets:
    def test_no_duplicate_issues_across_two_merges(self, git_repo, monkeypatch):
        calls = []
        monkeypatch.setattr(
            backend,
            "run_agent",
            _fake_run_agent_factory(
                calls, fail_labels={"security"}, fail_validators=True,
                selector_response="fail",
            ),
        )
        rc = pipeline.run_review(_options(git_repo))
        assert rc == 0
        findings = json.loads((git_repo / "Findings-review.json").read_text())
        messages = [i["message"] for i in findings["issues"]]
        assert len(messages) == len(set(messages))  # merged once each
        assert any("security" in m for m in messages)
        assert any("validator" in m for m in messages)


class TestMultiDimensionFanOut:
    def test_two_dimensions_produce_two_raw_files(self, git_repo, monkeypatch):
        calls = []
        monkeypatch.setattr(
            backend,
            "run_agent",
            _fake_run_agent_factory(calls, selector_response="two-dims"),
        )
        rc = pipeline.run_review(_options(git_repo))
        assert rc == 0
        raw = git_repo / ".tmp-review" / "00-raw"
        # wiped-then-refilled by the run; findings JSON aggregates both dims
        findings = json.loads((git_repo / "Findings-review.json").read_text())
        dims = {d["dimension_slug"] for d in findings["decomposition"]}
        assert dims == {"core", "docs"}


class TestDenialAggregation:
    def test_denials_by_tool_in_costs(self, git_repo):
        state = pipeline.RunState(options=_options(git_repo), scope=None)
        state.tmp_dir.mkdir(exist_ok=True)
        denial = {"tool_name": "Bash", "tool_input": {"command": "git -C x diff"}}
        result = backend.AgentResult(output={"ok": True}, cost_usd=0.01)
        result.permission_denials = [denial, dict(denial)]
        pipeline._run_with_retry(state, "select", "x", "haiku", lambda: result)
        report = pipeline._write_costs(state)
        assert report["denials_by_tool"] == {"Bash": 2}

    def test_normalized_tokens_are_rolled_up(self, git_repo):
        state = pipeline.RunState(options=_options(git_repo), scope=None)
        state.tmp_dir.mkdir(exist_ok=True)
        result = backend.AgentResult(
            output={"ok": True},
            token_usage={
                "input_tokens": 100,
                "cache_read_input_tokens": 200,
                "cache_creation_input_tokens": 20,
                "output_tokens": 10,
            },
        )
        pipeline._run_with_retry(state, "select", "x", "haiku", lambda: result)
        report = pipeline._write_costs(state)
        assert report["total_normalized_tokens"] == 205.0
        assert report["normalized_tokens_by_stage"] == {"select/haiku": 205.0}


class TestSelectOnly:
    def test_select_only_saves_and_run_consumes(self, git_repo, monkeypatch, tmp_path, capsys):
        calls = []
        monkeypatch.setattr(backend, "run_agent", _fake_run_agent_factory(calls))
        selection_file = tmp_path / "sel.json"
        rc = pipeline.run_select_only(_options(git_repo), selection_file)
        assert rc == 0
        out = capsys.readouterr().out
        assert "lens: implementation:" in out
        assert selection_file.is_file()
        selector_calls = [c for c in calls if "Select which review lenses" in c["prompt"]]
        assert len(selector_calls) == 1

        saved_run_id = json.loads(selection_file.read_text())["run_id"]
        rc = pipeline.run_review(_options(git_repo), selection_file=selection_file)
        assert rc == 0
        selector_calls = [c for c in calls if "Select which review lenses" in c["prompt"]]
        assert len(selector_calls) == 1  # NOT re-run
        assert not selection_file.exists()  # consumed
        costs = json.loads((git_repo / ".tmp-review" / "costs.json").read_text())
        assert any(e["stage"] == "select" for e in costs["entries"])  # cost replayed
        assert costs["run_id"] == saved_run_id  # one run_id across both phases

    def test_stale_selection_ignored(self, git_repo, monkeypatch, tmp_path):
        calls = []
        monkeypatch.setattr(backend, "run_agent", _fake_run_agent_factory(calls))
        selection_file = tmp_path / "sel.json"
        selection_file.write_text(json.dumps({
            "head": "0" * 40, "selector_output": {"lenses": []}, "costs": [],
        }))
        rc = pipeline.run_review(_options(git_repo), selection_file=selection_file)
        assert rc == 0
        selector_calls = [c for c in calls if "Select which review lenses" in c["prompt"]]
        assert len(selector_calls) == 1  # re-ran due to stale head
        assert not selection_file.exists()


    def test_malformed_selection_file_tolerated(self, git_repo, monkeypatch, tmp_path):
        calls = []
        monkeypatch.setattr(backend, "run_agent", _fake_run_agent_factory(calls))
        selection_file = tmp_path / "sel.json"
        head = pipeline._head_sha(str(git_repo))
        selection_file.write_text(json.dumps({
            "head": head,
            "selector_output": ["not", "a", "dict"],
            "costs": [{"stage": "select", "label": "x", "model": "haiku",
                       "cost_usd": 0.01, "bogus_key": True}, "junk"],
        }))
        rc = pipeline.run_review(_options(git_repo), selection_file=selection_file)
        assert rc == 0  # non-dict selector_output -> selector re-ran; no crash
        costs = json.loads((git_repo / ".tmp-review" / "costs.json").read_text())
        replayed = [e for e in costs["entries"] if e["label"] == "x"]
        assert len(replayed) == 1  # valid keys replayed, bogus dropped


class TestValidationBuckets:
    """Which buckets reach the validators (pipeline._validation_buckets)."""

    def _stage(self, tmp_path, findings):
        stage = tmp_path / "10-merged"
        stage.mkdir()
        (stage / "_envelope.json").write_text(json.dumps({"issues": []}))
        for i, finding in enumerate(findings):
            (stage / f"hash{i}.json").write_text(json.dumps(finding))
        return stage

    def _finding(self, **overrides):
        base = {
            "content_hash": "abc123",
            "runtime_scope": "service-internal",
            "failure_mode": "degraded-behavior",
            "evidence_quality": "demonstrated",
            "trace_origin": "component",
        }
        base.update(overrides)
        return base

    def test_all_suggestions_promotes_suggestion_bucket(self, tmp_path):
        stage = self._stage(tmp_path, [self._finding(), self._finding()])
        assert pipeline._validation_buckets(stage) == "suggestion"

    def test_one_important_keeps_default(self, tmp_path):
        stage = self._stage(
            tmp_path,
            [self._finding(), self._finding(trace_origin="entry-point")],
        )
        assert pipeline._validation_buckets(stage) == "critical,important"

    def test_no_findings_keeps_default(self, tmp_path):
        assert pipeline._validation_buckets(self._stage(tmp_path, [])) == "critical,important"

    def test_unreadable_stage_dir_keeps_default(self, tmp_path):
        assert pipeline._validation_buckets(tmp_path / "absent") == "critical,important"


class TestOrchestratingSession:
    """The launching session is linked, never costed (pipeline.RunState)."""

    def _state(self, monkeypatch, session_id):
        if session_id is None:
            monkeypatch.delenv("CLAUDE_CODE_SESSION_ID", raising=False)
        else:
            monkeypatch.setenv("CLAUDE_CODE_SESSION_ID", session_id)
        return pipeline.RunState(options=_options("/tmp"), scope=None)

    def test_session_id_stamped_on_agents(self, monkeypatch):
        state = self._state(monkeypatch, "sess-abc")
        attrs = state.agent_attributes("lens", "security/full-scope")
        assert attrs["review.orchestrating_session_id"] == "sess-abc"
        assert attrs["review.run_id"] == state.run_id

    def test_absent_session_omits_attribute(self, monkeypatch):
        state = self._state(monkeypatch, None)
        assert "review.orchestrating_session_id" not in state.agent_attributes("lens", "x")

    def test_ledger_records_session_and_excludes_its_cost(self, monkeypatch, tmp_path):
        state = self._state(monkeypatch, "sess-abc")
        state.options.project_root = str(tmp_path)
        (tmp_path / ".tmp-review").mkdir()
        state.costs.append(
            pipeline.CostEntry(stage="lens", label="a", model="haiku", cost_usd=0.25)
        )
        report = pipeline._write_costs(state)
        assert report["orchestrating_session_id"] == "sess-abc"
        # Only agent spend is summed; the session's own cost is unknowable here.
        assert report["total_cost_usd"] == 0.25

    def test_ledger_null_when_not_launched_by_a_session(self, monkeypatch, tmp_path):
        state = self._state(monkeypatch, None)
        state.options.project_root = str(tmp_path)
        (tmp_path / ".tmp-review").mkdir()
        report = pipeline._write_costs(state)
        assert report["orchestrating_session_id"] is None


class TestBudgetHarvest:
    """A budget stop is never retried — retrying a runaway runs it away
    again at full price. Its session is reopened once instead, to take
    whatever it had already established."""

    def _state(self, git_repo):
        return pipeline.RunState(
            options=_options(git_repo),
            scope=pipeline.scope_mod.ReviewScope(
                project_root=str(git_repo),
                project_name="p",
                default_branch="origin/main",
                language="python",
                build_system="make",
                test_framework="pytest",
            ),
        )

    def _budget_stop(self, session_id="sess-budget"):
        return backend.AgentResult(
            error="budget exhausted: Reached maximum budget ($6)",
            error_category="budget",
            cost_usd=6.07,
            session_id=session_id,
        )

    def test_budget_stop_is_not_retried(self, git_repo):
        state = self._state(git_repo)
        attempts = []

        def fn():
            attempts.append(1)
            return self._budget_stop()

        pipeline._run_with_retry(state, "review", "impl/full-scope", "sonnet", fn)
        assert len(attempts) == 1, "a runaway must not be re-run at full price"

    def test_harvest_reopens_the_stopped_session(self, git_repo):
        state = self._state(git_repo)
        resumed = []

        def harvest(session_id):
            resumed.append(session_id)
            return backend.AgentResult(
                output={"findings": []}, cost_usd=0.4, session_id=session_id
            )

        result = pipeline._run_with_retry(
            state,
            "review",
            "impl/full-scope",
            "sonnet",
            lambda: self._budget_stop("sess-abc"),
            harvest=harvest,
        )
        assert resumed == ["sess-abc"]
        assert result.output == {"findings": []}, "salvaged output is returned"

    def test_harvest_cost_is_ledgered_separately(self, git_repo):
        state = self._state(git_repo)
        pipeline._run_with_retry(
            state,
            "review",
            "impl/full-scope",
            "sonnet",
            lambda: self._budget_stop(),
            harvest=lambda sid: backend.AgentResult(output={"ok": 1}, cost_usd=0.4),
        )
        labels = [c.label for c in state.costs]
        assert labels == ["impl/full-scope", "impl/full-scope (harvest)"]
        # The stopped run's spend is real and reported, unlike a SIGKILL.
        assert [c.cost_usd for c in state.costs] == [6.07, 0.4]
        assert state.costs[0].error_category == "budget"

    def test_harvest_records_an_issue_so_partial_output_is_disclosed(self, git_repo):
        state = self._state(git_repo)
        pipeline._run_with_retry(
            state,
            "review",
            "impl/full-scope",
            "sonnet",
            lambda: self._budget_stop(),
            harvest=lambda sid: backend.AgentResult(output={"ok": 1}, cost_usd=0.4),
        )
        assert any(
            i["kind"] == "subagent_failure" and "harvested" in i["message"]
            for i in state.issues
        ), "silently shipping partial findings as complete would be worse"

    def test_failed_harvest_falls_back_to_the_budget_stop(self, git_repo):
        state = self._state(git_repo)
        result = pipeline._run_with_retry(
            state,
            "review",
            "impl/full-scope",
            "sonnet",
            lambda: self._budget_stop(),
            harvest=lambda sid: backend.AgentResult(
                error="resume failed", error_category="agent"
            ),
        )
        assert result.error is not None
        assert result.output is None
        assert not state.issues, "no harvest claim when nothing was harvested"

    def test_no_session_id_means_no_harvest_attempt(self, git_repo):
        state = self._state(git_repo)
        called = []
        result = pipeline._run_with_retry(
            state,
            "review",
            "impl/full-scope",
            "sonnet",
            lambda: self._budget_stop(session_id=""),
            harvest=lambda sid: called.append(sid),
        )
        assert called == [], "cannot resume a session with no id"
        assert result.error is not None

    def test_other_categories_still_retry(self, git_repo):
        state = self._state(git_repo)
        attempts = []

        def fn():
            attempts.append(1)
            return backend.AgentResult(error="bad json", error_category="protocol")

        pipeline._run_with_retry(state, "review", "impl/full-scope", "sonnet", fn)
        assert len(attempts) == 3, "schema/protocol flukes are worth an identical retry"


class TestBudgetByModel:
    def test_sonnet_and_haiku_differ(self):
        assert pipeline.budget_for("sonnet") == 6.0
        assert pipeline.budget_for("haiku") == 2.0

    def test_unknown_model_gets_the_default(self):
        assert pipeline.budget_for("some-future-model") == pipeline.DEFAULT_BUDGET_USD


class TestAgentLogsExist:
    def test_lens_agents_get_budget_session_and_debug_file(self, git_repo, monkeypatch):
        calls = []
        monkeypatch.setattr(backend, "run_agent", _fake_run_agent_factory(calls))
        assert pipeline.run_review(_options(git_repo)) == 0
        lens_calls = [c for c in calls if "axis within the dimension" in c["prompt"]]
        assert lens_calls
        for call in lens_calls:
            assert call["max_budget_usd"] == pipeline.budget_for(call["model"])
            assert call["session_id"], "chosen up front, not read back"
            assert call["persist_session"] is True, "required for harvest"
            assert str(call["debug_file"]).endswith(".log")

    def test_log_dir_is_created_by_bootstrap(self, git_repo, monkeypatch):
        monkeypatch.setattr(backend, "run_agent", _fake_run_agent_factory([]))
        assert pipeline.run_review(_options(git_repo)) == 0
        assert (git_repo / ".tmp-review" / pipeline.LOG_DIRNAME).is_dir()


def _steps(report) -> dict:
    """step name -> status, for the assertions below."""
    return {step["step"]: step["status"] for step in report["steps"]}


class TestRunReport:
    """The run report answers 'what ran and what failed' without mining logs.

    Every assertion here is about a stage that used to lose work silently:
    a skipped validator batch, a selector fallback, an excluded raw file.
    """

    def test_clean_run_reports_every_step_ok(self, git_repo, monkeypatch):
        monkeypatch.setattr(backend, "run_agent", _fake_run_agent_factory([]))
        assert pipeline.run_review(_options(git_repo)) == 0

        findings = json.loads((git_repo / "Findings-review.json").read_text())
        report = findings["run_report"]
        assert report["status"] == "ok"
        assert report["run_id"] == findings["run_id"]
        assert report["harness"] == "claude"
        statuses = _steps(report)
        assert statuses["scope"] == "ok"
        assert statuses["select"] == "ok"
        assert statuses["review"] == "ok"
        assert statuses["validate"] == "ok"
        assert statuses["consolidate"] == "ok"
        assert statuses["apply-verdicts"] == "ok"
        # Full-repo review has no merge base to filter against.
        assert statuses["diff-scope-filter"] == "skipped"

    def test_report_lands_in_costs_and_tmp_dir_too(self, git_repo, monkeypatch):
        monkeypatch.setattr(backend, "run_agent", _fake_run_agent_factory([]))
        assert pipeline.run_review(_options(git_repo)) == 0

        tmp = git_repo / ".tmp-review"
        standalone = json.loads((tmp / pipeline.RUN_REPORT_FILENAME).read_text())
        costs = json.loads((tmp / "costs.json").read_text())
        embedded = json.loads((git_repo / "Findings-review.json").read_text())
        assert standalone["steps"] == embedded["run_report"]["steps"]
        assert costs["steps"] == standalone["steps"]

    def test_failed_validator_batch_degrades_the_run(self, git_repo, monkeypatch):
        monkeypatch.setattr(
            backend,
            "run_agent",
            _fake_run_agent_factory([], fail_validators=True),
        )
        assert pipeline.run_review(_options(git_repo)) == 0

        findings = json.loads((git_repo / "Findings-review.json").read_text())
        report = findings["run_report"]
        # Degraded, not failed: apply-verdicts.py passes an unvalidated
        # batch through, so the run still produced findings.
        assert report["status"] == "degraded"
        assert _steps(report)["validate"] == "degraded"
        validate_step = next(
            s for s in report["steps"] if s["step"] == "validate"
        )
        assert "validator-batch-1" in validate_step["detail"]
        # The consequence is stated, not left for the reader to infer.
        messages = " ".join(issue["message"] for issue in findings["issues"])
        assert "never adversarially validated" in messages

    def test_selector_fallback_is_a_degraded_step(self, git_repo, monkeypatch):
        monkeypatch.setattr(
            backend,
            "run_agent",
            _fake_run_agent_factory([], selector_response="fail"),
        )
        assert pipeline.run_review(_options(git_repo)) == 0

        report = json.loads((git_repo / "Findings-review.json").read_text())["run_report"]
        assert _steps(report)["select"] == "degraded"
        assert report["status"] == "degraded"

    def test_partial_lens_failure_degrades_the_review_step(self, git_repo, monkeypatch):
        monkeypatch.setattr(
            backend,
            "run_agent",
            _fake_run_agent_factory(
                [], selector_response="fail", fail_labels={"security"}
            ),
        )
        assert pipeline.run_review(_options(git_repo)) == 0

        report = json.loads((git_repo / "Findings-review.json").read_text())["run_report"]
        review_step = next(s for s in report["steps"] if s["step"] == "review")
        assert review_step["status"] == "degraded"
        assert "security/full-scope" in review_step["detail"]

    def test_total_lens_failure_reports_failed_and_writes_the_report(
        self, git_repo, monkeypatch, capsys
    ):
        """The run that produces no findings file still produces a report."""
        monkeypatch.setattr(
            backend,
            "run_agent",
            _fake_run_agent_factory([], fail_labels={"implementation"}),
        )
        assert pipeline.run_review(_options(git_repo)) == 1
        assert not (git_repo / "Findings-review.json").exists()

        report = json.loads(
            (git_repo / ".tmp-review" / pipeline.RUN_REPORT_FILENAME).read_text()
        )
        assert report["status"] == "failed"
        assert _steps(report)["review"] == "failed"
        assert "Run report (failed)" in capsys.readouterr().out

    def test_stage_cli_failure_names_the_step_in_the_report(self, git_repo, monkeypatch):
        """A fatal deterministic stage still records which one ended the run."""
        monkeypatch.setattr(backend, "run_agent", _fake_run_agent_factory([]))
        real_stage_cli = pipeline.stage_cli

        def failing_stage_cli(script_name, *args, **kwargs):
            if script_name == "batch-findings.py":
                kwargs.pop("detail", None)
                return real_stage_cli(
                    script_name, "--input-dir", "./does-not-exist/", *args[4:], **kwargs
                )
            return real_stage_cli(script_name, *args, **kwargs)

        monkeypatch.setattr(pipeline, "stage_cli", failing_stage_cli)
        try:
            pipeline.run_review(_options(git_repo))
        except pipeline.PipelineError:
            pass
        report = json.loads(
            (git_repo / ".tmp-review" / pipeline.RUN_REPORT_FILENAME).read_text()
        )
        assert _steps(report)["batch"] == "failed"
        assert report["status"] == "failed"

    def test_unknown_status_is_rejected(self, git_repo):
        state = pipeline.RunState(
            options=_options(git_repo), scope=None  # scope unused by record_step
        )
        try:
            state.record_step("review", "mostly-fine")
        except ValueError as exc:
            assert "mostly-fine" in str(exc)
        else:
            raise AssertionError("expected ValueError for an unknown status")


class TestIntentEndToEnd:
    """Intent travels from Options to the agents and to a durable artifact.

    The absent case matters as much as the present one: a review that
    inferred the code's purpose from the code has to say so, or it reads
    exactly like one that was told the purpose.
    """

    INTENT = "AC1: deleting a workspace must not delete its runs."

    def test_intent_reaches_agents_and_artifacts(self, git_repo, monkeypatch):
        calls = []
        monkeypatch.setattr(backend, "run_agent", _fake_run_agent_factory(calls))
        assert pipeline.run_review(_options(git_repo, intent=self.INTENT)) == 0

        # Selector and lens agents were both told why the code exists.
        selector = next(c for c in calls if "Select which review lenses" in c["prompt"])
        lens = next(c for c in calls if "LENS SCOPE:" in c["prompt"])
        for call in (selector, lens):
            assert self.INTENT in call["prompt"]

        findings = json.loads((git_repo / "Findings-review.json").read_text())
        assert findings["intent"] == self.INTENT
        assert _steps(findings["run_report"])["intent"] == "ok"

        # The run directory keeps the input, next to costs.json.
        assert (git_repo / ".tmp-review" / pipeline.INTENT_FILENAME).read_text() == self.INTENT
        intent_md = (git_repo / "Findings-intent.md").read_text()
        assert self.INTENT in intent_md

    def test_missing_intent_is_reported_not_hidden(self, git_repo, monkeypatch):
        monkeypatch.setattr(backend, "run_agent", _fake_run_agent_factory([]))
        assert pipeline.run_review(_options(git_repo)) == 0

        findings = json.loads((git_repo / "Findings-review.json").read_text())
        assert "intent" not in findings
        assert _steps(findings["run_report"])["intent"] == "skipped"
        assert not (git_repo / ".tmp-review" / pipeline.INTENT_FILENAME).exists()
        assert "No intent was supplied" in (git_repo / "Findings-intent.md").read_text()
