# Generated By: Claude Code (Claude Fable 5)
"""Tests for orchestrator/backend.py — the agent seam."""

import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO_ROOT))
from orchestrator import backend  # noqa: E402


def _cli_result(**overrides):
    result = {
        "is_error": False,
        "total_cost_usd": 0.0123,
        "permission_denials": [],
        "result": "raw text",
        "structured_output": {"ok": True},
    }
    result.update(overrides)
    return result


class _FakeProc:
    """Stands in for subprocess.Popen of the claude CLI."""

    def __init__(self, stdout, returncode=0, stderr=""):
        self._stdout = stdout
        self.returncode = returncode
        self._stderr = stderr
        self.pid = 12345

    def communicate(self, input=None, timeout=None):
        if isinstance(self._stdout, Exception):
            raise self._stdout
        return self._stdout, self._stderr

    def wait(self):
        return self.returncode


def _patch_run(monkeypatch, response, capture=None):
    def fake_popen(argv, **kwargs):
        if capture is not None:
            capture["argv"] = argv
            capture["kwargs"] = kwargs
        if isinstance(response, subprocess.TimeoutExpired):
            return _FakeProc(response)
        if isinstance(response, Exception):
            raise response
        return response

    monkeypatch.setattr(subprocess, "Popen", fake_popen)
    monkeypatch.setattr("os.killpg", lambda pid, sig: None)


class TestArgvConstruction:
    def test_full_argv(self, monkeypatch):
        capture = {}
        _patch_run(monkeypatch, _FakeProc(json.dumps(_cli_result())), capture)
        backend.run_agent(
            "the prompt",
            schema={"type": "object"},
            model="sonnet",
            allowed_tools=["Read", "Grep"],
            tools="Read,Grep",
            cwd="/tmp",
            effort="low",
            timeout_s=42,
        )
        argv = capture["argv"]
        assert argv[:2] == ["claude", "-p"]
        assert "the prompt" not in argv  # prompt rides stdin
        assert argv[argv.index("--tools") + 1] == "Read,Grep"
        assert argv[argv.index("--permission-mode") + 1] == "dontAsk"
        assert "--output-format" in argv and argv[argv.index("--output-format") + 1] == "json"
        assert "--no-session-persistence" in argv
        assert "--bare" not in argv
        assert argv[argv.index("--model") + 1] == "sonnet"
        assert argv[argv.index("--effort") + 1] == "low"
        assert argv[argv.index("--allowedTools") + 1] == "Read,Grep"
        assert json.loads(argv[argv.index("--json-schema") + 1]) == {"type": "object"}
        assert capture["kwargs"]["cwd"] == "/tmp"

    def test_no_schema_omits_json_schema_flag(self, monkeypatch):
        capture = {}
        _patch_run(monkeypatch, _FakeProc(json.dumps(_cli_result())), capture)
        backend.run_agent(
            "p", schema=None, model="haiku", allowed_tools=[], cwd="/tmp"
        )
        assert "--json-schema" not in capture["argv"]
        assert "--allowedTools" not in capture["argv"]
        assert "--tools" not in capture["argv"]

    def test_env_scrubbed_of_claude_vars(self, monkeypatch):
        capture = {}
        monkeypatch.setenv("CLAUDECODE", "1")
        monkeypatch.setenv("CLAUDE_CODE_ENTRYPOINT", "cli")
        monkeypatch.setenv("CLAUDE_CODE_SESSION_ID", "abc")
        monkeypatch.setenv("CLAUDE_CODE_ENABLE_TELEMETRY", "1")
        monkeypatch.setenv("CLAUDE_CODE_ENHANCED_TELEMETRY_BETA", "1")
        monkeypatch.setenv("OTEL_EXPORTER_OTLP_ENDPOINT", "http://collector:4318")
        monkeypatch.setenv("HOME", "/home/x")
        _patch_run(monkeypatch, _FakeProc(json.dumps(_cli_result())), capture)
        backend.run_agent("p", schema=None, model="haiku", allowed_tools=[], cwd="/tmp")
        env = capture["kwargs"]["env"]
        # Session identity stripped
        assert "CLAUDECODE" not in env
        assert "CLAUDE_CODE_ENTRYPOINT" not in env
        assert "CLAUDE_CODE_SESSION_ID" not in env
        # Telemetry config preserved
        assert env["CLAUDE_CODE_ENABLE_TELEMETRY"] == "1"
        assert env["CLAUDE_CODE_ENHANCED_TELEMETRY_BETA"] == "1"
        assert env["OTEL_EXPORTER_OTLP_ENDPOINT"] == "http://collector:4318"
        assert env["HOME"] == "/home/x"


class TestResultParsing:
    def test_success_with_schema(self, monkeypatch):
        _patch_run(monkeypatch, _FakeProc(json.dumps(_cli_result())))
        res = backend.run_agent(
            "p", schema={"type": "object"}, model="sonnet", allowed_tools=[], cwd="/tmp"
        )
        assert res.error is None
        assert res.output == {"ok": True}
        assert res.cost_usd == 0.0123
        assert res.permission_denials == []

    def test_success_without_schema_returns_text(self, monkeypatch):
        _patch_run(monkeypatch, _FakeProc(json.dumps(_cli_result())))
        res = backend.run_agent(
            "p", schema=None, model="haiku", allowed_tools=[], cwd="/tmp"
        )
        assert res.output == {"text": "raw text"}

    def test_is_error_sets_error_but_keeps_cost(self, monkeypatch):
        _patch_run(
            monkeypatch,
            _FakeProc(json.dumps(_cli_result(is_error=True, result="boom"))),
        )
        res = backend.run_agent(
            "p", schema={"type": "object"}, model="sonnet", allowed_tools=[], cwd="/tmp"
        )
        assert res.error is not None and "boom" in res.error
        assert res.output is None
        assert res.cost_usd == 0.0123

    def test_missing_structured_output_is_error(self, monkeypatch):
        _patch_run(
            monkeypatch,
            _FakeProc(json.dumps(_cli_result(structured_output=None))),
        )
        res = backend.run_agent(
            "p", schema={"type": "object"}, model="sonnet", allowed_tools=[], cwd="/tmp"
        )
        assert res.error == "missing structured_output in result"

    def test_non_json_stdout(self, monkeypatch):
        _patch_run(monkeypatch, _FakeProc("garbage", returncode=1, stderr="bad"))
        res = backend.run_agent(
            "p", schema=None, model="haiku", allowed_tools=[], cwd="/tmp"
        )
        assert "malformed CLI result" in res.error

    def test_timeout(self, monkeypatch):
        _patch_run(
            monkeypatch, subprocess.TimeoutExpired(cmd=["claude"], timeout=5)
        )
        res = backend.run_agent(
            "p", schema=None, model="haiku", allowed_tools=[], cwd="/tmp", timeout_s=5
        )
        assert "timeout" in res.error

    def test_spawn_failure(self, monkeypatch):
        _patch_run(monkeypatch, FileNotFoundError("no claude"))
        res = backend.run_agent(
            "p", schema=None, model="haiku", allowed_tools=[], cwd="/tmp"
        )
        assert "failed to spawn" in res.error

    def test_permission_denials_surface(self, monkeypatch):
        denial = {"tool_name": "Bash", "tool_input": {"command": "git diff"}}
        _patch_run(
            monkeypatch,
            _FakeProc(json.dumps(_cli_result(permission_denials=[denial]))),
        )
        res = backend.run_agent(
            "p", schema=None, model="haiku", allowed_tools=["Read"], cwd="/tmp"
        )
        assert res.permission_denials == [denial]


class TestLoadResolvedSchema:
    def test_strips_generated_marker(self):
        schema = backend.load_resolved_schema("agent-output")
        assert "_generated" not in schema
        assert schema["type"] == "object"
        assert "findings" in schema["properties"]

    def test_no_root_composition(self):
        # --json-schema rejects root-level composition like StructuredOutput.
        for name in ("agent-output", "validation-output"):
            schema = backend.load_resolved_schema(name)
            for keyword in ("allOf", "anyOf", "oneOf"):
                assert keyword not in schema, f"{name} has root {keyword}"


class TestAgentTrace:
    def test_trace_line_written_on_success(self, monkeypatch, tmp_path):
        import json as _json

        _patch_run(monkeypatch, _FakeProc(_json.dumps(_cli_result())))
        trace = tmp_path / "agent-trace.jsonl"
        backend.run_agent(
            "the prompt",
            schema={"type": "object"},
            model="sonnet",
            allowed_tools=["Read"],
            cwd="/tmp",
            trace_file=trace,
            label="impl/full-scope",
        )
        lines = trace.read_text().strip().splitlines()
        assert len(lines) == 1
        record = _json.loads(lines[0])
        assert record["label"] == "impl/full-scope"
        assert record["prompt"] == "the prompt"
        assert record["error"] is None
        assert record["cost_usd"] == 0.0123
        assert record["result"]["structured_output"] == {"ok": True}
        assert record["elapsed_s"] >= 0

    def test_trace_line_written_on_failure_and_appends(self, monkeypatch, tmp_path):
        import json as _json

        trace = tmp_path / "agent-trace.jsonl"
        _patch_run(monkeypatch, _FakeProc("garbage", returncode=1, stderr="bad"))
        backend.run_agent(
            "p", schema=None, model="haiku", allowed_tools=[], cwd="/tmp",
            trace_file=trace, label="a",
        )
        _patch_run(monkeypatch, subprocess.TimeoutExpired(cmd=["claude"], timeout=5))
        backend.run_agent(
            "p", schema=None, model="haiku", allowed_tools=[], cwd="/tmp",
            trace_file=trace, label="b", timeout_s=5,
        )
        records = [_json.loads(x) for x in trace.read_text().strip().splitlines()]
        assert len(records) == 2
        assert "malformed CLI result" in records[0]["error"]
        assert records[0]["result"]["stderr"] == "bad"
        assert "timeout" in records[1]["error"]

    def test_no_trace_file_means_no_write(self, monkeypatch, tmp_path):
        import json as _json

        _patch_run(monkeypatch, _FakeProc(_json.dumps(_cli_result())))
        backend.run_agent(
            "p", schema=None, model="haiku", allowed_tools=[], cwd="/tmp"
        )
        assert list(tmp_path.iterdir()) == []


class TestRedactPrompt:
    def test_guidance_block_redacted_until_next_section(self):
        prompt = (
            "PROJECT CONTEXT:\n- Language: Python\n\n"
            "USER GUIDANCE:\nsecret focus area\nwith a second line\n\n"
            "METHODOLOGY:\nPhase 1\n"
        )
        redacted = backend.redact_prompt(prompt)
        assert "secret focus area" not in redacted
        assert "second line" not in redacted
        assert "[guidance redacted from trace]" in redacted
        assert "METHODOLOGY:" in redacted
        assert "- Language: Python" in redacted

    def test_no_guidance_is_passthrough(self):
        prompt = "PROJECT CONTEXT:\nno guidance here\n"
        assert backend.redact_prompt(prompt) == prompt

    def test_trace_stores_redacted_prompt(self, monkeypatch, tmp_path):
        _patch_run(monkeypatch, _FakeProc(json.dumps(_cli_result())))
        trace = tmp_path / "trace.jsonl"
        backend.run_agent(
            "USER GUIDANCE:\ntopsecret\n\nMETHODOLOGY:\ngo",
            schema=None, model="haiku", allowed_tools=[], cwd="/tmp",
            trace_file=trace, label="x",
        )
        content = trace.read_text()
        assert "topsecret" not in content
        assert (trace.stat().st_mode & 0o777) == 0o600


class TestErrorCategories:
    def test_timeout_category(self, monkeypatch):
        _patch_run(monkeypatch, subprocess.TimeoutExpired(cmd=["claude"], timeout=5))
        res = backend.run_agent(
            "p", schema=None, model="haiku", allowed_tools=[], cwd="/tmp", timeout_s=5
        )
        assert res.error_category == "timeout"

    def test_spawn_category(self, monkeypatch):
        _patch_run(monkeypatch, FileNotFoundError("no claude"))
        res = backend.run_agent("p", schema=None, model="haiku", allowed_tools=[], cwd="/tmp")
        assert res.error_category == "spawn"

    def test_agent_error_category(self, monkeypatch):
        _patch_run(monkeypatch, _FakeProc(json.dumps(_cli_result(is_error=True))))
        res = backend.run_agent("p", schema=None, model="haiku", allowed_tools=[], cwd="/tmp")
        assert res.error_category == "agent"


class TestRoundTwoFixes:
    def test_allowed_tools_with_internal_space_survive_join(self, monkeypatch):
        capture = {}
        _patch_run(monkeypatch, _FakeProc(json.dumps(_cli_result())), capture)
        backend.run_agent(
            "p", schema=None, model="haiku",
            allowed_tools=["Read", "Bash(git diff:*)", "Bash(git log:*)"],
            cwd="/tmp",
        )
        argv = capture["argv"]
        joined = argv[argv.index("--allowedTools") + 1]
        assert joined == "Read,Bash(git diff:*),Bash(git log:*)"
        assert " " not in joined.replace("git diff", "").replace("git log", "")

    def test_trace_write_failure_warns(self, monkeypatch, tmp_path, capsys):
        _patch_run(monkeypatch, _FakeProc(json.dumps(_cli_result())))
        unwritable = tmp_path / "nodir" / "trace.jsonl"  # parent missing
        res = backend.run_agent(
            "p", schema=None, model="haiku", allowed_tools=[], cwd="/tmp",
            trace_file=unwritable, label="x",
        )
        assert res.error is None  # tracing failure never fails the run
        assert "trace write failed" in capsys.readouterr().err

    def test_redaction_survives_allcaps_inside_guidance(self):
        prompt = (
            "USER GUIDANCE:\nfocus here\nNOTE:\nstill secret\n\n"
            "METHODOLOGY:\nPhase 1\n"
        )
        redacted = backend.redact_prompt(prompt)
        assert "still secret" not in redacted
        assert "focus here" not in redacted
        assert "METHODOLOGY:" in redacted


class TestMalformedResults:
    def test_non_dict_json_result_is_protocol_error(self, monkeypatch):
        _patch_run(monkeypatch, _FakeProc('["not", "a", "dict"]'))
        res = backend.run_agent("p", schema=None, model="haiku", allowed_tools=[], cwd="/tmp")
        assert res.error_category == "protocol"
        assert "malformed CLI result" in res.error

    def test_junk_cost_value_tolerated(self, monkeypatch):
        _patch_run(monkeypatch, _FakeProc(json.dumps(_cli_result(total_cost_usd="junk"))))
        res = backend.run_agent("p", schema=None, model="haiku", allowed_tools=[], cwd="/tmp")
        assert res.error is None
        assert res.cost_usd == 0.0

    def test_prompt_goes_via_stdin_not_argv(self, monkeypatch):
        capture = {}
        _patch_run(monkeypatch, _FakeProc(json.dumps(_cli_result())), capture)
        backend.run_agent("the secret prompt", schema=None, model="haiku", allowed_tools=[], cwd="/tmp")
        assert "the secret prompt" not in capture["argv"]
        assert capture["kwargs"]["stdin"] is not None
