# Generated By: Claude Code (Claude Fable 5)
"""Tests for orchestrator/simple_mode.py plus a simple-mode end-to-end run."""

import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO_ROOT))
from orchestrator import backend, pipeline, simple_mode  # noqa: E402


def _simple_output(concern_slug, findings, dimension_slug="full-scope"):
    concern_names = {
        "implementation": "Implementation Quality",
        "security": "Security",
    }
    return {
        "agent_id": f"{concern_slug}/{dimension_slug}",
        "concern": concern_names[concern_slug],
        "concern_slug": concern_slug,
        "dimension_name": "full scope",
        "dimension_slug": dimension_slug,
        "dimension_scope": {},
        "findings": findings,
    }


def _finding(title, severity="important", confidence="high", path="app.py", line="1"):
    return {
        "title": title,
        "severity": severity,
        "confidence": confidence,
        "locations": [{"path": path, "line": line, "role": "primary"}],
        "issue": "issue text",
        "why_it_matters": "matters",
        "suggested_fix": "fix it",
    }


class TestCollectFindings:
    def test_dedup_keeps_more_severe(self, tmp_path):
        raw = tmp_path / "00-raw"
        raw.mkdir()
        (raw / "implementation-full-scope.json").write_text(
            json.dumps(
                _simple_output(
                    "implementation",
                    [_finding("dup A", severity="suggestion", confidence="low")],
                )
            )
        )
        (raw / "security-full-scope.json").write_text(
            json.dumps(
                _simple_output(
                    "security",
                    [_finding("other B", severity="critical", path="app.py", line="9")],
                )
            )
        )
        findings, decomposition, _ = simple_mode.collect_findings(raw)
        assert len(findings) == 2  # different concern_slug => different keys
        assert {d["dimension_slug"] for d in decomposition} == {"full-scope"}
        assert all(re.fullmatch(r"[a-f0-9]{16}", f["content_hash"]) for f in findings)

    def test_observations_collected_and_deduped(self, tmp_path):
        raw = tmp_path / "00-raw"
        raw.mkdir()
        out = _simple_output("implementation", [_finding("f")])
        out["cross_cutting_observations"] = ["Note 1", "Note 1", ""]
        (raw / "implementation-full-scope.json").write_text(json.dumps(out))
        _, _, observations = simple_mode.collect_findings(raw)
        assert observations == [
            {"agent": "implementation/full-scope", "text": "Note 1"}
        ]

    def test_same_concern_same_location_merges(self, tmp_path):
        raw = tmp_path / "00-raw"
        raw.mkdir()
        f1 = _finding("dup A", severity="suggestion")
        f2 = _finding("dup A again", severity="critical")
        f2["locations"].append({"path": "b.py", "line": "2", "role": "related"})
        (raw / "implementation-full-scope.json").write_text(
            json.dumps(_simple_output("implementation", [f1, f2]))
        )
        findings, _, _ = simple_mode.collect_findings(raw)
        assert len(findings) == 1
        assert findings[0]["severity"] == "critical"
        assert len(findings[0]["locations"]) == 2


class TestApplyVerdicts:
    def _setup(self, tmp_path, verdicts):
        vdir = tmp_path / "15-validation"
        vdir.mkdir()
        (vdir / "batch-1-output.json").write_text(
            json.dumps({"batch_number": 1, "verdicts": verdicts})
        )
        return vdir

    def test_confirm_rescore_remove_and_passthrough(self, tmp_path):
        findings = []
        for i, title in enumerate(["keep", "rescore", "drop", "noverdict"]):
            f = _finding(title, line=str(i + 1))
            f["concern_slug"] = "implementation"
            f["content_hash"] = f"{i:016x}"
            findings.append(f)
        vdir = self._setup(
            tmp_path,
            [
                {"finding_ref": {"content_hash": findings[0]["content_hash"]}, "action": "confirm", "reasoning": "ok"},
                {"finding_ref": {"content_hash": findings[1]["content_hash"]}, "action": "rescore", "new_severity": "suggestion", "reasoning": "overstated"},
                {"finding_ref": {"content_hash": findings[2]["content_hash"]}, "action": "remove", "remove_reason": "not_real", "reasoning": "premise invalid"},
            ],
        )
        survivors, issues = simple_mode.apply_verdicts(vdir, findings)
        titles = [f["title"] for f in survivors]
        assert titles == ["keep", "rescore", "noverdict"]
        assert survivors[1]["severity"] == "suggestion"
        assert len(issues) == 1
        assert "validator_removed[not_real]" in issues[0]["message"]


def _fake_simple_backend(calls):
    def fake_run_agent(prompt, *, schema, model, allowed_tools, cwd, tools=None, effort=None, timeout_s=600, trace_file=None, label="", redact=None, otel_attributes=None):
        calls.append(prompt)
        if "Select which review lenses" in prompt:
            return backend.AgentResult(
                output={
                    "lenses": [{"name": "implementation", "rationale": "always"}],
                },
                cost_usd=0.001,
            )
        if "validator agent" in prompt:
            hashes = re.findall(r"content_hash: ([a-f0-9]{16,64})", prompt)
            return backend.AgentResult(
                output={
                    "batch_number": 1,
                    "verdicts": [
                        {"finding_ref": {"content_hash": h}, "action": "confirm", "reasoning": "ok"}
                        for h in hashes
                    ],
                },
                cost_usd=0.002,
            )
        return backend.AgentResult(
            output=_simple_output(
                "implementation",
                [
                    _finding("real bug", severity="critical", confidence="high"),
                    _finding("hunch", severity="suggestion", confidence="low", line="2"),
                ],
            ),
            cost_usd=0.01,
        )

    return fake_run_agent


class TestSimpleEndToEnd:
    def test_full_run(self, git_repo, monkeypatch):
        calls = []
        monkeypatch.setattr(backend, "run_agent", _fake_simple_backend(calls))
        options = pipeline.Options(
            project_root=str(git_repo), scoring="simple", parallel=2, timeout_s=30
        )
        rc = pipeline.run_review(options)
        assert rc == 0

        envelope = json.loads((git_repo / "Findings-review.json").read_text())
        assert envelope["scoring"] == "simple"
        by_severity = {f["severity"]: f for f in envelope["findings"]}
        assert by_severity["critical"]["confidence"] == "high"
        # low confidence renders into needs-review
        assert by_severity["needs-review"]["title"] == "hunch"
        # simple prompts were used
        lens_prompts = [c for c in calls if "axis within the dimension" in c]
        assert lens_prompts and all("_justification" not in c for c in lens_prompts)
        # validator saw the simple finding block
        validator_prompts = [c for c in calls if "validator agent" in c]
        assert validator_prompts and "severity: critical" in validator_prompts[0]


class TestWriteBatches:
    def test_only_critical_important_batched_in_chunks(self, tmp_path):
        vdir = tmp_path / "15-validation"
        vdir.mkdir()
        findings = []
        for i in range(10):
            f = _finding(f"crit {i}", severity="critical", line=str(i + 1))
            f["concern_slug"] = "implementation"
            f["content_hash"] = f"{i:016x}"
            findings.append(f)
        low = _finding("sugg", severity="suggestion", line="99")
        low["concern_slug"] = "implementation"
        low["content_hash"] = "f" * 16
        findings.append(low)
        count = simple_mode.write_batches(vdir, findings)
        assert count == 2  # 10 critical / batch size 8
        batch1 = json.loads((vdir / "batch-1-input.json").read_text())
        batch2 = json.loads((vdir / "batch-2-input.json").read_text())
        assert len(batch1["findings"]) == 8
        assert len(batch2["findings"]) == 2
        assert batch1["total_batches"] == 2
        titles = [f["title"] for f in batch1["findings"] + batch2["findings"]]
        assert "sugg" not in titles

    def test_verdicts_merged_across_batch_files(self, tmp_path):
        vdir = tmp_path / "15-validation"
        vdir.mkdir()
        f1 = _finding("a", line="1"); f1["concern_slug"] = "implementation"; f1["content_hash"] = "a" * 16
        f2 = _finding("b", line="2"); f2["concern_slug"] = "implementation"; f2["content_hash"] = "b" * 16
        (vdir / "batch-1-output.json").write_text(json.dumps({
            "batch_number": 1,
            "verdicts": [{"finding_ref": {"content_hash": "a" * 16}, "action": "remove", "remove_reason": "not_real", "reasoning": "no"}],
        }))
        (vdir / "batch-2-output.json").write_text(json.dumps({
            "batch_number": 2,
            "verdicts": [{"finding_ref": {"content_hash": "b" * 16}, "action": "confirm", "reasoning": "yes"}],
        }))
        survivors, issues = simple_mode.apply_verdicts(vdir, [f1, f2])
        assert [f["title"] for f in survivors] == ["b"]
        assert len(issues) == 1
