#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Apply validator verdicts to produce the post-validation stage directory.

Reads per-finding files from --input-dir (10-merged/) and verdict files from
--verdicts-dir (15-validation/batch-*-output.json), then writes the surviving
findings to --output-dir (20-findings/).

Verdict application is deterministic:
  - confirm: copy the finding unchanged
  - rescore: shallow-merge new_dimensions into the finding
  - remove: skip (finding absent from output)

Findings with no verdict (e.g., from a failed validator batch) pass through
unchanged — the absence of a verdict is not a removal signal.

Validates each verdict file against validation-output.schema.json.
Validates each output finding against merged-finding.schema.json.
"""

import argparse
import json
import sys
from pathlib import Path

import jsonschema

REPO_ROOT = Path(__file__).resolve().parent.parent
SCHEMAS_DIR = REPO_ROOT / "schemas"
PLUGIN_ROOT = REPO_ROOT.parent.parent

sys.path.insert(0, str(PLUGIN_ROOT))
from scripts.envelope import (  # noqa: E402
    load_stage_dir,
    safe_load_json,
    schema_registry,
    write_stage_dir,
)


def _validate(instance: object, schema_path: Path) -> list[str]:
    schema = safe_load_json(schema_path)
    validator = jsonschema.Draft202012Validator(schema, registry=schema_registry())
    return [
        f"{'/'.join(str(p) for p in err.absolute_path) or '<root>'}: {err.message}"
        for err in sorted(
            validator.iter_errors(instance), key=lambda e: list(e.absolute_path)
        )
    ]


def _load_verdicts(verdicts_dir: Path, schema_path: Path) -> tuple[dict[str, dict], list[dict]]:
    """Load and validate all verdict files, returning (hash→verdict map, issues)."""
    verdict_map: dict[str, dict] = {}
    issues: list[dict] = []

    for path in sorted(verdicts_dir.glob("batch-*-output.json")):
        try:
            data = safe_load_json(path)
        except (json.JSONDecodeError, ValueError) as exc:
            issues.append({
                "severity": "warning",
                "kind": "validation_failed",
                "message": f"could not parse verdict file {path.name}: {exc}",
                "source_component": "apply-verdicts",
            })
            continue

        errors = _validate(data, schema_path)
        if errors:
            issues.append({
                "severity": "warning",
                "kind": "validation_failed",
                "message": (
                    f"verdict file {path.name} failed schema validation "
                    f"({len(errors)} error(s)): {errors[0]}"
                ),
                "source_component": "apply-verdicts",
            })
            continue

        for verdict in data.get("verdicts", []):
            ch = verdict["finding_ref"]["content_hash"]
            verdict_map[ch] = verdict

    return verdict_map, issues


def _apply_verdict(finding: dict, verdict: dict) -> dict | None:
    """Apply a single verdict to a finding. Returns the modified finding,
    or None if the verdict is 'remove'."""
    action = verdict["action"]
    if action == "remove":
        return None
    if action == "confirm":
        return dict(finding)
    if action == "rescore":
        result = dict(finding)
        for key, value in verdict["new_dimensions"].items():
            result[key] = value
        return result
    return dict(finding)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input-dir",
        type=Path,
        required=True,
        help="stage directory with merged findings (10-merged/)",
    )
    parser.add_argument(
        "--verdicts-dir",
        type=Path,
        required=True,
        help="directory with batch-*-output.json verdict files (15-validation/)",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        required=True,
        help="stage directory for post-validation findings (20-findings/)",
    )
    parser.add_argument(
        "--issues",
        type=Path,
        default=None,
        help="optional JSON array of additional issues to merge into the envelope",
    )
    args = parser.parse_args(argv)

    for d, label in ((args.input_dir, "--input-dir"), (args.verdicts_dir, "--verdicts-dir"), (args.output_dir, "--output-dir")):
        if not d.is_dir():
            print(f"error: {label} is not a directory: {d}", file=sys.stderr)
            return 2

    verdict_schema = SCHEMAS_DIR / "validation-output.schema.json"
    finding_schema = SCHEMAS_DIR / "merged-finding.schema.json"
    envelope_schema = SCHEMAS_DIR / "stage-envelope.schema.json"
    for sp in (verdict_schema, finding_schema, envelope_schema):
        if not sp.exists():
            print(f"error: schema not found: {sp}", file=sys.stderr)
            return 2

    envelope, findings = load_stage_dir(args.input_dir)
    verdict_map, verdict_issues = _load_verdicts(args.verdicts_dir, verdict_schema)

    additional_issues: list[dict] = []
    if args.issues is not None:
        try:
            data = safe_load_json(args.issues)
            if isinstance(data, list):
                additional_issues = data
        except (json.JSONDecodeError, ValueError) as exc:
            print(f"warning: could not load --issues {args.issues}: {exc}", file=sys.stderr)

    confirmed = 0
    rescored = 0
    removed = 0
    passthrough = 0
    output_findings: list[dict] = []

    for finding in findings:
        ch = finding["content_hash"]
        verdict = verdict_map.get(ch)

        if verdict is None:
            output_findings.append(finding)
            passthrough += 1
            continue

        result = _apply_verdict(finding, verdict)
        if result is None:
            removed += 1
        else:
            errors = _validate(result, finding_schema)
            if errors:
                print(
                    f"error: finding {ch} failed schema validation after verdict application:",
                    file=sys.stderr,
                )
                for e in errors:
                    print(f"  {e}", file=sys.stderr)
                return 1
            output_findings.append(result)
            if verdict["action"] == "confirm":
                confirmed += 1
            else:
                rescored += 1

    all_issues = envelope.get("issues", []) + verdict_issues + additional_issues
    output_envelope = dict(envelope)
    output_envelope["issues"] = all_issues

    envelope_errors = _validate(output_envelope, envelope_schema)
    if envelope_errors:
        print("error: output envelope failed schema validation:", file=sys.stderr)
        for e in envelope_errors:
            print(f"  {e}", file=sys.stderr)
        return 1

    write_stage_dir(args.output_dir, output_envelope, output_findings)

    print(
        f"OK: {confirmed} confirmed, {rescored} rescored, {removed} removed, "
        f"{passthrough} passthrough → {len(output_findings)} finding(s) "
        f"at {args.output_dir}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
