#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.7)
"""Slice a stage directory of per-finding files into validation batches.

Reads all finding files from --input-dir (excluding _envelope.json), sorts
by dimensional priority (ordinal tuple of runtime_scope, failure_mode,
evidence_quality, trace_origin) descending with content_hash as
deterministic tie-break, then writes ``batch-<N>-input.json`` files into
--output-dir, each containing at most --batch-size findings (default 8 —
the spec's hard cap).

Findings are identified by content_hash (the filename stem). No index
field is used — content_hash is the sole cross-stage key.

Validates each batch against validation-input.schema.json before writing;
the script exits non-zero on any validation error.
"""

import argparse
import json
import math
import sys
from pathlib import Path

import jsonschema

REPO_ROOT = Path(__file__).resolve().parent.parent
SCHEMAS_DIR = REPO_ROOT / "schemas"
PLUGIN_ROOT = REPO_ROOT.parent.parent

sys.path.insert(0, str(PLUGIN_ROOT))
from scripts.envelope import load_stage_dir, safe_load_json, schema_registry  # noqa: E402

# Keep this in sync with validation-input.schema.json $defs/batch_finding.required
BATCH_FINDING_FIELDS = (
    "content_hash",
    "concern_slug",
    "title",
    "runtime_scope",
    "runtime_scope_justification",
    "failure_mode",
    "failure_mode_justification",
    "evidence_quality",
    "evidence_quality_justification",
    "trace_origin",
    "trace_origin_justification",
    "effort_to_fix",
    "effort_to_fix_justification",
    "locations",
    "issue",
    "why_it_matters",
    "suggested_fix",
)

MAX_BATCH_SIZE = 8

RUNTIME_SCOPE_ORDER = ["documentation", "tooling", "ci", "service-internal", "service-external"]
FAILURE_MODE_ORDER = ["unclear", "confusion", "build-break", "degraded-behavior", "crash-or-outage", "data-loss-or-security"]
EVIDENCE_QUALITY_ORDER = ["speculative", "inferred", "demonstrated"]
TRACE_ORIGIN_ORDER = ["local", "component", "entry-point"]


def _priority(f: dict) -> tuple[int, int, int, int]:
    return (
        RUNTIME_SCOPE_ORDER.index(f["runtime_scope"]),
        FAILURE_MODE_ORDER.index(f["failure_mode"]),
        EVIDENCE_QUALITY_ORDER.index(f["evidence_quality"]),
        TRACE_ORIGIN_ORDER.index(f["trace_origin"]),
    )


def _project_to_batch_finding(finding: dict) -> dict:
    """Project a merged finding to validation-input.batch_finding shape.

    Drops fields not in the batch schema (e.g. source_dimensions).
    """
    out = {}
    for key in BATCH_FINDING_FIELDS:
        out[key] = finding[key]
    return out


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input-dir",
        type=Path,
        required=True,
        help="stage directory with _envelope.json + per-finding files",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        required=True,
        help="directory for batch-<N>-input.json files (created if absent)",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=MAX_BATCH_SIZE,
        help=(
            f"findings per batch (1..{MAX_BATCH_SIZE}); the spec caps at "
            f"{MAX_BATCH_SIZE} per validator"
        ),
    )
    args = parser.parse_args(argv)

    if args.batch_size < 1 or args.batch_size > MAX_BATCH_SIZE:
        print(
            f"error: --batch-size must be between 1 and {MAX_BATCH_SIZE}; "
            f"got {args.batch_size}",
            file=sys.stderr,
        )
        return 2

    if not args.input_dir.is_dir():
        print(f"error: --input-dir is not a directory: {args.input_dir}", file=sys.stderr)
        return 2

    schema_path = SCHEMAS_DIR / "validation-input.schema.json"
    if not schema_path.exists():
        print(f"error: schema not found: {schema_path}", file=sys.stderr)
        return 2

    _envelope, findings = load_stage_dir(args.input_dir)

    if not findings:
        print("OK: no findings to batch")
        return 0

    # Sort by priority desc (content_hash tie-break for determinism).
    sorted_findings = sorted(
        findings,
        key=lambda f: (tuple(-x for x in _priority(f)), f["content_hash"]),
    )

    total = len(sorted_findings)
    total_batches = math.ceil(total / args.batch_size)

    args.output_dir.mkdir(parents=True, exist_ok=True)

    schema = safe_load_json(schema_path)
    validator = jsonschema.Draft202012Validator(schema, registry=schema_registry())

    written = 0
    for batch_num in range(1, total_batches + 1):
        start = (batch_num - 1) * args.batch_size
        end = start + args.batch_size
        slice_ = sorted_findings[start:end]
        batch = {
            "batch_number": batch_num,
            "total_batches": total_batches,
            "findings": [
                _project_to_batch_finding(f)
                for f in slice_
            ],
        }
        errors = sorted(
            validator.iter_errors(batch),
            key=lambda e: list(e.absolute_path),
        )
        if errors:
            print(
                f"error: batch {batch_num} failed schema validation:",
                file=sys.stderr,
            )
            for err in errors:
                location = "/".join(str(p) for p in err.absolute_path) or "<root>"
                print(f"  {location}: {err.message}", file=sys.stderr)
            return 1

        out_path = args.output_dir / f"batch-{batch_num}-input.json"
        with out_path.open("w", encoding="utf-8") as fh:
            json.dump(batch, fh, indent=2)
            fh.write("\n")
        written += 1

        top_hash = batch["findings"][0]["content_hash"] if batch["findings"] else "N/A"
        top_f = slice_[0]
        print(
            f"  batch {batch_num}: {len(batch['findings'])} finding(s),"
            f" top={top_hash} ({top_f['runtime_scope']}/{top_f['failure_mode']})",
            file=sys.stderr,
        )

    print(
        f"OK: wrote {written} batch file(s) covering {total} finding(s) "
        f"into {args.output_dir}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
