#!/usr/bin/env bash
# Generated By: Claude Code (Claude Opus 4.6)
#
# Guard script: verifies this is a git repo with a determinable default branch.
# Exits non-zero on failure to abort skill loading via bang-injection.

set -euo pipefail

if ! git rev-parse --is-inside-work-tree &>/dev/null; then
  echo "ERROR: Not inside a git repository. Are you in the right directory?" >&2
  exit 1
fi

default_branch=$(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's|^refs/remotes/||')

if [ -z "$default_branch" ]; then
  echo "ERROR: Cannot determine default branch. Are you in the right directory?" >&2
  exit 1
fi

echo "Default branch: ${default_branch}"
