#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.7)
"""Consolidate per-agent JSON findings into a single consolidated.json.

Reads every ``*.json`` under --raw-dir, validates each against the
agent-output schema (skipping malformed files with a warning), then applies
three merge passes:

  1. Group by (concern_slug, primary location) — primary location is the
     first entry in finding.locations whose role is 'primary' (or absent,
     which defaults to primary). Within each group:
       - locations: union, dedup by (path, line)
       - suggested_fix: longest non-trivial (tie-break by source dimension order)
       - runtime_scope, failure_mode, evidence_quality, trace_origin: max by ordinal
       - effort_to_fix: min by ordinal
       - justifications: from the finding that contributed the winning value
       - source_dimensions: sorted union of dimension_slug values

  2. Cross-cutting merge (threshold 0.7) — within the same concern_slug,
     group remaining findings by title similarity (Jaccard over lowercased
     alphanumeric token sets). Catches cases where one concern flags the
     same issue with slightly different wording.

  3. Cross-concern merge (threshold 0.4) — across different concern_slug
     values, group findings whose primary location is identical and whose
     titles have Jaccard similarity above the threshold. Lower threshold
     than pass 2 because shared location already evidences they are the
     same observation; different angles (architecture vs. implementation)
     legitimately rephrase the issue differently. Merged finding's
     concern_slug is taken from the highest-priority contributor
     (dimensional ordinal tuple, alphabetical tie-break).

Each merged finding gets a stable content_hash: hex SHA-256 (truncated to 16
chars) over (concern_slug, dimension_slug of first contributor, primary
location ``path:line``, title).

The decomposition list is built from the agent-output dimension info,
deduplicated by dimension_slug.

Validates the final document against consolidated.schema.json before writing.
"""

import argparse
import json
import re
import sys
from pathlib import Path

import jsonschema

REPO_ROOT = Path(__file__).resolve().parent.parent
SCHEMAS_DIR = REPO_ROOT / "schemas"
PLUGIN_ROOT = REPO_ROOT.parent.parent

sys.path.insert(0, str(PLUGIN_ROOT))
from scripts.envelope import _line_start, content_hash, safe_load_json, schema_registry  # noqa: E402

_TOKEN_RE = re.compile(r"[A-Za-z0-9]+")

RUNTIME_SCOPE_ORDER = ["documentation", "tooling", "ci", "service-internal", "service-external"]
FAILURE_MODE_ORDER = ["unclear", "confusion", "build-break", "degraded-behavior", "crash-or-outage", "data-loss-or-security"]
EVIDENCE_QUALITY_ORDER = ["speculative", "inferred", "demonstrated"]
TRACE_ORIGIN_ORDER = ["local", "component", "entry-point"]
EFFORT_TO_FIX_ORDER = ["trivial", "small", "moderate", "large"]

_DIMENSION_FIELDS = [
    ("runtime_scope", RUNTIME_SCOPE_ORDER, max),
    ("failure_mode", FAILURE_MODE_ORDER, max),
    ("evidence_quality", EVIDENCE_QUALITY_ORDER, max),
    ("trace_origin", TRACE_ORIGIN_ORDER, max),
    ("effort_to_fix", EFFORT_TO_FIX_ORDER, min),
]


def _merge_dimension(group: list[dict], field: str, ordering: list[str], agg) -> tuple[str, str]:
    """Return (winning_value, justification_from_winner) for a categorical dimension."""
    values = [(ordering.index(f[field]), f) for f in group]
    winner = agg(values, key=lambda t: t[0])
    return winner[1][field], winner[1][f"{field}_justification"]


def _dimension_priority(f: dict) -> tuple[int, int, int, int]:
    return (
        RUNTIME_SCOPE_ORDER.index(f["runtime_scope"]),
        FAILURE_MODE_ORDER.index(f["failure_mode"]),
        EVIDENCE_QUALITY_ORDER.index(f["evidence_quality"]),
        TRACE_ORIGIN_ORDER.index(f["trace_origin"]),
    )


def _validate(instance: object, schema_path: Path) -> list[str]:
    schema = safe_load_json(schema_path)
    validator = jsonschema.Draft202012Validator(schema, registry=schema_registry())
    return [
        f"{'/'.join(str(p) for p in err.absolute_path) or '<root>'}: {err.message}"
        for err in sorted(
            validator.iter_errors(instance), key=lambda e: list(e.absolute_path)
        )
    ]


def _primary_location(finding: dict) -> dict:
    """First location whose role is 'primary' or absent; falls back to [0]."""
    for loc in finding["locations"]:
        if loc.get("role", "primary") == "primary":
            return loc
    return finding["locations"][0]


def _location_key(loc: dict) -> tuple[str, str]:
    return (loc["path"], loc["line"])


def _title_tokens(title: str) -> frozenset[str]:
    return frozenset(t.lower() for t in _TOKEN_RE.findall(title))


def _jaccard(a: frozenset[str], b: frozenset[str]) -> float:
    if not a and not b:
        return 1.0
    union = a | b
    if not union:
        return 0.0
    return len(a & b) / len(union)


def _content_hash(
    *, concern_slug: str, dimension_slug: str, primary: dict, title: str
) -> str:
    return content_hash(
        concern_slug,
        dimension_slug,
        f"{primary['path']}:{primary['line']}",
        title,
    )


def _merge_findings(group: list[dict]) -> dict:
    """Merge a group of (annotated) findings sharing a primary location.

    Each item in `group` is expected to carry the original finding fields
    plus a `_dimension_slug` annotation set by the caller.
    """
    first = group[0]
    locations: list[dict] = []
    seen_keys: set[tuple[str, str]] = set()
    for f in group:
        for loc in f["locations"]:
            key = _location_key(loc)
            if key in seen_keys:
                continue
            seen_keys.add(key)
            locations.append(loc)

    fixes_with_dim = sorted(
        (
            (f["suggested_fix"], f["_dimension_slug"])
            for f in group
            if f.get("suggested_fix") and f["suggested_fix"].strip()
        ),
        key=lambda t: (-len(t[0]), t[1]),
    )
    suggested_fix = fixes_with_dim[0][0] if fixes_with_dim else first["suggested_fix"]

    merged = {
        "concern_slug": first["concern_slug"],
        "source_dimensions": sorted({f["_dimension_slug"] for f in group}),
        "title": first["title"],
        "locations": locations,
        "issue": first["issue"],
        "why_it_matters": first["why_it_matters"],
        "suggested_fix": suggested_fix,
    }
    for field, ordering, agg in _DIMENSION_FIELDS:
        val, justification = _merge_dimension(group, field, ordering, agg)
        merged[field] = val
        merged[f"{field}_justification"] = justification
    return merged


def _cross_cutting_merge(findings: list[dict], threshold: float) -> list[dict]:
    """Within the same concern_slug, merge findings whose titles have Jaccard
    similarity ≥ threshold (over lowercased alphanumeric tokens)."""
    if not findings:
        return []

    by_concern: dict[str, list[dict]] = {}
    for f in findings:
        by_concern.setdefault(f["concern_slug"], []).append(f)

    output: list[dict] = []
    for concern, items in by_concern.items():
        output.extend(_merge_by_title_similarity(items, threshold))
    return output


def _cross_concern_merge(findings: list[dict], threshold: float) -> list[dict]:
    """Across different concern_slug values, merge findings whose primary
    location is identical AND whose titles have Jaccard similarity ≥ threshold.

    Threshold is typically lower than the within-concern threshold: same-line
    observations from different angles (architecture vs. implementation, etc.)
    legitimately phrase the issue differently. The merged finding's
    concern_slug is taken from the highest-priority contributor (dimensional
    ordinal tuple, tie-break alphabetical).
    """
    if not findings:
        return []

    by_location: dict[tuple[str, str], list[dict]] = {}
    for f in findings:
        primary = _primary_location(f)
        by_location.setdefault((primary["path"], primary["line"]), []).append(f)

    output: list[dict] = []
    for items in by_location.values():
        if len(items) == 1:
            output.append(items[0])
            continue
        # Within a location group, sub-cluster by title similarity.
        clusters = _merge_by_title_similarity(items, threshold, force_concern=True)
        output.extend(clusters)
    return output


def _merge_by_title_similarity(
    items: list[dict],
    threshold: float,
    *,
    force_concern: bool = False,
) -> list[dict]:
    """Cluster `items` by title Jaccard similarity ≥ threshold and merge each
    cluster. When force_concern is True, the merged finding's concern_slug is
    taken from the highest-priority contributor (used for cross-concern merge).
    """
    token_sets = [_title_tokens(f["title"]) for f in items]
    merged_into: list[int | None] = [None] * len(items)
    groups: list[list[int]] = []
    for i, tokens_i in enumerate(token_sets):
        if merged_into[i] is not None:
            continue
        group_idx = len(groups)
        groups.append([i])
        merged_into[i] = group_idx
        for j in range(i + 1, len(items)):
            if merged_into[j] is not None:
                continue
            if _jaccard(tokens_i, token_sets[j]) >= threshold:
                groups[group_idx].append(j)
                merged_into[j] = group_idx

    output: list[dict] = []
    for group_indices in groups:
        if len(group_indices) == 1:
            output.append(items[group_indices[0]])
            continue

        # Pick the dominant finding (highest priority, alphabetical tie-break)
        # so its concern_slug, title, issue, why_it_matters, suggested_fix
        # become the merged record's prose.
        def _priority(idx: int) -> tuple:
            f = items[idx]
            dp = _dimension_priority(f)
            return ((-dp[0], -dp[1], -dp[2], -dp[3]), f["concern_slug"], f["title"])

        ordered = sorted(group_indices, key=_priority)
        dominant = items[ordered[0]]

        annotated = []
        for idx in group_indices:
            f = items[idx]
            dim = f.get("_dimension_slug") or (f.get("source_dimensions") or [""])[0]
            annotated.append({**f, "_dimension_slug": dim})
        merged = _merge_findings(annotated)

        # _merge_findings uses items[0] for prose; override with dominant.
        merged["title"] = dominant["title"]
        merged["issue"] = dominant["issue"]
        merged["why_it_matters"] = dominant["why_it_matters"]
        merged["suggested_fix"] = dominant["suggested_fix"]
        if force_concern:
            merged["concern_slug"] = dominant["concern_slug"]

        all_dims: set[str] = set()
        for idx in group_indices:
            src = items[idx].get("source_dimensions")
            if src:
                all_dims.update(src)
            else:
                all_dims.add(items[idx]["_dimension_slug"])
        merged["source_dimensions"] = sorted(all_dims)
        output.append(merged)
    return output


def _build_decomposition(agent_outputs: list[dict]) -> list[dict]:
    """Unique decomposition entries keyed by dimension_slug, preserving the
    first-seen dimension_name and dimension_scope per slug."""
    seen: dict[str, dict] = {}
    for ao in agent_outputs:
        slug = ao["dimension_slug"]
        if slug in seen:
            continue
        seen[slug] = {
            "dimension_name": ao["dimension_name"],
            "dimension_slug": slug,
            "dimension_scope": ao.get("dimension_scope", {}),
        }
    return [seen[k] for k in sorted(seen)]


# Top-level keys that only appear in the cross-skill envelope, never in
# an agent-output document. Their presence in a raw/*.json is a strong
# signal the sub-agent wrote the wrong schema (an envelope instead of an
# agent-output); we surface that up front with an actionable message
# rather than letting the generic schema validator emit a wall of
# "additional property not allowed" / "required key missing" errors.
_ENVELOPE_ONLY_KEYS = frozenset(
    {"schema_version", "source", "project", "decomposition", "issues",
     "supplementary", "applied"}
)


def _detect_envelope_shape(instance: object) -> list[str]:
    """Return the envelope-only keys found at the top level of `instance`,
    or an empty list if none are present (i.e., the file looks like an
    attempt at agent-output).
    """
    if not isinstance(instance, dict):
        return []
    return sorted(set(instance.keys()) & _ENVELOPE_ONLY_KEYS)


def _load_and_validate_raw(
    raw_dir: Path, agent_schema: Path
) -> tuple[list[dict], list[str]]:
    """Return (valid_agent_outputs, warnings)."""
    valid: list[dict] = []
    warnings: list[str] = []
    schema = safe_load_json(agent_schema)
    validator = jsonschema.Draft202012Validator(schema, registry=schema_registry())

    for path in sorted(raw_dir.glob("*.json")):
        try:
            instance = safe_load_json(path)
        except json.JSONDecodeError as exc:
            warnings.append(
                f"skipping {path.name}: invalid JSON at line {exc.lineno},"
                f" col {exc.colno}: {exc.msg}"
            )
            continue

        # Fast-path: a raw file with envelope-only keys is almost certainly
        # a sub-agent that confused the cross-skill envelope schema for the
        # agent-output schema. Emit a targeted warning so the cause is
        # obvious instead of drowning in schema errors.
        envelope_keys = _detect_envelope_shape(instance)
        if envelope_keys:
            warnings.append(
                f"skipping {path.name}: file has cross-skill envelope shape "
                f"(top-level keys {envelope_keys}), not agent-output shape. "
                "The sub-agent wrote the wrong schema — it must emit agent-output "
                "({'agent_id', 'concern', 'concern_slug', 'dimension_name', "
                "'dimension_slug', 'dimension_scope', 'findings'[, "
                "'cross_cutting_observations']}), NOT the final envelope. "
                "Excluded from consolidation."
            )
            continue

        errors = list(validator.iter_errors(instance))
        if errors:
            header = (
                f"skipping {path.name}: schema validation failed "
                f"({len(errors)} error(s))"
            )
            details = [
                f"  [{i}] at {'/'.join(str(p) for p in err.absolute_path) or '<root>'}: {err.message}"
                for i, err in enumerate(errors, start=1)
            ]
            warnings.append(header + "\n" + "\n".join(details))
            continue
        valid.append(instance)
    return valid, warnings


def consolidate(
    agent_outputs: list[dict],
    project_name: str,
    scope_slug: str,
    similarity_threshold: float,
    cross_concern_threshold: float = 0.4,
) -> dict:
    """Pure-data entry point. Used by tests that want to bypass the CLI."""
    # Flatten findings, annotating with their source dimension.
    flat: list[dict] = []
    for ao in agent_outputs:
        for f in ao["findings"]:
            flat.append(
                {
                    **f,
                    "_dimension_slug": ao["dimension_slug"],
                    "concern_slug": ao["concern_slug"],
                }
            )

    # Pass 1: group by (concern_slug, primary location)
    pass1_groups: dict[tuple[str, str, str], list[dict]] = {}
    for f in flat:
        primary = _primary_location(f)
        key = (f["concern_slug"], primary["path"], primary["line"])
        pass1_groups.setdefault(key, []).append(f)

    pass1_output: list[dict] = []
    for group in pass1_groups.values():
        pass1_output.append(_merge_findings(group))

    # Pass 2: cross-cutting merge by title similarity within concern.
    # Re-annotate with _dimension_slug so the merger can use it as a tie-break.
    for f in pass1_output:
        f["_dimension_slug"] = f["source_dimensions"][0]
    pass2_output = _cross_cutting_merge(pass1_output, similarity_threshold)

    # Pass 3: cross-concern merge at identical primary location.
    # Catches cases where two concerns flag the same code from different
    # angles (e.g., architecture vs. implementation both call out a
    # thread-safety bug at the same line range).
    for f in pass2_output:
        f.setdefault("_dimension_slug", f["source_dimensions"][0])
    pass3_output = _cross_concern_merge(pass2_output, cross_concern_threshold)

    # Strip internal annotations and add content_hash.
    final_findings: list[dict] = []
    for f in pass3_output:
        primary = _primary_location(f)
        chash = _content_hash(
            concern_slug=f["concern_slug"],
            dimension_slug=f["source_dimensions"][0],
            primary=primary,
            title=f["title"],
        )
        cleaned = {k: v for k, v in f.items() if not k.startswith("_")}
        cleaned["content_hash"] = chash
        # Order keys deterministically for cleaner diffs.
        ordered = {
            "content_hash": cleaned["content_hash"],
            "concern_slug": cleaned["concern_slug"],
            "source_dimensions": cleaned["source_dimensions"],
            "title": cleaned["title"],
            "runtime_scope": cleaned["runtime_scope"],
            "runtime_scope_justification": cleaned["runtime_scope_justification"],
            "failure_mode": cleaned["failure_mode"],
            "failure_mode_justification": cleaned["failure_mode_justification"],
            "evidence_quality": cleaned["evidence_quality"],
            "evidence_quality_justification": cleaned["evidence_quality_justification"],
            "trace_origin": cleaned["trace_origin"],
            "trace_origin_justification": cleaned["trace_origin_justification"],
            "effort_to_fix": cleaned["effort_to_fix"],
            "effort_to_fix_justification": cleaned["effort_to_fix_justification"],
            "locations": cleaned["locations"],
            "issue": cleaned["issue"],
            "why_it_matters": cleaned["why_it_matters"],
            "suggested_fix": cleaned["suggested_fix"],
        }
        final_findings.append(ordered)

    # Sort findings deterministically: concern, then primary location.
    # Line is parsed as int so '9' sorts before '10' (was lexicographic before).
    final_findings.sort(
        key=lambda f: (
            f["concern_slug"],
            _primary_location(f)["path"],
            _line_start(_primary_location(f).get("line", "")),
            f["title"],
        )
    )

    decomposition = _build_decomposition(agent_outputs)

    project: dict = {"name": project_name}
    if scope_slug:
        project["scope_slug"] = scope_slug
    else:
        project["scope_slug"] = ""

    return {
        "project": project,
        "decomposition": decomposition,
        "findings": final_findings,
    }


def _append_issues(path: Path, warnings: list[str]) -> None:
    """Append one issue object per warning to the issues file. Creates the
    file (as a fresh JSON array) if missing; preserves existing entries
    otherwise. Each warning produces a `schema_rejected_input` issue so
    the final envelope carries a machine-readable record of skipped inputs.
    """
    existing: list[dict] = []
    if path.exists():
        try:
            with path.open("r", encoding="utf-8") as fh:
                loaded = json.load(fh)
            if isinstance(loaded, list):
                existing = loaded
        except (OSError, json.JSONDecodeError):
            existing = []

    new_entries = [
        {
            "severity": "warning",
            "kind": "schema_rejected_input",
            "message": w,
            "source_component": "consolidate-findings",
        }
        for w in warnings
    ]

    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as fh:
        json.dump(existing + new_entries, fh, indent=2)
        fh.write("\n")


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--raw-dir",
        type=Path,
        required=True,
        help="directory containing per-agent JSON files",
    )
    parser.add_argument(
        "--output", type=Path, required=True, help="path to write consolidated.json"
    )
    parser.add_argument(
        "--project-name", required=True, help="project name for the consolidated set"
    )
    parser.add_argument(
        "--scope-slug",
        default="",
        help="optional scope slug (PR number, theme); embedded in project metadata",
    )
    parser.add_argument(
        "--similarity-threshold",
        type=float,
        default=0.7,
        help="Jaccard threshold (0.0-1.0) for within-concern title-similarity merge",
    )
    parser.add_argument(
        "--cross-concern-threshold",
        type=float,
        default=0.4,
        help=(
            "Jaccard threshold (0.0-1.0) for cross-concern merge at identical "
            "primary location; lower than --similarity-threshold because the "
            "shared location already evidences they are the same observation"
        ),
    )
    parser.add_argument(
        "--issues-out",
        type=Path,
        default=None,
        help=(
            "optional path to write/append skip warnings as shared-schema "
            "issue objects. Each skipped raw file becomes one issue with "
            "kind='schema_rejected_input'. If the file already exists and "
            "contains a JSON array, the new issues are appended; otherwise "
            "the file is created with a fresh array. This lets the render "
            "step consume one combined issues.json via its --issues flag."
        ),
    )
    args = parser.parse_args(argv)

    if not args.raw_dir.is_dir():
        print(f"error: --raw-dir is not a directory: {args.raw_dir}", file=sys.stderr)
        return 2

    for name, value in (
        ("--similarity-threshold", args.similarity_threshold),
        ("--cross-concern-threshold", args.cross_concern_threshold),
    ):
        if value < 0.0 or value > 1.0:
            print(
                f"error: {name} must be between 0.0 and 1.0; got {value}",
                file=sys.stderr,
            )
            return 2

    if args.raw_dir.resolve() == args.output.resolve() or args.output.is_dir():
        print(
            f"error: --output must be a file path, not a directory: {args.output}",
            file=sys.stderr,
        )
        return 2

    agent_schema = SCHEMAS_DIR / "agent-output.schema.json"
    consolidated_schema = SCHEMAS_DIR / "consolidated.schema.json"
    if not agent_schema.exists() or not consolidated_schema.exists():
        print(f"error: required schemas not found in {SCHEMAS_DIR}", file=sys.stderr)
        return 2

    valid_agents, warnings = _load_and_validate_raw(args.raw_dir, agent_schema)
    for w in warnings:
        print(f"warning: {w}", file=sys.stderr)

    if args.issues_out is not None and warnings:
        _append_issues(args.issues_out, warnings)

    if not valid_agents:
        print(
            f"error: no valid agent-output files found in {args.raw_dir}",
            file=sys.stderr,
        )
        return 1

    consolidated = consolidate(
        valid_agents,
        project_name=args.project_name,
        scope_slug=args.scope_slug,
        similarity_threshold=args.similarity_threshold,
        cross_concern_threshold=args.cross_concern_threshold,
    )

    errors = _validate(consolidated, consolidated_schema)
    if errors:
        print("error: consolidated output failed schema validation:", file=sys.stderr)
        for e in errors:
            print(f"  {e}", file=sys.stderr)
        return 1

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8") as fh:
        json.dump(consolidated, fh, indent=2)
        fh.write("\n")

    print(
        f"OK: consolidated {len(valid_agents)} agent output(s) into "
        f"{len(consolidated['findings'])} finding(s) at {args.output}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
