#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Filter findings whose primary locations fall outside the PR diff.

For PR-scoped reviews, removes per-finding files from a stage directory
when none of the finding's primary locations overlap with lines changed
in ``git diff <base-ref>...HEAD``.  Rewrites the stage directory in place
and records each filtered finding as an issue in the envelope.

Skips (no-op) when --base-ref is not provided — full-repo reviews keep
all findings.

Usage:
    python diff-scope-filter.py --stage-dir ./.tmp-review/10-merged/ --base-ref origin/devel
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path

SKILL_ROOT = Path(__file__).resolve().parent.parent
PLUGIN_ROOT = SKILL_ROOT.parent.parent

sys.path.insert(0, str(PLUGIN_ROOT))
from scripts.envelope import load_stage_dir, write_stage_dir  # noqa: E402


def get_changed_lines(base_ref: str) -> dict[str, set[int]]:
    """Parse unified diff to extract changed line numbers per file."""
    result = subprocess.run(
        ["git", "diff", f"{base_ref}...HEAD", "-U0"],
        capture_output=True, text=True, check=True,
    )

    changed: dict[str, set[int]] = {}
    current_file = None

    for line in result.stdout.splitlines():
        m = re.match(r"^\+\+\+ b/(.+)$", line)
        if m:
            current_file = m.group(1)
            changed.setdefault(current_file, set())
            continue

        m = re.match(r"^@@ .+ \+(\d+)(?:,(\d+))? @@", line)
        if m and current_file:
            start = int(m.group(1))
            count = int(m.group(2)) if m.group(2) else 1
            if count == 0:
                continue
            for i in range(start, start + count):
                changed[current_file].add(i)

    return changed


def mark_new_files(base_ref: str, changed: dict[str, set[int]]) -> None:
    """Mark all lines as changed for newly added files."""
    result = subprocess.run(
        ["git", "diff", f"{base_ref}...HEAD", "--name-status"],
        capture_output=True, text=True, check=True,
    )
    for status_line in result.stdout.splitlines():
        parts = status_line.split("\t", 1)
        if parts[0] == "A" and len(parts) > 1:
            changed[parts[1]] = set(range(1, 100_000))


def parse_line_range(line_str: str) -> tuple[int, int]:
    """Parse '42' or '42-50' into (start, end) inclusive."""
    if "-" in line_str:
        a, b = line_str.split("-", 1)
        return int(a), int(b)
    n = int(line_str)
    return n, n


def finding_overlaps_diff(finding: dict, changed: dict[str, set[int]]) -> bool:
    """Return True if any primary location overlaps with changed lines."""
    locations = finding.get("locations", [])
    primary_locs = [
        loc for loc in locations
        if loc.get("role", "primary") == "primary"
    ]
    if not primary_locs:
        primary_locs = locations[:1]

    for loc in primary_locs:
        path = loc["path"]
        if path not in changed:
            continue
        start, end = parse_line_range(loc["line"])
        finding_lines = set(range(start, end + 1))
        if finding_lines & changed[path]:
            return True
    return False


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--stage-dir",
        type=Path,
        required=True,
        help="stage directory with _envelope.json + per-finding files (modified in place)",
    )
    parser.add_argument(
        "--base-ref",
        default="",
        help="git ref to diff against (e.g. origin/devel). Empty = skip filtering.",
    )
    args = parser.parse_args(argv)

    if not args.base_ref:
        print("OK: no --base-ref provided, skipping diff-scope filter (full-repo review)")
        return 0

    if not args.stage_dir.is_dir():
        print(f"error: --stage-dir is not a directory: {args.stage_dir}", file=sys.stderr)
        return 2

    try:
        changed = get_changed_lines(args.base_ref)
        mark_new_files(args.base_ref, changed)
    except subprocess.CalledProcessError as exc:
        print(f"error: git diff failed: {exc.stderr}", file=sys.stderr)
        return 1

    if not changed:
        print("warning: no changed files detected in diff", file=sys.stderr)
        return 0

    envelope, findings = load_stage_dir(args.stage_dir)

    kept: list[dict] = []
    filtered: list[dict] = []

    for finding in findings:
        if finding_overlaps_diff(finding, changed):
            kept.append(finding)
        else:
            filtered.append(finding)

    if not filtered:
        print(f"OK: all {len(findings)} finding(s) overlap with diff")
        return 0

    issues = envelope.get("issues", [])
    for f in filtered:
        primary_locs = [
            loc for loc in f.get("locations", [])
            if loc.get("role", "primary") == "primary"
        ]
        if not primary_locs:
            primary_locs = f.get("locations", [])[:1]
        loc_str = ", ".join(f"{l['path']}:{l['line']}" for l in primary_locs)
        issues.append({
            "severity": "info",
            "kind": "diff_scope_filtered",
            "message": (
                f"Finding '{f['title']}' ({f['content_hash']}) filtered: "
                f"primary location(s) {loc_str} not in PR diff"
            ),
            "source_component": "diff-scope-filter",
        })
    envelope["issues"] = issues

    write_stage_dir(args.stage_dir, envelope, kept)

    print(
        f"OK: {len(filtered)} finding(s) filtered (outside diff), "
        f"{len(kept)} finding(s) kept"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
