#!/usr/bin/env bash
# Generated By: Claude Code (Claude Opus 4.7)
#
# Extracts free-form guidance text from the skill's arguments and emits it as
# a "User Guidance" context section. The main agent decides how to apply it.
#
# Parsing rules (paired with pr-scope.sh):
#   - No args              -> output nothing
#   - First arg is numeric -> treat it as a PR number; guidance is the remainder
#   - First arg non-numeric -> entire argument string is guidance

set -euo pipefail

[ "$#" -ge 1 ] || exit 0

if [[ "$1" =~ ^[0-9]+$ ]]; then
  shift
fi

[ "$#" -ge 1 ] || exit 0

guidance="$*"
[ -n "${guidance// /}" ] || exit 0

cat <<EOF
## User Guidance

${guidance}
EOF
