#!/usr/bin/env bash
# Generated By: Claude Code (Claude Opus 4.7)
#
# Extracts free-form guidance text from the skill's arguments and emits it as
# a "User Guidance" context section. The main agent decides how to apply it.
#
# Parsing rules (paired with pr-scope.sh):
#   - No args              -> output nothing
#   - First arg is numeric -> treat it as a PR number; guidance is the remainder
#   - First arg non-numeric -> entire argument string is guidance
#
# Examples:
#   guidance.sh ""                   # outputs nothing
#   guidance.sh "focus on auth"      # outputs guidance block
#   guidance.sh "123"                # outputs nothing (PR only)
#   guidance.sh "123 focus on auth"  # outputs guidance block

set -euo pipefail

# SKILL.md invokes this as `guidance.sh "$ARGUMENTS"` — a single quoted
# string. Split internally: if the first whitespace-separated token is a
# PR number, drop it; the remainder is guidance. Otherwise the entire
# string is guidance.

[ "$#" -ge 1 ] || exit 0

# $1 may be empty or may contain multiple tokens.
all="$1"
first_token="${all%% *}"

if [[ "$first_token" =~ ^[0-9]+$ ]]; then
  # Strip the leading PR number and any separator whitespace.
  guidance="${all#"$first_token"}"
  guidance="${guidance# }"
else
  guidance="$all"
fi

# Trim pure-whitespace and emit nothing if empty.
[ -n "${guidance// /}" ] || exit 0

cat <<EOF
## User Guidance

${guidance}
EOF
