#!/usr/bin/env bash
# Generated By: Claude Code (Claude Opus 4.6)
#
# Outputs PR scope information (changed files and diff stats) for diff-scoped reviews.
# Called from SKILL.md pre-fetch with the skill's arguments.
# Outputs nothing unless the argument is a single number (PR number).

set -euo pipefail

# SKILL.md invokes this as `pr-scope.sh "$ARGUMENTS"` — a single quoted string
# that may contain multiple space-separated tokens (e.g. "123 focus on auth").
# Split internally: the first whitespace-separated token is the PR-number
# candidate; anything after it is guidance handled by guidance.sh.

# Test 1: was an arg sent?
[ "$#" -ge 1 ] || { echo "no argument, not a PR review"; exit 0; }

# Extract the first token; empty when ARGUMENTS is blank.
first_token="${1%% *}"
[ -n "$first_token" ] || { echo "no argument, not a PR review"; exit 0; }

# Test 2: is the first token a number?
[[ "$first_token" =~ ^[0-9]+$ ]] || { echo "argument is not a PR number, not a PR review"; exit 0; }

pr_number="$first_token"

# Determine the default branch, preferring remote refs (authoritative)
# over local refs. origin/main first (GitHub/GitLab convention), then
# origin/master (older convention), then local refs as last resort.
default_branch=""
for ref in origin/main origin/master main master; do
  if git rev-parse --verify "$ref" &>/dev/null; then
    default_branch="$ref"
    break
  fi
done

if [ -z "$default_branch" ]; then
  echo "## PR Scope: #${pr_number}"
  echo ""
  echo "WARNING: Could not determine default branch. Unable to compute changed files."
  exit 0
fi

# Find the merge base
base=$(git merge-base HEAD "$default_branch" 2>/dev/null) || {
  echo "## PR Scope: #${pr_number}"
  echo ""
  echo "WARNING: Could not determine merge base against ${default_branch}."
  exit 0
}

diff_stat=$(git diff --stat "$base"..HEAD)
if [ -z "$diff_stat" ]; then
  echo "## PR Scope: #${pr_number}"
  echo ""
  echo "WARNING: No changed files detected between merge base and HEAD."
  exit 0
fi

echo "## PR Scope: #${pr_number}"
echo ""
echo "Merge base: ${base:0:12} (against ${default_branch})"
echo ""
echo "### Diff Stats"
echo ""
echo "$diff_stat"
echo ""
echo "### Scope Rules"
echo ""
echo "- Report findings ONLY for the changed files listed above."
echo "- You may read other files for context (understanding imports, call sites, interfaces),"
echo "  but do not report findings against unchanged files."
echo "- When a changed file interacts with unchanged code in a problematic way, report the"
echo "  finding against the changed file with a note about the interaction."
echo "- The output filename slug is: pr-${pr_number}"
