#!/usr/bin/env bash
# Generated By: Claude Code (Claude Opus 4.6)
# Print the agent-output JSON schema to stdout.
# Injected into the review SKILL.md pre-fetch so sub-agents have the
# schema in context without needing to Read it (which requires permissions).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cat "$SCRIPT_DIR/../schemas/agent-output.schema.json"
