#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.7)
"""Render post-validation findings to a structured JSON document plus two
markdown files at the chosen output directory.

This is the only step that:
- Maps the four numerical scores to severity buckets via configurable thresholds
- Assigns finding IDs (C0.., I0.., S0.., N0..) in stable per-bucket order

Intermediate JSON in the pipeline carries no severity labels and no IDs.
"""

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SCHEMAS_DIR = REPO_ROOT / "schemas"

BUCKET_PREFIX = {
    "critical": "C",
    "important": "I",
    "suggestion": "S",
    "needs-review": "N",
}

BUCKET_ORDER = ["critical", "important", "suggestion", "needs-review"]


def assign_bucket(finding: dict, config: dict) -> str:
    confidence = finding["confidence"]
    if confidence < config["confidence_floor"]:
        return "needs-review"
    impact = finding["impact"]
    likelihood = finding["likelihood"]
    priority = impact * likelihood / 100
    if (
        priority >= config["critical"]["min_priority"]
        and impact >= config["critical"]["min_impact"]
    ):
        return "critical"
    if priority >= config["important"]["min_priority"]:
        return "important"
    return "suggestion"


def sort_key_within_bucket(finding: dict) -> tuple:
    primary = next(
        (
            loc
            for loc in finding["locations"]
            if loc.get("role", "primary") == "primary"
        ),
        finding["locations"][0],
    )
    return (primary["path"], primary["line"], finding["title"])


def assign_buckets_and_ids(findings: list[dict], config: dict) -> list[dict]:
    annotated = []
    for f in findings:
        bucket = assign_bucket(f, config)
        annotated.append({**f, "severity": bucket})

    by_bucket: dict[str, list[dict]] = {b: [] for b in BUCKET_ORDER}
    for f in annotated:
        by_bucket[f["severity"]].append(f)

    out: list[dict] = []
    for bucket in BUCKET_ORDER:
        for i, f in enumerate(sorted(by_bucket[bucket], key=sort_key_within_bucket)):
            f["id"] = f"{BUCKET_PREFIX[bucket]}{i}"
            out.append(f)
    return out


def _format_finding_block(f: dict) -> str:
    locations = "\n".join(
        f"- `{loc['path']}:{loc['line']}`"
        + (f" ({loc['role']})" if loc.get("role") and loc["role"] != "primary" else "")
        for loc in f["locations"]
    )
    return (
        f"#### {f['id']}: {f['title']}\n\n"
        f"**Locations:**\n{locations}\n\n"
        f"**Scores:** impact {f['impact']}, likelihood {f['likelihood']}, "
        f"effort_to_fix {f['effort_to_fix']}, confidence {f['confidence']}\n\n"
        f"**Issue:** {f['issue']}\n\n"
        f"**Why it matters:** {f['why_it_matters']}\n\n"
        f"**Suggested fix:** {f['suggested_fix']}\n"
    )


def render_main_markdown(rendered: dict, project_name: str, scope_slug: str) -> str:
    findings = rendered["findings"]
    by_bucket = {b: [f for f in findings if f["severity"] == b] for b in BUCKET_ORDER}

    base = file_basename(project_name, scope_slug)
    supp_path = f"{base}-supplementary.md"

    parts: list[str] = []
    parts.append(f"# Code Review: {project_name}\n")
    parts.append("## TL;DR\n")
    counts = (
        f"{len(by_bucket['critical'])} critical, "
        f"{len(by_bucket['important'])} important, "
        f"{len(by_bucket['suggestion'])} suggestion, "
        f"{len(by_bucket['needs-review'])} needs-review."
    )
    parts.append(f"{counts}\n")
    parts.append("## Findings\n")
    parts.append("### Critical\n")
    if by_bucket["critical"]:
        for f in by_bucket["critical"]:
            parts.append(_format_finding_block(f))
    else:
        parts.append("No critical issues identified.\n")

    parts.append("### Important\n")
    if by_bucket["important"]:
        for f in by_bucket["important"]:
            parts.append(_format_finding_block(f))
    else:
        parts.append("No important issues identified.\n")

    parts.append("### Suggestions\n")
    if by_bucket["suggestion"]:
        parts.append(
            f"{len(by_bucket['suggestion'])} suggestions documented in the "
            f"[supplementary review]({supp_path}#suggestions).\n"
        )
    else:
        parts.append("No suggestions.\n")

    parts.append("### Needs Review\n")
    if by_bucket["needs-review"]:
        parts.append(
            f"{len(by_bucket['needs-review'])} low-confidence findings in the "
            f"[supplementary review]({supp_path}#needs-review).\n"
        )
    else:
        parts.append("No low-confidence findings.\n")

    return "\n".join(parts)


def render_supplementary_markdown(
    rendered: dict, project_name: str, scope_slug: str
) -> str:
    findings = rendered["findings"]
    by_bucket = {b: [f for f in findings if f["severity"] == b] for b in BUCKET_ORDER}

    parts: list[str] = []
    parts.append(f"# Code Review (Supplementary): {project_name}\n")

    parts.append("## Decomposition\n")
    if rendered.get("decomposition"):
        for d in rendered["decomposition"]:
            scope = json.dumps(d.get("dimension_scope", {}), sort_keys=True)
            name = d["dimension_name"]
            slug = d["dimension_slug"]
            parts.append(f"- **{name}** (`{slug}`): {scope}")
        parts.append("")
    else:
        parts.append("(no decomposition recorded)\n")

    parts.append("## Detailed Analysis\n")
    by_concern: dict[str, list[dict]] = {}
    for f in findings:
        if f["severity"] == "needs-review":
            continue
        by_concern.setdefault(f["concern_slug"], []).append(f)
    if by_concern:
        for concern in sorted(by_concern):
            parts.append(f"### {concern.title()}\n")
            for f in by_concern[concern]:
                parts.append(_format_finding_block(f))
    else:
        parts.append("(no findings to detail)\n")

    parts.append("## Suggestions\n")
    if by_bucket["suggestion"]:
        for f in by_bucket["suggestion"]:
            parts.append(_format_finding_block(f))
    else:
        parts.append("None.\n")

    parts.append("## Needs Review\n")
    if by_bucket["needs-review"]:
        for f in by_bucket["needs-review"]:
            parts.append(_format_finding_block(f))
    else:
        parts.append("None.\n")

    return "\n".join(parts)


def file_basename(project_name: str, scope_slug: str) -> str:
    if scope_slug:
        return f"Review-{project_name}-{scope_slug}"
    return f"Review-{project_name}"


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        required=True,
        help="post-validation findings JSON (consolidated shape)",
    )
    parser.add_argument("--config", type=Path, required=True, help="render-config JSON")
    parser.add_argument(
        "--out-dir",
        type=Path,
        required=True,
        help="directory for output files (typically the project root)",
    )
    parser.add_argument(
        "--project-name", required=True, help="project name used in output filenames"
    )
    parser.add_argument(
        "--scope-slug",
        default="",
        help="optional slug appended to filenames (PR number, theme, etc.)",
    )
    args = parser.parse_args(argv)

    with args.input.open("r", encoding="utf-8") as fh:
        data = json.load(fh)
    with args.config.open("r", encoding="utf-8") as fh:
        config = json.load(fh)

    args.out_dir.mkdir(parents=True, exist_ok=True)

    rendered_findings = assign_buckets_and_ids(data.get("findings", []), config)
    rendered = {
        "project": data.get("project", {"name": args.project_name}),
        "decomposition": data.get("decomposition", []),
        "findings": rendered_findings,
    }

    base = file_basename(args.project_name, args.scope_slug)
    json_path = args.out_dir / f"{base}.json"
    md_main_path = args.out_dir / f"{base}.md"
    md_supp_path = args.out_dir / f"{base}-supplementary.md"

    with json_path.open("w", encoding="utf-8") as fh:
        json.dump(rendered, fh, indent=2)
        fh.write("\n")
    md_main_path.write_text(
        render_main_markdown(rendered, args.project_name, args.scope_slug),
        encoding="utf-8",
    )
    md_supp_path.write_text(
        render_supplementary_markdown(rendered, args.project_name, args.scope_slug),
        encoding="utf-8",
    )

    print(f"render: wrote {json_path}, {md_main_path}, {md_supp_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
