#!/usr/bin/env bash
# Generated By: Claude Code (Claude Opus 4.6)
#
# Determines whether to inject external coding standards into the review skill context.
#
# For user-owned repos (origin remote owner matches authenticated GitHub user)
# where ~/source/standards/ exists: outputs the standards CLAUDE.md with all
# relative markdown links rewritten to absolute paths.
#
# For all other repos: outputs nothing (project standards are already in
# context via Claude Code).

set -euo pipefail

gh_user=$(gh api user --jq '.login' 2>/dev/null) || exit 0
url=$(git remote get-url origin 2>/dev/null) || exit 0
url=${url%%/}
owner=${url%/*}
owner=${owner##*[/:]}

[ -d ~/source/standards ] || exit 0
[ "$gh_user" = "$owner" ] || exit 0

# Rewrite relative markdown links to absolute ~/source/standards/ paths.
# Example: [naming](common/naming.md) -> [naming](~/source/standards/common/naming.md)
sed -E 's|\]\(([^)]+)\)|\](~/source/standards/\1)|g' ~/source/standards/CLAUDE.md
