#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.7)
"""Validate a JSON file against a named review-skill schema.

Schema name is auto-detected from the input filename when the --schema flag is
omitted: a file named '<schema-name>.<anything>.json' or '<schema-name>.json'
selects '<schema-name>'. Otherwise --schema must be passed explicitly.

Exits 0 on successful validation, non-zero on any failure.
"""

import argparse
import json
import sys
from pathlib import Path

import jsonschema

SKILL_ROOT = Path(__file__).resolve().parent.parent
PLUGIN_ROOT = SKILL_ROOT.parent.parent
SCHEMAS_DIR = SKILL_ROOT / "schemas"

sys.path.insert(0, str(PLUGIN_ROOT))
from scripts.envelope import safe_load_json, schema_registry  # noqa: E402

KNOWN_SCHEMAS = {
    "agent-output",
    "consolidated",
    "merged-finding",
    "stage-envelope",
    "validation-input",
    "validation-output",
    "render-config",
}


def detect_schema(input_path: Path) -> str | None:
    """Detect schema by filename first (fixtures, explicit naming), then by
    parent directory (live pipeline files under .tmp-review/)."""
    stem = input_path.name
    for known in KNOWN_SCHEMAS:
        if stem.startswith(known + ".") or stem == f"{known}.json":
            return known

    parent = input_path.parent.name
    if parent in ("raw", "00-raw"):
        return "agent-output"
    if parent in ("10-merged", "20-findings"):
        if stem == "_envelope.json":
            return "stage-envelope"
        return "merged-finding"
    if parent in ("validation", "15-validation"):
        if stem.endswith("-input.json"):
            return "validation-input"
        if stem.endswith("-output.json"):
            return "validation-output"
    if parent == ".tmp-review":
        if stem in ("consolidated.json", "post-validation.json"):
            return "consolidated"

    return None


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path, help="path to JSON file to validate")
    parser.add_argument(
        "--schema",
        choices=sorted(KNOWN_SCHEMAS),
        help="schema name (auto-detected from filename when omitted)",
    )
    args = parser.parse_args(argv)

    if not args.input.exists():
        print(f"error: input file not found: {args.input}", file=sys.stderr)
        return 2

    schema_name = args.schema or detect_schema(args.input)
    if schema_name is None:
        print(
            f"error: cannot detect schema from filename '{args.input.name}'; "
            f"pass --schema explicitly. Known schemas: {sorted(KNOWN_SCHEMAS)}",
            file=sys.stderr,
        )
        return 2

    schema_path = SCHEMAS_DIR / f"{schema_name}.schema.json"
    if not schema_path.exists():
        print(f"error: schema file not found: {schema_path}", file=sys.stderr)
        return 2

    try:
        instance = safe_load_json(args.input)
        schema = safe_load_json(schema_path)
    except json.JSONDecodeError as exc:
        print(f"error: invalid JSON: {exc}", file=sys.stderr)
        return 1

    validator = jsonschema.Draft202012Validator(schema, registry=schema_registry())
    errors = sorted(
        validator.iter_errors(instance), key=lambda e: list(e.absolute_path)
    )
    if errors:
        for err in errors:
            location = "/".join(str(p) for p in err.absolute_path) or "<root>"
            print(f"error at {location}: {err.message}", file=sys.stderr)
        return 1

    print(f"OK: {args.input} validates against {schema_name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
