"""Tests for skills/c4-reverse-engineer/scripts/count_source_lines.py."""

import importlib.util
from pathlib import Path

SKILL_ROOT = Path(__file__).resolve().parent.parent
SCRIPT = SKILL_ROOT / "scripts" / "count_source_lines.py"


def _load():
    spec = importlib.util.spec_from_file_location("count_source_lines", SCRIPT)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


class TestIsTestPath:
    def test_tests_dir_is_test(self, tmp_path):
        mod = _load()
        (tmp_path / "tests").mkdir()
        f = tmp_path / "tests" / "foo.py"
        f.write_text("", encoding="utf-8")
        assert mod.is_test_path(f, tmp_path) is True

    def test_nested_test_dir_is_test(self, tmp_path):
        mod = _load()
        nested = tmp_path / "src" / "__tests__"
        nested.mkdir(parents=True)
        f = nested / "a.ts"
        f.write_text("", encoding="utf-8")
        assert mod.is_test_path(f, tmp_path) is True

    def test_test_file_prefix(self, tmp_path):
        mod = _load()
        f = tmp_path / "test_foo.py"
        f.write_text("", encoding="utf-8")
        assert mod.is_test_path(f, tmp_path) is True

    def test_test_file_suffix(self, tmp_path):
        mod = _load()
        f = tmp_path / "foo_test.go"
        f.write_text("", encoding="utf-8")
        assert mod.is_test_path(f, tmp_path) is True

    def test_non_test_file(self, tmp_path):
        mod = _load()
        f = tmp_path / "src" / "foo.py"
        f.parent.mkdir()
        f.write_text("", encoding="utf-8")
        assert mod.is_test_path(f, tmp_path) is False


class TestIsGenerated:
    def test_generated_marker_detected(self, tmp_path):
        mod = _load()
        f = tmp_path / "foo.py"
        f.write_text("# Code generated by the protocol buffer compiler\n", encoding="utf-8")
        assert mod.is_generated(f) is True

    def test_clean_file_not_generated(self, tmp_path):
        mod = _load()
        f = tmp_path / "foo.py"
        f.write_text("def hello():\n    return 1\n", encoding="utf-8")
        assert mod.is_generated(f) is False

    def test_attribution_comment_not_flagged(self, tmp_path):
        mod = _load()
        f = tmp_path / "foo.py"
        # "Generated By: Claude Code" is attribution, not machine output.
        f.write_text("# Generated By: Claude Code (Claude Opus 4.7)\n", encoding="utf-8")
        assert mod.is_generated(f) is False


class TestRecommendTier:
    def test_small_boundary_exact(self):
        mod = _load()
        # 2999 < 3000 → small
        assert mod.recommend_tier(2999).startswith("small")

    def test_medium_lower_boundary(self):
        mod = _load()
        # 3000 is the first "medium"
        assert mod.recommend_tier(3000).startswith("medium")

    def test_medium_upper_boundary(self):
        mod = _load()
        # 14999 < 15000 → still medium
        assert mod.recommend_tier(14999).startswith("medium")

    def test_large_lower_boundary(self):
        mod = _load()
        # 15000 is the first "large"
        assert mod.recommend_tier(15000).startswith("large")

    def test_zero_lines_is_small(self):
        mod = _load()
        assert mod.recommend_tier(0).startswith("small")


class TestWalk:
    def test_skip_dirs_excluded(self, tmp_path):
        mod = _load()
        (tmp_path / "src").mkdir()
        (tmp_path / "src" / "a.py").write_text("x = 1\ny = 2\n", encoding="utf-8")
        # Put a file under node_modules which must be skipped.
        (tmp_path / "node_modules").mkdir()
        (tmp_path / "node_modules" / "junk.py").write_text("x = 1\n" * 500, encoding="utf-8")
        totals = mod.walk(tmp_path)
        # Only src/a.py should count.
        assert "Python" in totals
        files, lines = totals["Python"]
        assert files == 1
        assert lines == 2
