#!/usr/bin/env bash
# Generated By: Claude Code (Claude Opus 4.6)
#
# Determines which standards to audit against and emits subdomain/file lists.
#
# Usage: applicability.sh ["$ARGUMENTS"]
#
# Discovery cascade (first match wins):
#   1. Explicit paths — directories/files passed as arguments
#   2. Repo-local — docs/standards/ in the current repo
#   3. External — ~/source/standards/ (owner-gated: jewzaam/nmalik)
#
# Arguments ($1): space-separated tokens. Each token that is an existing
#   directory or file is a standards source. Tokens after the last file/dir
#   are trailing prose context. Examples:
#     "/path/to/standards"
#     "/path/to/standards focus on logging"
#     "/path/one /path/two"
#     "focus on logging"              (no paths — falls through to cascade)
#     ""                              (no args — falls through to cascade)
#
# Output format (applicable case):
#   SOURCE: explicit|repo-local|external
#   CONTEXT: <prose text>             # only if trailing prose was provided
#   SUBDOMAIN: <name>
#   FILE: <absolute path>
#   MISSING_FILE: <absolute path>     # referenced but not found on disk
#   SUBDOMAIN: <name>
#   ...
#
# Output format (non-applicable case):
#   NOT_APPLICABLE: <reason>

set -euo pipefail

args="${1:-}"

# --- Argument parsing ---
# Walk tokens left-to-right. Collect existing dirs/files as sources.
# Once a token is neither a dir nor a file, everything from that token
# onward is prose context.
sources=()
context=""
if [[ -n "$args" ]]; then
  remaining="$args"
  while [[ -n "$remaining" ]]; do
    token="${remaining%% *}"
    if [[ "$remaining" == "$token" ]]; then
      remaining=""
    else
      remaining="${remaining#"$token" }"
    fi
    if [[ -d "$token" || -f "$token" ]]; then
      sources+=("$token")
    else
      # This token is not a path — it and everything after are context
      if [[ -n "$remaining" ]]; then
        context="$token $remaining"
      else
        context="$token"
      fi
      break
    fi
  done
fi

# --- Index parsing: CLAUDE.md format ---
# Parses ## headings + - [label](path) links. Same logic as the original
# applicability.sh, extracted into a function.
parse_claude_md_index() {
  local index="$1"
  local root="$2"
  awk -v root="$root" '
    BEGIN {
      skip["Maintaining this file"] = 1
      skip["Planned"] = 1
      redirect["Python Templates"] = "Python"
      n_sections = 0
    }
    /^## / {
      section = $0
      sub(/^## +/, "", section)
      if (section in skip) { current = ""; next }
      if (section in redirect) {
        current = redirect[section]
        next
      }
      current = section
      if (!(section in seen)) {
        order[n_sections++] = section
        seen[section] = 1
      }
      next
    }
    /^- \[/ {
      if (current == "") next
      if (match($0, /\]\(([^)]+)\)/, m) == 0) next
      path = m[1]
      if (path ~ /\/README\.md$/) next
      if (path == "README.md") next
      files[current] = files[current] path "\n"
    }
    END {
      for (i = 0; i < n_sections; i++) {
        name = order[i]
        if (!(name in files)) continue
        printf "SUBDOMAIN: %s\n", name
        n = split(files[name], arr, "\n")
        for (j = 1; j <= n; j++) {
          if (arr[j] == "") continue
          resolved = root "/" arr[j]
          probe = (getline _discard < resolved)
          if (probe >= 0) {
            close(resolved)
            printf "FILE: %s\n", resolved
          } else {
            printf "MISSING_FILE: %s\n", resolved
          }
        }
      }
    }
  ' "$index"
}

# --- Index parsing: README.md format ---
# Parses ### headings as subdomains. Extracts links from both:
#   - Markdown list items: - [label](path)
#   - Markdown table cells: | [label](path) |
parse_readme_index() {
  local index="$1"
  local root="$2"
  awk -v root="$root" '
    BEGIN { n_sections = 0; current = "" }
    /^### / {
      section = $0
      sub(/^### +/, "", section)
      current = section
      if (!(section in seen)) {
        order[n_sections++] = section
        seen[section] = 1
      }
      next
    }
    /^## / {
      current = ""
      next
    }
    {
      if (current == "") next
      # Match markdown links in list items or table cells
      line = $0
      while (match(line, /\[([^\]]+)\]\(([^)]+)\)/, m) > 0) {
        path = m[2]
        # Skip README links and external/parent-relative links
        if (path ~ /\/README\.md$/ || path == "README.md") { line = substr(line, RSTART + RLENGTH); continue }
        if (path ~ /^\.\.\//) { line = substr(line, RSTART + RLENGTH); continue }
        if (path ~ /^https?:\/\//) { line = substr(line, RSTART + RLENGTH); continue }
        files[current] = files[current] path "\n"
        line = substr(line, RSTART + RLENGTH)
      }
    }
    END {
      for (i = 0; i < n_sections; i++) {
        name = order[i]
        if (!(name in files)) continue
        printf "SUBDOMAIN: %s\n", name
        n = split(files[name], arr, "\n")
        for (j = 1; j <= n; j++) {
          if (arr[j] == "") continue
          resolved = root "/" arr[j]
          probe = (getline _discard < resolved)
          if (probe >= 0) {
            close(resolved)
            printf "FILE: %s\n", resolved
          } else {
            printf "MISSING_FILE: %s\n", resolved
          }
        }
      }
    }
  ' "$index"
}

# --- Flat directory scan ---
# Lists all *.md files (excluding README.md) under a single subdomain.
parse_flat_dir() {
  local dir="$1"
  local subdomain="${2:-$(basename "$dir")}"
  local files=()
  for f in "$dir"/*.md; do
    [[ -f "$f" ]] || continue
    [[ "$(basename "$f")" == "README.md" ]] && continue
    files+=("$(cd "$(dirname "$f")" && pwd)/$(basename "$f")")
  done
  if [[ ${#files[@]} -eq 0 ]]; then
    return 1
  fi
  printf "SUBDOMAIN: %s\n" "$subdomain"
  for f in "${files[@]}"; do
    printf "FILE: %s\n" "$f"
  done
}

# --- Emit standards from a directory ---
# Tries index files (CLAUDE.md, README.md), falls back to flat scan.
emit_dir_standards() {
  local dir="$1"
  dir="$(cd "$dir" && pwd)"
  if [[ -f "$dir/CLAUDE.md" ]]; then
    parse_claude_md_index "$dir/CLAUDE.md" "$dir"
  elif [[ -f "$dir/README.md" ]]; then
    parse_readme_index "$dir/README.md" "$dir"
  else
    parse_flat_dir "$dir" || return 1
  fi
}

# ============================================================
# Mode 1: Explicit paths
# ============================================================
if [[ ${#sources[@]} -gt 0 ]]; then
  output=""
  any_found=0
  for src in "${sources[@]}"; do
    if [[ -d "$src" ]]; then
      result=$(emit_dir_standards "$src" 2>&1) || true
      if [[ -n "$result" ]]; then
        output+="$result"$'\n'
        any_found=1
      fi
    elif [[ -f "$src" ]]; then
      parent_name=$(basename "$(dirname "$src")")
      [[ "$parent_name" == "." || "$parent_name" == "/" ]] && parent_name="misc"
      abs_path="$(cd "$(dirname "$src")" && pwd)/$(basename "$src")"
      output+="SUBDOMAIN: $parent_name"$'\n'
      output+="FILE: $abs_path"$'\n'
      any_found=1
    fi
  done
  if [[ $any_found -eq 0 ]]; then
    echo "NOT_APPLICABLE: no standards files found in provided paths"
    exit 0
  fi
  echo "SOURCE: explicit"
  [[ -n "$context" ]] && echo "CONTEXT: $context"
  printf "%s" "$output"
  exit 0
fi

# If we had args but no sources matched, all args are context (prose only).
# Fall through to cascade with context preserved.

# ============================================================
# Mode 2: Repo-local docs/standards/
# ============================================================
if [[ -d "docs/standards" ]]; then
  # Check that there are actual .md files (besides README)
  has_md=0
  for f in docs/standards/*.md; do
    [[ -f "$f" ]] || continue
    [[ "$(basename "$f")" == "README.md" ]] && continue
    has_md=1
    break
  done
  if [[ $has_md -eq 1 ]]; then
    abs_dir="$(cd docs/standards && pwd)"
    result=$(emit_dir_standards "$abs_dir" 2>&1) || true
    if [[ -n "$result" ]]; then
      echo "SOURCE: repo-local"
      [[ -n "$context" ]] && echo "CONTEXT: $context"
      printf "%s\n" "$result"
      exit 0
    fi
  fi
fi

# ============================================================
# Mode 3: External fallback ~/source/standards/
# ============================================================
url=$(git remote get-url origin 2>/dev/null) || { echo "NOT_APPLICABLE: no origin remote"; exit 0; }
url=${url%%/}
owner=${url%/*}
owner=${owner##*[/:]}

case "$owner" in
  jewzaam|nmalik) ;;
  *) echo "NOT_APPLICABLE: origin owner '$owner' is not a user-owned repo"; exit 0 ;;
esac

standards_dir="$HOME/source/standards"
index="$standards_dir/CLAUDE.md"
[ -f "$index" ] || { echo "NOT_APPLICABLE: $index not found"; exit 0; }

echo "SOURCE: external"
[[ -n "$context" ]] && echo "CONTEXT: $context"
parse_claude_md_index "$index" "$standards_dir"
