#!/usr/bin/env bash
# Generated By: Claude Code (Claude Opus 4.6)
#
# Determines whether the standards skill applies to the current repository
# and, if so, emits the list of standards subdomains to audit against.
#
# Applicability rules:
#   - origin remote must be owned by the user (GitHub: jewzaam, GitLab: nmalik)
#   - ~/source/standards/ must exist with a parseable CLAUDE.md
#
# Output format (applicable case):
#   SUBDOMAIN: <name>
#   FILE: <absolute path>
#   FILE: <absolute path>
#   SUBDOMAIN: <name>
#   ...
#
# Merge/skip rules:
#   - "Python Templates" bullets are appended to the "Python" subdomain
#   - "Planned" section is skipped (placeholders only)
#   - "Maintaining this file" section is skipped (meta, no standards files)
#   - Links to README.md files are omitted (section indexes, not standards)
#
# Output format (non-applicable case):
#   NOT_APPLICABLE: <reason>

set -euo pipefail

url=$(git remote get-url origin 2>/dev/null) || { echo "NOT_APPLICABLE: no origin remote"; exit 0; }
url=${url%%/}
owner=${url%/*}
owner=${owner##*[/:]}

case "$owner" in
  jewzaam|nmalik) ;;
  *) echo "NOT_APPLICABLE: origin owner '$owner' is not a user-owned repo"; exit 0 ;;
esac

standards_dir="$HOME/source/standards"
index="$standards_dir/CLAUDE.md"
[ -f "$index" ] || { echo "NOT_APPLICABLE: $index not found"; exit 0; }

awk -v root="$standards_dir" '
  BEGIN {
    skip["Maintaining this file"] = 1
    skip["Planned"] = 1
    # section name to redirect into (merge map)
    redirect["Python Templates"] = "Python"
    n_sections = 0
  }
  /^## / {
    section = $0
    sub(/^## +/, "", section)
    if (section in skip) { current = ""; next }
    if (section in redirect) {
      current = redirect[section]
      next
    }
    current = section
    if (!(section in seen)) {
      order[n_sections++] = section
      seen[section] = 1
    }
    next
  }
  /^- \[/ {
    if (current == "") next
    if (match($0, /\]\(([^)]+)\)/, m) == 0) next
    path = m[1]
    if (path ~ /\/README\.md$/) next
    if (path == "README.md") next
    files[current] = files[current] path "\n"
  }
  END {
    for (i = 0; i < n_sections; i++) {
      name = order[i]
      if (!(name in files)) continue
      printf "SUBDOMAIN: %s\n", name
      n = split(files[name], arr, "\n")
      for (j = 1; j <= n; j++) {
        if (arr[j] == "") continue
        printf "FILE: %s/%s\n", root, arr[j]
      }
    }
  }
' "$index"
