#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.7)
"""Render standards-audit findings to the shared handoff JSON plus two markdown
files at the chosen output directory.

The main agent writes an intermediate JSON (the 'pre-render' file) collecting
the per-subdomain gap findings and the supplementary metadata. This script:

1. Assigns stable IDs (C0.., I0.., S0..) per severity bucket.
2. Computes a content hash per finding.
3. Builds the shared `findings.schema.json` envelope with source='standards'.
4. Validates the envelope against the shared schema.
5. Writes JSON + main markdown + supplementary markdown. The markdown is
   always rendered from the JSON — never hand-authored.

Exits non-zero if validation fails; no files are written on validation failure.
"""

import argparse
import json
import logging
import sys
from pathlib import Path

import jsonschema

logger = logging.getLogger("render-standards")

SKILL_ROOT = Path(__file__).resolve().parent.parent
PLUGIN_ROOT = SKILL_ROOT.parent.parent

sys.path.insert(0, str(PLUGIN_ROOT))
from scripts.envelope import (  # noqa: E402
    _line_start,
    assign_ids_per_bucket,
    build_envelope,
    content_hash,
    format_locations_block,
    format_validation_error,
    load_issues_file,
    validate_envelope,
)

SOURCE = "standards"

BUCKET_PREFIX = {
    "critical": "C",
    "important": "I",
    "suggestion": "S",
}
BUCKET_ORDER = ["critical", "important", "suggestion"]


def _standards_sort_key(f: dict) -> tuple:
    """Sort by subdomain, then primary location (path, numeric line start), then title.

    Line is parsed to an int so multi-digit line numbers order correctly
    ('9' before '10'). Range values like '12-20' sort on the start.
    """
    first_loc = f["locations"][0]
    return (
        f["subdomain"],
        first_loc["path"],
        _line_start(first_loc.get("line", "")),
        f["title"],
    )


def _build_standards_envelope(
    pre_render: dict,
    project_name: str,
    scope_slug: str,
    issues: list[dict],
) -> dict:
    project = pre_render.get("project") or {"name": project_name}
    project.setdefault("scope_slug", scope_slug or "standards")

    findings: list[dict] = []
    for raw in pre_render.get("findings", []):
        title = raw.get("title") or "?"
        if "locations" not in raw or not raw["locations"]:
            raise ValueError(
                f'finding "{title}": missing required `locations` array'
            )
        locations = raw["locations"]
        subdomain = raw["subdomain"]
        findings.append(
            {
                "title": title,
                "severity": raw["severity"],
                "locations": locations,
                "issue": raw["issue"],
                "why_it_matters": raw["why_it_matters"],
                "suggested_fix": raw["suggested_fix"],
                "content_hash": content_hash(
                    subdomain,
                    f"{locations[0]['path']}:{locations[0]['line']}",
                    title,
                ),
                "subdomain": subdomain,
            }
        )
    findings = assign_ids_per_bucket(
        findings,
        bucket_order=BUCKET_ORDER,
        prefix_map=BUCKET_PREFIX,
        sort_key=_standards_sort_key,
    )

    return build_envelope(
        source=SOURCE,
        project=project,
        findings=findings,
        issues=issues,
        supplementary=pre_render.get("supplementary") or None,
    )


def _format_finding_block(f: dict) -> str:
    """Format a single finding as a markdown block with subdomain, locations, and prose fields."""
    locations = format_locations_block(f["locations"])
    return (
        f"#### {f['id']}: {f['title']}\n\n"
        f"**Subdomain:** {f['subdomain']}\n\n"
        f"**Locations:**\n{locations}\n\n"
        f"**Issue:** {f['issue']}\n\n"
        f"**Why it matters:** {f['why_it_matters']}\n\n"
        f"**Suggested fix:** {f['suggested_fix']}\n"
    )


def render_main_markdown(envelope: dict, project_name: str) -> str:
    """Render the main standards markdown: TL;DR, applicability matrix, and findings by severity bucket."""
    findings = envelope["findings"]
    by_bucket = {b: [f for f in findings if f["severity"] == b] for b in BUCKET_ORDER}
    supplementary = envelope.get("supplementary", {})

    parts: list[str] = []
    parts.append(f"# Standards Review: {project_name}\n")
    parts.append("## TL;DR\n")
    parts.append(
        supplementary.get(
            "tldr",
            f"{len(by_bucket['critical'])} critical, "
            f"{len(by_bucket['important'])} important, "
            f"{len(by_bucket['suggestion'])} suggestion findings across "
            f"standards subdomains.",
        )
        + "\n"
    )

    applicability = supplementary.get("applicability") or []
    if applicability:
        parts.append("## Applicability Matrix\n")
        parts.append("| Subdomain | Standard | Applies | Gap Count |")
        parts.append("|-----------|----------|---------|-----------|")
        for row in applicability:
            applies = "yes" if row.get("applies") else "no"
            gap_count = row.get("gap_count", "—") if row.get("applies") else "—"
            parts.append(
                f"| {row['subdomain']} | {row['standard']} | {applies} | {gap_count} |"
            )
        parts.append("")

    parts.append("## Findings\n")
    labels = [("critical", "Critical"), ("important", "Important"), ("suggestion", "Suggestions")]
    for bucket, label in labels:
        parts.append(f"### {label}\n")
        if by_bucket[bucket]:
            for f in by_bucket[bucket]:
                parts.append(_format_finding_block(f))
        else:
            parts.append(f"No {label.lower()} issues identified.\n")

    parts.append("## Recommendations\n")
    parts.append(
        "Run `/apply-review Findings-standards.json` to "
        "iteratively fix findings."
    )
    return "\n".join(parts)


def render_supplementary_markdown(envelope: dict, project_name: str) -> str:
    """Render supplementary markdown: strengths, per-subdomain notes, non-applicable standards, and detail by subdomain."""
    findings = envelope["findings"]
    supplementary = envelope.get("supplementary", {})

    parts: list[str] = []
    parts.append(f"# Standards Review (Supplementary): {project_name}\n")

    strengths = supplementary.get("strengths") or []
    parts.append("## Strengths\n")
    if strengths:
        for s in strengths:
            parts.append(f"- {s}")
        parts.append("")
    else:
        parts.append("None recorded.\n")

    subdomain_notes = supplementary.get("subdomain_notes") or {}
    if subdomain_notes:
        parts.append("## Per-Subdomain Notes\n")
        for sub, note in sorted(subdomain_notes.items()):
            parts.append(f"### {sub.title()}\n\n{note}\n")

    not_applicable = supplementary.get("not_applicable") or []
    parts.append("## Non-Applicable Standards\n")
    if not_applicable:
        parts.append("| Standard | Reason |")
        parts.append("|----------|--------|")
        for row in not_applicable:
            parts.append(f"| {row['standard']} | {row['reason']} |")
        parts.append("")
    else:
        parts.append("None recorded.\n")

    parts.append("## Finding Detail by Subdomain\n")
    by_subdomain: dict[str, list[dict]] = {}
    for f in findings:
        by_subdomain.setdefault(f["subdomain"], []).append(f)
    for sub in sorted(by_subdomain):
        parts.append(f"### {sub.title()}\n")
        for f in by_subdomain[sub]:
            parts.append(_format_finding_block(f))

    return "\n".join(parts)


def file_basename() -> str:
    """Filename stem: `Findings-standards`. Matches the plugin-wide convention
    `Findings-<skill-name>` for producer skills — project identity lives in
    the JSON envelope's `project.name`, not in the filename.
    """
    return "Findings-standards"


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        required=True,
        help="pre-render JSON (findings[] + supplementary)",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        required=True,
        help="directory for output files (typically the project root)",
    )
    parser.add_argument(
        "--project-name", required=True, help="project name used in output filenames"
    )
    parser.add_argument(
        "--scope-slug",
        default="standards",
        help="scope slug written into project.scope_slug (defaults to 'standards')",
    )
    parser.add_argument(
        "--issues",
        type=Path,
        default=None,
        help="optional JSON array of meta-issue objects (shared issue shape)",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="verbose diagnostic logging to stderr",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="suppress the success summary line on stdout",
    )
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.DEBUG if args.debug else logging.INFO,
        format="%(levelname)s: %(message)s",
        stream=sys.stderr,
    )
    logger.debug("input=%s out-dir=%s project-name=%s", args.input, args.out_dir, args.project_name)

    try:
        with args.input.open("r", encoding="utf-8") as fh:
            pre_render = json.load(fh)
    except FileNotFoundError:
        logger.error("input file not found: %s", args.input)
        return 1
    except json.JSONDecodeError as exc:
        logger.error("could not parse --input %s: %s", args.input, exc)
        return 1

    try:
        issues = load_issues_file(args.issues)
    except ValueError as exc:
        logger.error("%s", exc)
        return 1

    try:
        envelope = _build_standards_envelope(
            pre_render, args.project_name, args.scope_slug, issues
        )
    except ValueError as exc:
        logger.error("%s", exc)
        return 1

    try:
        validate_envelope(envelope)
    except jsonschema.ValidationError as exc:
        logger.error("%s", format_validation_error(exc, "standards"))
        return 1

    args.out_dir.mkdir(parents=True, exist_ok=True)
    base = file_basename()
    json_path = args.out_dir / f"{base}.json"
    md_main_path = args.out_dir / f"{base}.md"
    md_supp_path = args.out_dir / f"{base}-supplementary.md"

    with json_path.open("w", encoding="utf-8") as fh:
        json.dump(envelope, fh, indent=2)
        fh.write("\n")
    md_main_path.write_text(
        render_main_markdown(envelope, args.project_name), encoding="utf-8"
    )
    md_supp_path.write_text(
        render_supplementary_markdown(envelope, args.project_name), encoding="utf-8"
    )

    if not args.quiet:
        print(f"render-standards: wrote {json_path}, {md_main_path}, {md_supp_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
