#!/usr/bin/env bash
# Generated By: Claude Code (Claude Opus 4.7)
# Bootstrap a per-skill .tmp-<name>/ workspace at the project root.
#
# WIPES the workspace on every invocation to ensure each skill run starts
# from a clean slate. Writes a .gitignore of '*' so nothing inside is
# accidentally committed.
#
# Usage:
#     bootstrap-tmp.sh <dir-name> [subdir1 subdir2 ...]
#
# Example:
#     bootstrap-tmp.sh .tmp-standards
#     bootstrap-tmp.sh .tmp-review raw validation
#
# Honors PROJECT_ROOT env var when set (used by tests); defaults to PWD.

set -euo pipefail

if [ $# -lt 1 ]; then
    echo "usage: bootstrap-tmp.sh <dir-name> [subdirs...]" >&2
    exit 2
fi

DIR_NAME="$1"
shift
SUBDIRS=("$@")

# Input validation — this script wipes the target dir with `rm -rf`, so the
# inputs must not allow path traversal, absolute paths, or wandering outside
# the project root.
#
# DIR_NAME must match the convention `.tmp-<name>`: starts with `.tmp-`,
# then one or more alphanumeric / underscore / hyphen characters, no slashes
# and no `..`.
if ! [[ "$DIR_NAME" =~ ^\.tmp-[A-Za-z0-9_-]+$ ]]; then
    echo "error: dir-name must match '.tmp-<name>' with [A-Za-z0-9_-] only (got: '$DIR_NAME')" >&2
    exit 2
fi

# Subdir names must be single path segments with safe characters — no `/`,
# no `..`, no leading `.`.
for sub in "${SUBDIRS[@]}"; do
    if ! [[ "$sub" =~ ^[A-Za-z0-9_-]+$ ]]; then
        echo "error: subdir names must be single segments matching '[A-Za-z0-9_-]+' (got: '$sub')" >&2
        exit 2
    fi
done

ROOT="${PROJECT_ROOT:-$PWD}"
WORK_DIR="$ROOT/$DIR_NAME"

# Wipe and recreate from scratch.
rm -rf "$WORK_DIR"
mkdir -p "$WORK_DIR"

for sub in "${SUBDIRS[@]}"; do
    mkdir -p "$WORK_DIR/$sub"
done

# Write the .gitignore as a bare '*' with no trailing newline.
printf '*' > "$WORK_DIR/.gitignore"

echo "bootstrap-tmp: $WORK_DIR ready (wiped)"
