#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.7)
"""Shared helpers for the cross-skill findings envelope.

All producer and consumer render scripts in this plugin use this module for
the parts of the pipeline that are identical across skills:

- Read the plugin version (emitted as `schema_version` on every envelope).
- Load and validate a constructed envelope against
  `${plugin_root}/schemas/findings.schema.json`.
- Build the shared-schema envelope with the right optional fields per source.
- Load an optional issues-file argument into a validated list.
- Report a validation error consistently (single-line, no partial writes
  upstream — callers must not write any outputs when validation fails).
- Compute a stable `content_hash` for a finding.
- Assign `id` labels (C0, I1, S2, N0, ...) within each severity bucket.

Skill-specific concerns stay in each skill's render script: pre-render
input parsing, severity mapping (review alone derives it from scores),
the exact context fields fed into `content_hash`, and the markdown
layout — all of which are legitimately per-skill.
"""

import hashlib
import json
from pathlib import Path
from typing import Any, Callable

import jsonschema

PLUGIN_ROOT = Path(__file__).resolve().parent.parent
PLUGIN_MANIFEST_PATH = PLUGIN_ROOT / ".claude-plugin" / "plugin.json"
SHARED_SCHEMA_PATH = PLUGIN_ROOT / "schemas" / "findings.schema.json"


def plugin_version() -> str:
    """Return the current plugin version from `.claude-plugin/plugin.json`.

    The envelope's `schema_version` tracks this value — schema and plugin
    share a lifecycle (the schema is an internal contract of the plugin).
    """
    with PLUGIN_MANIFEST_PATH.open("r", encoding="utf-8") as fh:
        return json.load(fh)["version"]


def load_shared_schema() -> dict:
    with SHARED_SCHEMA_PATH.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def validate_envelope(envelope: dict) -> None:
    """Raise `jsonschema.ValidationError` on failure; return on success."""
    jsonschema.Draft202012Validator(load_shared_schema()).validate(envelope)


def build_envelope(
    *,
    source: str,
    project: dict,
    findings: list[dict] | None = None,
    issues: list[dict] | None = None,
    decomposition: list[dict] | None = None,
    applied: list[dict] | None = None,
    supplementary: dict | None = None,
) -> dict:
    """Construct the shared-schema envelope.

    `schema_version`, `source`, `project`, `findings`, and `issues` are
    always present (findings and issues default to empty lists).
    `decomposition`, `applied`, `supplementary` are included only when
    passed (i.e., the key is absent from the envelope when the argument
    is None).
    """
    envelope: dict[str, Any] = {
        "schema_version": plugin_version(),
        "source": source,
        "project": project,
        "findings": list(findings) if findings is not None else [],
        "issues": list(issues) if issues is not None else [],
    }
    if decomposition is not None:
        envelope["decomposition"] = list(decomposition)
    if applied is not None:
        envelope["applied"] = list(applied)
    if supplementary:
        envelope["supplementary"] = supplementary
    return envelope


def load_issues_file(path: Path | None) -> list[dict]:
    """Load a JSON array of issue objects from `path`, or return an empty
    list when path is None. Raises `ValueError` if the file's top-level
    JSON is not a list."""
    if path is None:
        return []
    with path.open("r", encoding="utf-8") as fh:
        data = json.load(fh)
    if not isinstance(data, list):
        raise ValueError(
            f"--issues file must contain a JSON array, got {type(data).__name__}"
        )
    return data


def format_validation_error(
    exc: jsonschema.ValidationError, source_label: str
) -> str:
    """Format a validation error for stderr. Callers should print the
    result and return a non-zero exit code — no partial output files."""
    location = "/".join(str(p) for p in exc.absolute_path) or "<root>"
    return (
        f"error: rendered {source_label} JSON does not validate against "
        f"{SHARED_SCHEMA_PATH.name}: at {location}: {exc.message}"
    )


def content_hash(*parts: str) -> str:
    """Stable 16-char SHA-256 hex prefix over `|`-joined parts.

    The exact parts are skill-specific (standards uses subdomain + loc +
    title; c4 uses artifact + loc + title; review's consolidator uses
    concern + dimension + loc + title). Callers pass whichever fields
    uniquely identify a finding within their skill.
    """
    return hashlib.sha256("|".join(parts).encode("utf-8")).hexdigest()[:16]


def _default_sort_key(finding: dict) -> tuple:
    """Sort findings within a bucket by primary location + title."""
    locations = finding.get("locations") or [{"path": "", "line": ""}]
    primary = next(
        (
            loc
            for loc in locations
            if loc.get("role", "primary") == "primary"
        ),
        locations[0],
    )
    return (primary.get("path", ""), primary.get("line", ""), finding.get("title", ""))


def assign_ids_per_bucket(
    findings: list[dict],
    *,
    bucket_order: list[str],
    prefix_map: dict[str, str],
    sort_key: Callable[[dict], tuple] | None = None,
) -> list[dict]:
    """Assign stable `id` labels to findings, bucketed by `severity`.

    Each finding gets `id = "<prefix><N>"` where `<prefix>` is the
    `prefix_map[severity]` letter (e.g., `C`, `I`, `S`, `N`) and `<N>` is
    a per-bucket zero-indexed sequence. Findings are returned in
    `bucket_order`; within each bucket they are sorted by `sort_key`
    (defaults to primary location + title).

    Mutates each finding dict to add the `id` key, matching the in-place
    pattern used by callers.

    Raises `ValueError` if any finding's `severity` is not in `bucket_order`.
    """
    by_bucket: dict[str, list[dict]] = {b: [] for b in bucket_order}
    for f in findings:
        sev = f["severity"]
        if sev not in by_bucket:
            raise ValueError(
                f"finding severity '{sev}' not in bucket_order {bucket_order}"
            )
        by_bucket[sev].append(f)

    key = sort_key if sort_key is not None else _default_sort_key
    out: list[dict] = []
    for bucket in bucket_order:
        for i, f in enumerate(sorted(by_bucket[bucket], key=key)):
            f["id"] = f"{prefix_map[bucket]}{i}"
            out.append(f)
    return out
