#!/usr/bin/env bash
# Generated By: Claude Code (Claude Opus 4.6)
# Print CLAUDE_PLUGIN_ROOT with the home directory prefix replaced by ~.
# Used by SKILL.md pre-fetch injections so agents get a ~ path for Bash commands.

set -euo pipefail

echo "${CLAUDE_PLUGIN_ROOT}" | sed "s|^${HOME}|~|"
