#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Resolve all $ref in every *.schema.json, producing *.resolved.schema.json.

Auto-discovers all schema files under the plugin root. Each source schema
gets a resolved sibling with all $ref inlined. Output is deterministic
(sorted keys) for clean diffs.

Usage:
    python scripts/resolve_schema.py          # generate all
    python scripts/resolve_schema.py --check  # stdout only, for CI diffing
"""

import copy
import json
import sys
from pathlib import Path

PLUGIN_ROOT = Path(__file__).resolve().parent.parent

ID_PREFIX = "https://github.com/jewzaam/jewzaam-reviews/"


def discover_schema_pairs() -> list[tuple[Path, Path]]:
    """Find all *.schema.json files, return (source, resolved) pairs."""
    pairs = []
    for source in sorted(PLUGIN_ROOT.rglob("*.schema.json")):
        if ".resolved." in source.name:
            continue
        resolved_name = source.name.replace(".schema.json", ".resolved.schema.json")
        pairs.append((source, source.parent / resolved_name))
    return pairs


SCHEMA_PAIRS = discover_schema_pairs()


def load_schema(path: Path) -> dict:
    return json.loads(path.read_text())


def resolve_ref(ref: str, source_path: Path, cache: dict) -> dict:
    if ref.startswith("#/"):
        schema = load_schema(source_path)
        return _walk_pointer(schema, ref[1:])

    uri, _, fragment = ref.partition("#")

    if uri in cache:
        schema = cache[uri]
    elif uri.startswith(ID_PREFIX):
        rel = uri[len(ID_PREFIX):]
        local_path = PLUGIN_ROOT / rel
        schema = load_schema(local_path)
        cache[uri] = schema
    else:
        raise ValueError(f"Cannot resolve $ref URI: {uri}")

    if fragment:
        return _walk_pointer(schema, fragment)
    return schema


def _walk_pointer(schema: dict, pointer: str) -> dict:
    parts = pointer.strip("/").split("/")
    node = schema
    for part in parts:
        node = node[part]
    return copy.deepcopy(node)


def resolve_all_refs(node, source_path: Path, cache: dict):
    if isinstance(node, dict):
        if "$ref" in node:
            resolved = resolve_ref(node["$ref"], source_path, cache)
            return resolve_all_refs(resolved, source_path, cache)
        return {k: resolve_all_refs(v, source_path, cache) for k, v in node.items()}
    if isinstance(node, list):
        return [resolve_all_refs(item, source_path, cache) for item in node]
    return node


def resolve_schema(source_path: Path) -> dict:
    schema = load_schema(source_path)
    cache: dict = {}
    resolved = resolve_all_refs(schema, source_path, cache)

    resolved.pop("$id", None)
    resolved.pop("$schema", None)
    resolved.pop("$defs", None)

    resolved["_generated"] = (
        "DO NOT EDIT. Generated by scripts/resolve_schema.py from "
        + source_path.name
        + ". Edit the source schema, then run: make resolve-schemas"
    )

    return resolved


def main():
    check_mode = "--check" in sys.argv

    for source_path, output_path in SCHEMA_PAIRS:
        resolved = resolve_schema(source_path)
        content = json.dumps(resolved, indent=2, sort_keys=True) + "\n"

        if check_mode:
            sys.stdout.write(content)
        else:
            output_path.write_text(content)
            print(f"Wrote {output_path.relative_to(PLUGIN_ROOT)}")


if __name__ == "__main__":
    main()
