#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.7)
"""Validate semantic versioning for the jewzaam-reviews plugin.

Checks:

1. **Semver format** — `.claude-plugin/plugin.json` `version` matches the
   official semver regex (X.Y.Z with optional pre-release / build).
2. **Sources match** — `plugin.json` `version` equals
   `marketplace.json` `plugins[0].version`.
3. **Schema version aligned** — every `schema_version` in the
   `schemas/examples/*.json` fixtures matches the current plugin version.
   (Render scripts read the plugin version at runtime; fixtures are
   static and must be hand-updated on every bump. This check catches
   forgotten fixture updates.)
4. **Version bumped** — if source dirs (default: `schemas/ skills/`) changed
   relative to the mainline branch, the version must differ from mainline.

Adapted from the standards template at
`~/source/standards/python/templates/version-check.sh`, which reads
`pyproject.toml`. This plugin's version sources are JSON, so the script is
Python for portable JSON parsing (no jq dependency on dev or CI hosts).

Exit 0 on PASS, non-zero on FAIL. Prints a single-line summary.

Usage:
    python scripts/version-check.py [--source-dir DIR]...
"""

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PLUGIN_JSON = REPO_ROOT / ".claude-plugin" / "plugin.json"
MARKETPLACE_JSON = REPO_ROOT / ".claude-plugin" / "marketplace.json"
SCHEMA_EXAMPLES_DIR = REPO_ROOT / "schemas" / "examples"

# Official semver.org regex
SEMVER_RE = re.compile(
    r"^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)"
    r"(-((0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)"
    r"(\.(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?"
    r"(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$"
)

DEFAULT_SOURCE_DIRS = ["schemas", "skills"]


def read_plugin_version() -> str:
    with PLUGIN_JSON.open("r", encoding="utf-8") as fh:
        data = json.load(fh)
    return data["version"]


def read_marketplace_version() -> str:
    with MARKETPLACE_JSON.open("r", encoding="utf-8") as fh:
        data = json.load(fh)
    plugins = data.get("plugins", [])
    target = next(
        (p for p in plugins if p.get("name") == "jewzaam-reviews"),
        plugins[0] if plugins else {},
    )
    return target["version"]


def _git(*args: str) -> str:
    result = subprocess.run(
        ["git", *args],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    return result.stdout.strip()


def _git_ok(*args: str) -> bool:
    result = subprocess.run(
        ["git", *args],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    return result.returncode == 0


def find_mainline() -> str | None:
    for ref in ("main", "origin/main", "master", "origin/master"):
        if _git_ok("rev-parse", "--verify", ref):
            return ref
    return None


def version_at_revision(revision: str) -> str | None:
    """Return plugin.json version at a given git revision, or None."""
    blob = _git("show", f"{revision}:.claude-plugin/plugin.json")
    if not blob:
        return None
    try:
        data = json.loads(blob)
    except json.JSONDecodeError:
        return None
    return data.get("version")


def source_changed(base: str, head: str, source_dirs: list[str]) -> bool:
    changed = _git("diff", "--name-only", base, head, "--", *source_dirs)
    return bool(changed.strip())


def _find_misaligned_fixtures(plugin_ver: str) -> list[tuple[Path, str]]:
    """Return [(path, bad_version), ...] for every fixture whose
    schema_version differs from the plugin version. Empty list = all aligned."""
    if not SCHEMA_EXAMPLES_DIR.exists():
        return []
    mismatched: list[tuple[Path, str]] = []
    for path in sorted(SCHEMA_EXAMPLES_DIR.glob("*.json")):
        try:
            with path.open("r", encoding="utf-8") as fh:
                doc = json.load(fh)
        except (OSError, json.JSONDecodeError):
            continue
        fixture_ver = doc.get("schema_version")
        if fixture_ver is None:
            continue
        if fixture_ver != plugin_ver:
            mismatched.append((path, fixture_ver))
    return mismatched


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source-dir",
        action="append",
        default=None,
        help=(
            "directory that triggers the bump-required rule (default: "
            "'schemas' and 'skills'; pass multiple --source-dir flags "
            "to override)"
        ),
    )
    args = parser.parse_args(argv)
    source_dirs = args.source_dir or DEFAULT_SOURCE_DIRS

    # 1. Read versions from both files.
    try:
        plugin_ver = read_plugin_version()
    except (OSError, KeyError, json.JSONDecodeError) as exc:
        print(
            f"version-check: FAIL — could not read version from "
            f"{PLUGIN_JSON.relative_to(REPO_ROOT)}: {exc}",
            file=sys.stderr,
        )
        return 1

    try:
        marketplace_ver = read_marketplace_version()
    except (OSError, KeyError, json.JSONDecodeError) as exc:
        print(
            f"version-check: FAIL — could not read version from "
            f"{MARKETPLACE_JSON.relative_to(REPO_ROOT)}: {exc}",
            file=sys.stderr,
        )
        return 1

    # 2. Semver format.
    if not SEMVER_RE.match(plugin_ver):
        print(
            f"version-check: FAIL — plugin.json version '{plugin_ver}' is not "
            "valid semver (see https://semver.org)",
            file=sys.stderr,
        )
        return 1

    # 3. Sources match.
    if plugin_ver != marketplace_ver:
        print(
            f"version-check: FAIL — plugin.json has '{plugin_ver}' but "
            f"marketplace.json has '{marketplace_ver}'. The two must stay in sync.",
            file=sys.stderr,
        )
        return 1

    # 4. Fixture schema_version alignment.
    mismatched = _find_misaligned_fixtures(plugin_ver)
    if mismatched:
        print(
            f"version-check: FAIL — {len(mismatched)} fixture(s) have "
            f"schema_version out of sync with plugin version '{plugin_ver}':",
            file=sys.stderr,
        )
        for path, version in mismatched:
            rel = path.relative_to(REPO_ROOT)
            print(f"  {rel}: {version}", file=sys.stderr)
        print(
            "Update each fixture's schema_version to match the plugin "
            "version. (Render scripts read the plugin version at runtime; "
            "only static fixtures need manual updates.)",
            file=sys.stderr,
        )
        return 1

    # 5. Bump check against mainline.
    mainline = find_mainline()
    if mainline is None:
        print(
            f"version-check: PASS — {plugin_ver} (no mainline branch found, "
            "bump check skipped)"
        )
        return 0

    base = _git("merge-base", "HEAD", mainline)
    if not base:
        print(
            f"version-check: PASS — {plugin_ver} (no common ancestor with "
            f"{mainline})"
        )
        return 0

    if not source_changed(base, "HEAD", source_dirs):
        print(
            f"version-check: PASS — {plugin_ver} (no source changes in: "
            f"{' '.join(source_dirs)})"
        )
        return 0

    base_ver = version_at_revision(base)
    if base_ver and base_ver == plugin_ver:
        print(
            f"version-check: FAIL — version not bumped: both current and "
            f"{mainline} have '{plugin_ver}'. Source files in "
            f"{source_dirs} changed; bump the MINOR or MAJOR in both "
            f"plugin.json and marketplace.json.",
            file=sys.stderr,
        )
        return 1

    print(
        f"version-check: PASS — {base_ver or 'new'} -> {plugin_ver}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
