#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Bump the plugin version across all files that carry it.

Updates:
  - .claude-plugin/plugin.json       (version)
  - .claude-plugin/marketplace.json  (plugins[0].version)
  - schemas/examples/*.json          (schema_version)

Usage:
    python scripts/version-bump.py <new-version>
    python scripts/version-bump.py patch   # 0.2.3 → 0.2.4
    python scripts/version-bump.py minor   # 0.2.3 → 0.3.0
    python scripts/version-bump.py major   # 0.2.3 → 1.0.0
"""

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PLUGIN_JSON = REPO_ROOT / ".claude-plugin" / "plugin.json"
MARKETPLACE_JSON = REPO_ROOT / ".claude-plugin" / "marketplace.json"
SCHEMA_EXAMPLES_DIR = REPO_ROOT / "schemas" / "examples"

SEMVER_RE = re.compile(
    r"^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$"
)


def read_current_version() -> str:
    with PLUGIN_JSON.open("r", encoding="utf-8") as fh:
        return json.load(fh)["version"]


def compute_new_version(current: str, target: str) -> str:
    if SEMVER_RE.match(target):
        return target

    m = SEMVER_RE.match(current)
    if not m:
        print(f"error: current version '{current}' is not valid semver", file=sys.stderr)
        sys.exit(1)

    major, minor, patch = int(m.group(1)), int(m.group(2)), int(m.group(3))

    if target == "patch":
        return f"{major}.{minor}.{patch + 1}"
    if target == "minor":
        return f"{major}.{minor + 1}.0"
    if target == "major":
        return f"{major + 1}.0.0"

    print(f"error: '{target}' is not a valid version or bump type (patch/minor/major)", file=sys.stderr)
    sys.exit(1)


def update_json_file(path: Path, updater):
    with path.open("r", encoding="utf-8") as fh:
        data = json.load(fh)
    updater(data)
    with path.open("w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=2)
        fh.write("\n")


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("version", help="new version (e.g., 0.3.0) or bump type (patch/minor/major)")
    args = parser.parse_args(argv)

    current = read_current_version()
    new_ver = compute_new_version(current, args.version)

    if new_ver == current:
        print(f"version is already {current}")
        return 0

    update_json_file(PLUGIN_JSON, lambda d: d.__setitem__("version", new_ver))

    update_json_file(MARKETPLACE_JSON, lambda d: d["plugins"].__getitem__(0).__setitem__("version", new_ver))

    fixtures_updated = 0
    for path in sorted(SCHEMA_EXAMPLES_DIR.glob("*.json")):
        with path.open("r", encoding="utf-8") as fh:
            data = json.load(fh)
        if "schema_version" in data:
            data["schema_version"] = new_ver
            with path.open("w", encoding="utf-8") as fh:
                json.dump(data, fh, indent=2)
                fh.write("\n")
            fixtures_updated += 1

    print(f"{current} → {new_ver}")
    print(f"  updated: plugin.json, marketplace.json, {fixtures_updated} fixture(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
