#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.7)
"""Render the update-pr traceability document.

Consumes a pre-render JSON authored by the main agent and emits:

1. `Findings-update-pr-<number>.json` — the authoritative handoff validated
   against `${plugin_root}/schemas/findings.schema.json` with
   `source: "review"` (findings carry optional `pr_comment` links).
2. `Findings-update-pr-<number>.md` — the human-readable traceability document,
   rendered from the JSON. **Never hand-authored.**

The same script runs twice per update-pr session:

- End of Phase 1: resolutions absent → markdown shows only the traceability
  tables and findings list.
- End of Phase 4: resolutions populated in `supplementary.resolutions` →
  markdown additionally renders draft replies, re-requests, applied
  suggestions, and pending-local-edit sections.

Exits non-zero on validation failure; no files are written on failure.
"""

import argparse
import json
import logging
import sys
from pathlib import Path

import jsonschema

logger = logging.getLogger("render-update-pr")

SKILL_ROOT = Path(__file__).resolve().parent.parent
PLUGIN_ROOT = SKILL_ROOT.parent.parent

sys.path.insert(0, str(PLUGIN_ROOT))
from scripts.envelope import (  # noqa: E402
    assign_ids_per_bucket,
    build_envelope,
    content_hash,
    format_locations_block,
    format_validation_error,
    load_issues_file,
    validate_envelope,
)

BUCKET_ORDER = ["critical", "important", "suggestion", "needs-review"]
BUCKET_PREFIX = {
    "critical": "C",
    "important": "I",
    "suggestion": "S",
    "needs-review": "N",
}

SOURCE = "review"  # update-pr produces a review-shaped handoff


def _content_hash_for_finding(finding: dict) -> str:
    loc = finding["locations"][0]
    return content_hash(
        "update-pr", f"{loc['path']}:{loc['line']}", finding["title"]
    )


def _build_pr_envelope(pre_render: dict, pr_number: int, issues: list[dict]) -> dict:
    """Build the update-pr envelope with review-shaped findings and optional pr_comment links.

    Normalizes findings with default severity ('important') and dimensions
    when fields are absent from the pre-render input.
    """
    _DEFAULT_JUSTIFICATION = "Assigned by update-pr default (no upstream dimension data)"
    project = pre_render.get("project") or {"name": pre_render.get("repo", "pr")}
    project.setdefault("scope_slug", f"pr-{pr_number}")

    findings: list[dict] = []
    for raw in pre_render.get("findings", []):
        finding = {
            "title": raw["title"],
            "severity": raw.get("severity", "important"),
            "locations": raw["locations"],
            "issue": raw["issue"],
            "why_it_matters": raw["why_it_matters"],
            "suggested_fix": raw["suggested_fix"],
            "content_hash": raw.get("content_hash") or _content_hash_for_finding(raw),
            "concern_slug": raw.get("concern_slug", "implementation"),
            "source_dimensions": raw.get("source_dimensions", [f"pr-{pr_number}"]),
            "runtime_scope": raw.get("runtime_scope", "service-internal"),
            "runtime_scope_justification": raw.get("runtime_scope_justification", _DEFAULT_JUSTIFICATION),
            "failure_mode": raw.get("failure_mode", "degraded-behavior"),
            "failure_mode_justification": raw.get("failure_mode_justification", _DEFAULT_JUSTIFICATION),
            "evidence_quality": raw.get("evidence_quality", "inferred"),
            "evidence_quality_justification": raw.get("evidence_quality_justification", _DEFAULT_JUSTIFICATION),
            "trace_origin": raw.get("trace_origin", "component"),
            "trace_origin_justification": raw.get("trace_origin_justification", _DEFAULT_JUSTIFICATION),
            "effort_to_fix": raw.get("effort_to_fix", "small"),
            "effort_to_fix_justification": raw.get("effort_to_fix_justification", _DEFAULT_JUSTIFICATION),
        }
        if "pr_comment" in raw:
            finding["pr_comment"] = raw["pr_comment"]
        findings.append(finding)

    # IDs are derived from severity via the shared helper. Pre-render JSON
    # must NOT supply `id` — it is asigned per-bucket here.
    findings = assign_ids_per_bucket(
        findings,
        bucket_order=BUCKET_ORDER,
        prefix_map=BUCKET_PREFIX,
    )

    supplementary = pre_render.get("supplementary", {})
    supplementary.setdefault("pr_number", pr_number)

    decomposition = pre_render.get("decomposition") or [
        {
            "dimension_name": f"PR {pr_number}",
            "dimension_slug": f"pr-{pr_number}",
        }
    ]

    return build_envelope(
        source=SOURCE,
        project=project,
        decomposition=decomposition,
        findings=findings,
        issues=issues,
        supplementary=supplementary or None,
    )


def _finding_block(f: dict) -> str:
    pr = f.get("pr_comment")
    pr_line = ""
    if pr:
        pr_line = (
            f"- **PR comment:** {pr.get('author', '?')} #{pr.get('id', '?')}\n"
        )
    locations = format_locations_block(f["locations"])
    return (
        f"**<{f['id']}>: {f['title']}**\n"
        f"{pr_line}"
        f"- **Locations:**\n{locations}\n"
        f"- **Description:** {f['issue']}\n"
        f"- **Suggested fix:** {f['suggested_fix']}\n"
    )


def _render_header(supplementary: dict) -> list[str]:
    pr_number = supplementary.get("pr_number", "?")
    parts: list[str] = [f"# Review Traceability: PR {pr_number}\n"]
    pr_title = supplementary.get("pr_title", "")
    if pr_title:
        parts.append(f"PR: {pr_title}\n")
    counts = supplementary.get("counts", {})
    if counts:
        parts.append(
            f"Total comments: {counts.get('total', '?')} "
            f"({counts.get('resolved', '?')} resolved, "
            f"{counts.get('unresolved', '?')} unresolved)\n"
        )
    return parts


def _render_traceability(supplementary: dict) -> list[str]:
    parts: list[str] = [
        "## Comment Traceability\n",
        "All unresolved PR comments, mapped to findings. Resolved comments excluded.\n",
    ]
    traceability = supplementary.get("traceability") or {}
    if not traceability:
        return parts
    for reviewer, rows in sorted(traceability.items()):
        parts.append(f"### {reviewer} ({len(rows)} threads)\n")
        has_resolution = any("resolution" in r for r in rows)
        if has_resolution:
            parts.append("| # | Comment | File | Finding | Resolution |")
            parts.append("|---|---------|------|---------|------------|")
            for i, row in enumerate(rows, start=1):
                parts.append(
                    f"| {i} | {row.get('summary', '')} | "
                    f"`{row.get('location', '')}` | "
                    f"{row.get('finding', '—')} | "
                    f"{row.get('resolution', '')} |"
                )
        else:
            parts.append("| # | Comment | File | Finding |")
            parts.append("|---|---------|------|---------|")
            for i, row in enumerate(rows, start=1):
                parts.append(
                    f"| {i} | {row.get('summary', '')} | "
                    f"`{row.get('location', '')}` | "
                    f"{row.get('finding', '—')} |"
                )
        parts.append("")
    return parts


def _render_findings(findings: list[dict]) -> list[str]:
    parts: list[str] = ["## Findings\n"]
    if findings:
        for f in findings:
            parts.append(_finding_block(f))
    else:
        parts.append("No findings.\n")
    return parts


def _render_resolutions(supplementary: dict) -> list[str]:
    resolutions = supplementary.get("resolutions")
    if not resolutions:
        return []

    parts: list[str] = ["## Resolutions\n"]

    draft_replies = resolutions.get("draft_replies") or []
    if draft_replies:
        parts.append("### Draft Replies\n")
        for r in draft_replies:
            parts.append(
                f"- [ ] **{r.get('reviewer', '?')} on `{r.get('location', '?')}`** "
                f"[{r.get('decision', '')}]"
            )
            parts.append(f"  > {r.get('summary', '')}")
            parts.append(f"  **Draft reply:** {r.get('reply', '')}")
        parts.append("")

    re_request = resolutions.get("re_request") or []
    if re_request:
        parts.append("### Re-Request Reviews\n")
        for r in re_request:
            parts.append(
                f"- [ ] **{r.get('reviewer', '?')}** — {r.get('note', '')}"
            )
        parts.append("")

    applied_github = resolutions.get("applied_via_github_suggestions") or []
    if applied_github:
        parts.append("### Applied via GitHub Suggestions\n")
        for r in applied_github:
            parts.append(
                f"- {r.get('reviewer', '?')} on `{r.get('location', '?')}` "
                f"— {r.get('summary', '')}"
            )
        parts.append("")

    pending = resolutions.get("pending_local_edits") or []
    if pending:
        parts.append("### Pending Local Edits\n")
        for r in pending:
            parts.append(
                f"- {r.get('reviewer', '?')} on `{r.get('location', '?')}` — "
                f"{r.get('finding', '?')} — {r.get('summary', '')}"
            )
        parts.append("")

    no_action = resolutions.get("no_action") or []
    if no_action:
        parts.append("### No Action Needed\n")
        for r in no_action:
            parts.append(f"- {r.get('reviewer', '?')} — {r.get('summary', '')}")
        parts.append("")

    return parts


def render_markdown(envelope: dict) -> str:
    """Render the update-pr traceability markdown: header, comment traceability, findings, and resolutions."""
    supplementary = envelope.get("supplementary", {})
    parts: list[str] = []
    parts.extend(_render_header(supplementary))
    parts.extend(_render_traceability(supplementary))
    parts.extend(_render_findings(envelope["findings"]))
    parts.extend(_render_resolutions(supplementary))
    return "\n".join(parts)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        required=True,
        help="pre-render JSON (findings[] + supplementary)",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        required=True,
        help="directory for output files (typically the project root)",
    )
    parser.add_argument(
        "--pr-number", type=int, required=True, help="PR number (positive integer)"
    )
    parser.add_argument(
        "--issues",
        type=Path,
        default=None,
        help="optional JSON array of meta-issue objects (shared issue shape)",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="verbose diagnostic logging to stderr",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="suppress the success summary line on stdout",
    )
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.DEBUG if args.debug else logging.INFO,
        format="%(levelname)s: %(message)s",
        stream=sys.stderr,
    )
    logger.debug("input=%s out-dir=%s pr-number=%s", args.input, args.out_dir, args.pr_number)

    if args.pr_number < 1:
        parser.error(f"--pr-number must be a positive integer, got {args.pr_number}")

    try:
        with args.input.open("r", encoding="utf-8") as fh:
            pre_render = json.load(fh)
    except FileNotFoundError:
        logger.error("input file not found: %s", args.input)
        return 1
    except json.JSONDecodeError as exc:
        logger.error(
            "could not parse --input %s: %s (line %d, col %d)",
            args.input, exc, exc.lineno, exc.colno,
        )
        return 1

    try:
        issues = load_issues_file(args.issues)
    except ValueError as exc:
        logger.error("%s", exc)
        return 1

    envelope = _build_pr_envelope(pre_render, args.pr_number, issues)

    try:
        validate_envelope(envelope)
    except jsonschema.ValidationError as exc:
        logger.error("%s", format_validation_error(exc, "update-pr"))
        return 1

    args.out_dir.mkdir(parents=True, exist_ok=True)
    base = f"Findings-update-pr-{args.pr_number}"
    json_path = args.out_dir / f"{base}.json"
    md_path = args.out_dir / f"{base}.md"

    with json_path.open("w", encoding="utf-8") as fh:
        json.dump(envelope, fh, indent=2)
        fh.write("\n")
    md_path.write_text(render_markdown(envelope), encoding="utf-8")

    if not args.quiet:
        print(f"render-update-pr: wrote {json_path}, {md_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
