#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Enumerate every platform conditional in a project.

Finds occurrences of:
    - sys.platform / platform.system() / platform.machine()
    - os.name
    - project-specific IS_WINDOWS / IS_LINUX / IS_MAC / IS_DARWIN style constants
    - Go build tags (// +build, //go:build)
    - Rust #[cfg(target_os = ...)]
    - C/C++ #ifdef __linux__, __APPLE__, _WIN32, etc.

Feeds PLATFORM verification claims in Phase 3 of the c4-reverse-engineer skill. Every
reported hit should appear in the generated spec's platform-branch coverage.

Usage:
    python skills/c4-reverse-engineer/scripts/find_platform_conditionals.py [root]
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

SKIP_DIRS: set[str] = {
    ".git", ".hg", ".svn", "node_modules", "venv", ".venv", "__pycache__",
    "build", "dist", "target", "out", ".tox", ".pytest_cache", ".mypy_cache",
    ".ruff_cache", ".next", ".nuxt", "vendor", "third_party", "external",
    "coverage", "htmlcov", "site-packages", ".idea", ".vscode",
}

SOURCE_EXTENSIONS: set[str] = {
    ".py", ".ts", ".tsx", ".js", ".jsx", ".go", ".rs", ".java", ".kt",
    ".c", ".h", ".cpp", ".cc", ".hpp", ".cs", ".rb", ".php", ".swift",
    ".sh", ".bash", ".zsh",
}

TEST_DIR_NAMES: set[str] = {"tests", "test", "__tests__", "spec", "specs", "testdata"}
TEST_FILE_PREFIXES: tuple[str, ...] = ("test_",)
TEST_FILE_SUFFIXES: tuple[str, ...] = (
    "_test.py", "_test.go", ".test.ts", ".test.tsx", ".test.js",
    ".spec.ts", ".spec.tsx", ".spec.js",
)


def is_test_path(path: Path, root: Path) -> bool:
    try:
        rel_parts = path.relative_to(root).parts
    except ValueError:
        rel_parts = path.parts
    for part in rel_parts[:-1]:
        if part.lower() in TEST_DIR_NAMES:
            return True
    name = path.name
    if any(name.startswith(p) for p in TEST_FILE_PREFIXES):
        return True
    return any(name.endswith(s) for s in TEST_FILE_SUFFIXES)

# One regex per pattern category. Each capturing group is the match text shown in output.
PATTERNS: dict[str, re.Pattern[str]] = {
    "sys.platform": re.compile(r"\bsys\.platform\b"),
    "platform.system": re.compile(r"\bplatform\.system\s*\("),
    "platform.machine": re.compile(r"\bplatform\.machine\s*\("),
    "os.name": re.compile(r"\bos\.name\b"),
    "IS_WINDOWS/LINUX/MAC const": re.compile(r"\bIS_(WINDOWS|LINUX|MAC|DARWIN|OSX|WIN32)\b"),
    "Go build tag": re.compile(r"^//\s*(\+build|go:build)\b"),
    "Rust cfg(target_os)": re.compile(r"#\[cfg\s*\(\s*target_os\b"),
    "C/C++ platform ifdef": re.compile(r"#\s*if(?:def|ndef)?\s+(_WIN32|_WIN64|WIN32|__linux__|__APPLE__|__MACH__|__unix__|__FreeBSD__)"),
    "TypeScript process.platform": re.compile(r"\bprocess\.platform\b"),
    "navigator.userAgent": re.compile(r"\bnavigator\.userAgent\b"),
}


def scan_file(path: Path) -> list[tuple[str, int, str]]:
    hits: list[tuple[str, int, str]] = []
    try:
        with path.open("r", encoding="utf-8", errors="replace") as f:
            for lineno, line in enumerate(f, 1):
                for label, pattern in PATTERNS.items():
                    if pattern.search(line):
                        hits.append((label, lineno, line.rstrip()))
                        break
    except OSError:
        pass
    return hits


def walk(root: Path):
    import os
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS and not d.startswith(".")]
        for fname in filenames:
            path = Path(dirpath) / fname
            if path.suffix.lower() in SOURCE_EXTENSIONS:
                yield path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("root", nargs="?", default=".", help="Project root (default: cwd)")
    parser.add_argument(
        "--include-tests",
        action="store_true",
        help="Include test files (default: excluded — tests often mock these constants)",
    )
    args = parser.parse_args(argv)

    root = Path(args.root).resolve()
    if not root.is_dir():
        print(f"find_platform_conditionals: error: not a directory: {root}", file=sys.stderr)
        return 1

    total = 0
    by_category: dict[str, int] = {}
    for path in walk(root):
        if not args.include_tests and is_test_path(path, root):
            continue
        hits = scan_file(path)
        if not hits:
            continue
        rel = path.relative_to(root)
        for label, lineno, text in hits:
            print(f"{rel}:{lineno}: [{label}] {text.strip()[:120]}")
            by_category[label] = by_category.get(label, 0) + 1
            total += 1

    print()
    print(f"{total} platform conditional(s) found")
    if by_category:
        for label, count in sorted(by_category.items(), key=lambda kv: -kv[1]):
            print(f"  {count:>4}  {label}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
