#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.7)
"""Render C4-validation findings to the shared handoff JSON plus a markdown
companion.

The main agent collects Phase 6 validation findings (artifact + verdict +
spec_says + code_says + evidence + impact) into a pre-render JSON. This script:

1. Assigns stable IDs (C0.., I0.., S0..) per severity bucket.
2. Computes a content hash per finding.
3. Builds the shared-schema envelope with source='c4-validation'.
4. Validates against `${plugin_root}/schemas/findings.schema.json`.
5. Writes `Findings-c4-reverse-engineer.json` + `.md`. Markdown is always rendered
   from the JSON.

Exits non-zero if validation fails; no files are written on validation failure.
"""

import argparse
import json
import sys
from pathlib import Path

import jsonschema

SKILL_ROOT = Path(__file__).resolve().parent.parent
PLUGIN_ROOT = SKILL_ROOT.parent.parent

sys.path.insert(0, str(PLUGIN_ROOT))
from scripts.envelope import (  # noqa: E402
    assign_ids_per_bucket,
    build_envelope,
    content_hash,
    format_validation_error,
    load_issues_file,
    validate_envelope,
)

SOURCE = "c4-validation"

BUCKET_PREFIX = {"critical": "C", "important": "I", "suggestion": "S"}
BUCKET_ORDER = ["critical", "important", "suggestion"]


def _c4_sort_key(f: dict) -> tuple:
    return (f["artifact"], f["title"])


def _build_c4_envelope(
    pre_render: dict, project_name: str, issues: list[dict]
) -> dict:
    project = pre_render.get("project") or {"name": project_name}
    project.setdefault("scope_slug", "c4-validation")

    findings: list[dict] = []
    for raw in pre_render.get("findings", []):
        locations = raw.get("locations") or []
        if not locations:
            raise ValueError(
                f"c4-validation finding '{raw.get('title', '<no title>')}' has no "
                "locations; must cite both the artifact section and the code line"
            )
        findings.append(
            {
                "title": raw["title"],
                "severity": raw["severity"],
                "locations": locations,
                "issue": raw["issue"],
                "why_it_matters": raw["why_it_matters"],
                "suggested_fix": raw["suggested_fix"],
                "content_hash": content_hash(
                    raw["artifact"],
                    f"{locations[0]['path']}:{locations[0]['line']}",
                    raw["title"],
                ),
                "artifact": raw["artifact"],
                "verdict": raw["verdict"],
                "spec_says": raw["spec_says"],
                "code_says": raw["code_says"],
                "evidence": raw["evidence"],
            }
        )
    findings = assign_ids_per_bucket(
        findings,
        bucket_order=BUCKET_ORDER,
        prefix_map=BUCKET_PREFIX,
        sort_key=_c4_sort_key,
    )

    return build_envelope(
        source=SOURCE,
        project=project,
        findings=findings,
        issues=issues,
        supplementary=pre_render.get("supplementary") or None,
    )


def _format_finding_block(f: dict) -> str:
    locs = "\n".join(
        f"- `{loc['path']}:{loc['line']}`"
        + (f" ({loc['role']})" if loc.get("role") and loc["role"] != "primary" else "")
        for loc in f["locations"]
    )
    return (
        f"### {f['id']}: {f['title']}\n\n"
        f"**Artifact:** {f['artifact']}\n\n"
        f"**Verdict:** {f['verdict']}\n\n"
        f"**Spec says:** {f['spec_says']}\n\n"
        f"**Code says:** {f['code_says']}\n\n"
        f"**Evidence:** {f['evidence']}\n\n"
        f"**Locations:**\n{locs}\n\n"
        f"**Issue:** {f['issue']}\n\n"
        f"**Why it matters:** {f['why_it_matters']}\n\n"
        f"**Suggested fix:** {f['suggested_fix']}\n"
    )


def render_markdown(envelope: dict, project_name: str) -> str:
    findings = envelope["findings"]
    by_bucket = {b: [f for f in findings if f["severity"] == b] for b in BUCKET_ORDER}
    supplementary = envelope.get("supplementary", {})

    parts: list[str] = []
    parts.append(f"# Review: C4 Validation — {project_name}\n")

    summary = supplementary.get("summary") or []
    if summary:
        parts.append("## Summary\n")
        parts.append("| Artifact | Confirmed | Critical | Important | Suggestion |")
        parts.append("|----------|-----------|----------|-----------|------------|")
        for row in summary:
            parts.append(
                f"| {row['artifact']} | {row.get('confirmed', 0)} | "
                f"{row.get('critical', 0)} | {row.get('important', 0)} | "
                f"{row.get('suggestion', 0)} |"
            )
        parts.append("")

    labels = [
        ("critical", "Critical"),
        ("important", "Important"),
        ("suggestion", "Suggestion"),
    ]
    for bucket, label in labels:
        parts.append(f"## {label}\n")
        if by_bucket[bucket]:
            for f in by_bucket[bucket]:
                parts.append(_format_finding_block(f))
        else:
            parts.append(f"No {label.lower()} issues identified.\n")

    confirmed = supplementary.get("confirmed") or []
    parts.append("## Confirmed\n")
    if confirmed:
        for row in confirmed:
            parts.append(
                f"- **{row.get('artifact', '?')}** — "
                f"{row.get('claim', '')} "
                f"_(evidence: {row.get('evidence', '')})_"
            )
        parts.append("")
    else:
        parts.append("(no confirmed claims recorded)\n")

    return "\n".join(parts)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        required=True,
        help=(
            "pre-render JSON with `findings[]` (artifact + verdict + "
            "spec_says + code_says + evidence + title + issue + "
            "why_it_matters + suggested_fix + severity + locations[]) "
            "and optional `supplementary`"
        ),
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        required=True,
        help="directory for output files (typically the project root)",
    )
    parser.add_argument(
        "--project-name",
        required=True,
        help="project name used in output filenames",
    )
    parser.add_argument(
        "--issues",
        type=Path,
        default=None,
        help="optional path to a JSON array of meta-issue objects",
    )
    args = parser.parse_args(argv)

    with args.input.open("r", encoding="utf-8") as fh:
        pre_render = json.load(fh)

    try:
        issues = load_issues_file(args.issues)
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    envelope = _build_c4_envelope(pre_render, args.project_name, issues)

    try:
        validate_envelope(envelope)
    except jsonschema.ValidationError as exc:
        print(format_validation_error(exc, "c4-validation"), file=sys.stderr)
        return 1

    args.out_dir.mkdir(parents=True, exist_ok=True)
    base = "Findings-c4-reverse-engineer"
    json_path = args.out_dir / f"{base}.json"
    md_path = args.out_dir / f"{base}.md"

    with json_path.open("w", encoding="utf-8") as fh:
        json.dump(envelope, fh, indent=2)
        fh.write("\n")
    md_path.write_text(render_markdown(envelope, args.project_name), encoding="utf-8")

    print(f"render-c4-validation: wrote {json_path}, {md_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
